### PR TITLE
Php notice silent

### PR DESCRIPTION
**Pull request by Sufir**
Fast fix for this issue https://github.com/google/protobuf/issues/2465

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by NicklasWallgren** [comment]
Any progress?

**Comment by TeBoring** [comment]
The fix for autoload in #2532 has been merged.
Does the enum problem exist against master?

**Comment by TeBoring** [comment]
@Sufir Have you signed the CLA?

**Comment by Sufir** [comment]
> @Sufir Have you signed the CLA?
@TeBoring yes I have?

**Comment by TeBoring** [comment]
@Sufir Is the email for sending the pull request and the one in the commit the same?

**Comment by Sufir** [comment]
Yes, but I accepted after commit and don't know how it correctly recheck now.
Just another pull request https://github.com/google/protobuf/pull/2569

**Pull request closed without merging**
