### PR TITLE
Extract protoc action into .bzl for cc.

### PR DESCRIPTION
**Pull request by pherl**
This is needed to support python bazel build.

@xfxyjwf  for review.

[Review on Reviewable](https://reviewable.io/reviews/google/protobuf/883)

### CODE REVIEW

**Comment by xfxyjwf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[BUILD, line 150 \[r1\]](https://reviewable.io:443/reviews/google/protobuf/883#-K0hpim8TPifrjyKGZcA)** ([raw file](https://github.com/google/protobuf/blob/9c7d9c0925ebed800e4e41b298de9d97fd429679/BUILD#L150)):</sup>
So "deps" is to contain "cc_library"s and "proto_deps" is to contain "cc_proto_library"s? It seems more nature to me to use "deps" for "proto_library" dependencies. How about:
deps => for cc_proto_library rules
cc_lib => for cc_library dependencies

This aligns more with our internal proto_library rule.


---

<sup>**[protobuf.bzl, line 68 \[r1\]](https://reviewable.io:443/reviews/google/protobuf/883#-K0hqbySAA81l76wE96b)** ([raw file](https://github.com/google/protobuf/blob/9c7d9c0925ebed800e4e41b298de9d97fd429679/protobuf.bzl#L68)):</sup>
Move this to the beginning of the file and add comments explaining each parameter?


---

<sup>**[protobuf.bzl, line 71 \[r1\]](https://reviewable.io:443/reviews/google/protobuf/883#-K0hqsgWAukQJ8XSHH16)** ([raw file](https://github.com/google/protobuf/blob/9c7d9c0925ebed800e4e41b298de9d97fd429679/protobuf.bzl#L71)):</sup>
Will this relative ":protoc" work on a different package?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/protobuf/883)

**Comment by pherl** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[BUILD, line 150 \[r1\]](https://reviewable.io:443/reviews/google/protobuf/883#-K0hpim8TPifrjyKGZcA)** ([raw file](https://github.com/google/protobuf/blob/9c7d9c0925ebed800e4e41b298de9d97fd429679/BUILD#L150)):</sup>
Done.


---

<sup>**[protobuf.bzl, line 68 \[r1\]](https://reviewable.io:443/reviews/google/protobuf/883#-K0hqbySAA81l76wE96b)** ([raw file](https://github.com/google/protobuf/blob/9c7d9c0925ebed800e4e41b298de9d97fd429679/protobuf.bzl#L68)):</sup>
Added comments. However we cannot move it to the top of the file, due to referenced internal functions. It seems like bazel uses a different interpreter than python. 


---

<sup>**[protobuf.bzl, line 71 \[r1\]](https://reviewable.io:443/reviews/google/protobuf/883#-K0hqsgWAukQJ8XSHH16)** ([raw file](https://github.com/google/protobuf/blob/9c7d9c0925ebed800e4e41b298de9d97fd429679/protobuf.bzl#L71)):</sup>
This bzl file is only intended to be used in the protobuf BUILD only. We need to use relative path, otherwise, it won't work when the protobuf package is imported into other project's third_party directory.

Other users should wait for the bazel team to roll out the official proto_library support.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/protobuf/883)

**Comment by xfxyjwf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[protobuf.bzl, line 71 \[r1\]](https://reviewable.io:443/reviews/google/protobuf/883#-K0hqsgWAukQJ8XSHH16)** ([raw file](https://github.com/google/protobuf/blob/9c7d9c0925ebed800e4e41b298de9d97fd429679/protobuf.bzl#L71)):</sup>
I thought this protobuf.bzl is going be used by users. If we are waiting for bazel team to support proto_library, what do we need this protobuf.bzl file for? Our BUILD file can work without this bzl file.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/protobuf/883)

**Comment by pherl** [comment]
It was to introduce to avoid duplicated code for python support. Otherwise,
the BUILD file seems to be too complicated due to the import path issue.

**Comment by xfxyjwf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/protobuf/883)

**Comment by xfxyjwf** [comment]
LGTM

**Pull request merged**
