### PR TITLE
Add missing PY2AND3 srcs_versions attributes to Python Bazel build targets

### PR DESCRIPTION
**Pull request by davidzchen**
This is to fix the build break in tensorflow/tensorflow#1289

+cc @martinwicke @podsvirov

### CODE REVIEW

**Comment by xfxyjwf** [comment]
@haberman to review the change. Do we currently have test coverage for bazel on Jenkins?

**Comment by davidzchen** [comment]
Ping

**Comment by podsvirov** [comment]
Hello @davidzchen!
I love C ++ and well versed in CMake.
I contributed to the project in terms of improvement protobuf CMake project.
How can I help in this case?
I read about a variable srcs_version = "PY2AND3", but do not know where it can be used in C ++ code? Teach me :-)

**Comment by davidzchen** [comment]
@podsvirov, thanks for your enthusiasm. This particular PR, and the `srcs_version = "PY2AND3"` attribute, is specifically for the [Bazel](http://bazel.io) build for protobuf. I don't think that the CMake build for protobuf has this issue.

**Comment by xfxyjwf** [comment]
ping @haberman

**Comment by davidzchen** [comment]
Can someone take a look at this?

**Comment by martinwicke** [comment]
Thanks!

**Pull request merged**
