### PR TITLE
CMake: Add modern protobuf_generate

### PR DESCRIPTION
**Pull request by yeswalrus**
protobuf_generate_cpp and _python saved some typing, but were rather out of date. This adds an updated version that is more extensible, uses proper argument parsing and allows TARGET arguments. Should allow a better experience for anyone using CMake 3.1 and up.

- [ ] Depends on https://github.com/google/protobuf/pull/3157

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by acozzette** [comment]
ok to test (this comment will kick off the other CI runs)

**Comment by acozzette** [comment]
retest this please (this comment will trigger the tests to run again)

**Pull request merged**
