### PR TITLE
Sync the manually integrate changes in google3/third_party

### PR DESCRIPTION
**Pull request by anandolee**

### CODE REVIEW

**Comment by xfxyjwf** [comment]
ok to test

**Comment by xfxyjwf** [comment]
@haberman How do I trigger the Jenkins tests? "ok to test" doesn't seem to work for me.

**Comment by haberman** [comment]
Sorry Feng, it looks like I misspelled your username when I added it to Jenkins. It should work for you now.

Also I added Jie to the list of admins so her CLs should test right away now.

**Comment by xfxyjwf** [comment]
Thanks Josh!

**Comment by xfxyjwf** [comment]
Jenkins tests are already done, while travis tests are not started yet...

**Comment by xfxyjwf** [comment]
LGTM

**Pull request merged**
