### PR TITLE
Add support for setting the unknown field and unknown enum behavior in text parsers.

### PR DESCRIPTION
**Pull request by murraystokely**

### CODE REVIEW

**Comment by murraystokely** [comment]
I signed it!

**Comment by murraystokely** [comment]
I signed it!

**Comment by xfxyjwf** [comment]
Hmm, this method actually already exists in our internal code base for a long time but it's removed from opensource release intentionally. The idea is that text format parsing is mostly used in tests or configurations, where unknown fields are more likely to be caused by typos rather than intentional. For this reason we discourage allowing unknown fields in text format and excluded it for opensource release.

Could you tell us about the use case that motivates this PR?

**Comment by murraystokely** [comment]
This functionality is important for large organizations using protocol buffers without the benefit of Google's internal Protocol Buffer Descriptor Database (globalprotodb).  In federated environments with different distributed systems using protocol buffers but without as robust of a centralized system for protocol buffer schemas different applications can be running with different versions of the .proto files.  In such cases, the text representation is useless without these two flags.  This has come up for me multiple times in real production code since I left Google, but I can see why it never would have been an issue inside Google.  Add a comment telling users to use it at their own risk, but please provide some way for me to explicitly set this in the library.

**Comment by xfxyjwf** [comment]
@pherl , are you OK with allowing opensource users to set the allow_unknown_fields in text format?

**Comment by davidsansome** [comment]
This would be useful for Chrome infrastructure too.
We store some configurations as text protobufs and push these separately to the code.  When we add a new field to a proto and update the configs, it's then impossible to roll back the code without rolling back the configs too.  This caused http://o/e/m248c1d0b58000077 yesterday.

**Comment by xfxyjwf** [comment]
We should make the change to the internal code base instead.  https://github.com/google/protobuf/issues/4821

**Pull request closed without merging**
