### PR TITLE
Fix policy warning CMP0054

### PR DESCRIPTION
**Pull request by yeswalrus**
As the title says.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by gabm** [comment]
@yeswalrus Is this still active? .. the warning still seems to persist, right?

**Comment by yeswalrus** [comment]
Should be, yeah.

**Pull request merged**
