### PR TITLE
Proto3 map support for C#

### PR DESCRIPTION
**Pull request by jskeet**
There are still some open questions about handling strings and ByteStrings, but this is a good first step.

### CODE REVIEW

**Comment by jskeet** [comment]
@jtattermusch @anandolee

**Comment by jskeet** [comment]
I've made the requested changes from #544 - I've added all the relevant tests I can think of, and the coverage looks pretty good... are there any other tests you'd like before I merge this?

(I haven't rebased the cleanup work yet - I'll do that when I merge this.)

**Comment by jskeet** [comment]
Just found another bug with FieldCodec - will write significant tests for this before merging...

**Comment by jskeet** [comment]
Okay, with the fix to FieldCodec (and some tests for it, finally :) I think I'm happy with this again.
@anandolee does my last comment around keeping the tests for testing make sense?

**Comment by jtattermusch** [comment]
I went through the code and LGTM (ex-post, because it's already been merged).

**Pull request merged**
