### PR TITLE
Implement nullable syntaxic sugar keyword

### PR DESCRIPTION
**Pull request by dopuskh3**
Implementation proposal for nullable keyword that convert a scalar field to a one-field oneof.

Issue #1606

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by dopuskh3** [comment]
I signed it!

**Comment by heyleke** [comment]
What is the status of this, I see Travis fails on a PHP issue, does that mean this pull request will not go to master? And it needs a fix?

**Comment by xfxyjwf** [comment]
This PR implements a proposal that hasn't been reviewed/approved (the review is undergoing). I'll post back with status update of the review which is either approved or rejected.

**Comment by dopuskh3** [comment]
Hi @xfxyjwf , 

After some dicussions with @acozzette, it looks like making this change accepted could require some time and work.

Alternatively, I'm currently working on adding insertion points for setters and getter that will allow us to implement nullable fields using a less intrusive fashion:

- Adding a message option that tells if a specific message should support for nullable fields.
- If it does, then make declaration of a map<int32, bool> using a reserved field id required for message and all its nested message declarations
- Inject code in setters and getters to modify the content of the map value for corresponding field id.
- Inject hasXXX for message fields. 

The proposal has been done here Issue #2685. 

In the comming hours/day I will modify my merge request to add 2 insertion points per setters so that we can inject at the beginning or end of the corresponding setters.

I almost have a plugin working and implementing this.

**Comment by xfxyjwf** [comment]
As I posted at https://github.com/google/protobuf/issues/1606#issuecomment-281832148, the team decided to not move forward with this proposal.

**Pull request closed without merging**
