### PR TITLE
remove bind for six

### PR DESCRIPTION
**Pull request by shariat**
- removing bind is recommended 
https://github.com/bazelbuild/bazel/issues/1952
and
https://docs.bazel.build/versions/master/best-practices.html#repository-rules

- it conflicts with other external repos that have `@six` like `rules_docker`

I recommend the rest of bind rules be removed as well.

### CODE REVIEW

**Comment by shariat** [comment]
any hope merging this?

**Comment by pherl** [comment]
How would this change the existing users' setup? They need to use load the repositories.bzl and call protobuf_dependencies()? Is there any migration path so we can roll out this change without breaking user build in the next release?

Also this approach forces protobuf to stick to a specific six version. What if there are multiple libraries using the six but specifying different versions? This makes it impossible for the end users to use those libraries together without causing symbol conflicts. While by using bind(), it's the end users' choice which version the dependency sticks to.

I don't see using the archive is a clear win over bind() approach. There are still open issues.

**Comment by shariat** [comment]
yes, they have to call `protobuf_dependencies()`. The different version problem is kind of fixed by checking if the lib is already loaded or not. This is what other libraries are doing as well https://github.com/bazelbuild/rules_docker/blob/master/container/container.bzl#L84

**Comment by shariat** [comment]
main discussion is here https://github.com/bazelbuild/bazel/issues/1952

**Comment by pherl** [comment]
I commented on the thread.

**Comment by shariat** [comment]
@pherl btw, users do not have to call `protobuf_dependencies()`. `protobuf_dependencies()` is for convenience. Users can define the dependencies as before.

**Comment by pherl** [comment]
My understanding is users have to change bind() to a explicit repo named "six". This has to been done atomically when users upgrade their protobuf dependency. In this case, the change on the protobuf is a breaking change.

**Comment by pherl** [comment]
Because we use it? https://github.com/google/protobuf/search?utf8=%E2%9C%93&q=six&type=

**Comment by shariat** [comment]
yes, but `//external:six` is only used in `//:protobuf_python`. the output of that rule is `_pb2.py` files that do not import `six`.

**Comment by pherl** [comment]
`//:protobuf_python` is the only public target for users to depend on. It transitively include `//:python_srcs` which requires the `six` dependency. I guess a cleaner fix is to move the the `six` dependency to `//:python_srcs` where the library is actually used.

**Pull request closed without merging**
