### PR TITLE
Use std::get where it's available

### PR DESCRIPTION
**Pull request by TeBoring**

### CODE REVIEW

**Comment by TeBoring** [comment]
@xfxyjwf to review

**Comment by xfxyjwf** [comment]
LGTM

**Comment by mxmark** [comment]
Hi, This change moves functions like "Closure * NewCallback(..)" into the internal namespace. Is it okay to use such functions inside this "internal" namespace ? If not, is there a new recommended way to create Closures that we we can pass to the stubs generated by the protobuf compiler ?

**Comment by xfxyjwf** [comment]
@mxmark hmm, I didn't notice that Closure/Callback is used in the generated stub code. I guess we just need to move the related code back to google::protobuf namespace... Can you help create a github issue for that?

**Comment by mxmark** [comment]
Thanks @xfxyjwf for the quick reply! I created https://github.com/google/protobuf/issues/1966 for this.

**Pull request merged**
