### PR TITLE
Add insertion points for field modifiers in C# and Java

### PR DESCRIPTION
**Pull request by gturri**
With those insertion points, we're able to implement a plugin that does what is
described on #2684. ie: with those patches, we're able to make a distinction
between a field which has a default value and a field which isn't set.

Said differently, this is how we solve #1606 for Java and C#

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by gturri** [comment]
CLA should be fixed now

**Comment by gturri** [comment]
new test for CLA

**Comment by xfxyjwf** [comment]
Can you split this into two PRs, one with C# change and the other with Java change? Also please direct them to the master branch as only bug fixes should go into patch releases.

**Comment by gturri** [comment]
Sure!
I just created #3291 and #3292 accordingly.

**Pull request closed without merging**
