### PR TITLE
Objective C Second Alpha Drop

### PR DESCRIPTION
**Pull request by thomasvl**
- Style fixups in the code.
- map<> serialization fixes and more tests.
- Autocreation of map<> fields (to match repeated fields).
- @@protoc_insertion_point(global_scope|imports).
- Fixup proto2 syntax extension support.
- Move all startup code to +initialize so it happen on class usage and not app startup.
- Have generated headers use forward declarations and move imports into generated code, reduces what is need at compile time to speed up compiled and avoid pointless rippling of rebuilds.

### CODE REVIEW

**Comment by thomasvl** [comment]
This also covers #365

**Comment by TeBoring** [comment]
Could you also help write a README.md about how to use/build the library and the minimum requirement to use/build it?

**Comment by thomasvl** [comment]
On Fri, May 22, 2015 at 10:46 AM, Paul Yang <notifications@github.com>
wrote:

> Could you also help write a README.md about how to use/build the library
> and the minimum requirement to use/build it?
>

Yup, I've got a few other things in the queue, can I include in the next
big drop, or do you need it in this one?

**Comment by TeBoring** [comment]
I need the README in this release.

**Comment by thomasvl** [comment]
README.md added.

**Comment by TeBoring** [comment]
LGTM

**Pull request merged**
