### PR TITLE
Generate C# directory hierarchy with new option

### LINKED ISSUE #773: Consider populating a directory hierarchy for C# based on namespace
Currently we don't do this because in .NET projects there tends to be a "base" namespace, but I think we'll want to address this with another flag, based on a bit of experience of trying to use the current approach.

Proposal:

- Add a new flag of `csharp_base_package`
- When working out where to generate code, generate a directory name based on the namespace from the base package onwards. For example, if the base package is `a.b` and the declared package for the .proto file is `a.b.c.d`, create a directory of `C.D` and put the code in there, in a namespace of A.B.C.D
- If `csharp_base_package` isn't specified, treat it as empty (e.g. create a directory of `A.B.C.D` in the above example)
- If `csharp_base_package` is specified but the .proto package doesn't start with that, fail

Alternatives to consider:

- Specify the base namespace instead of base package (e.g. `A.B` instead of `a.b`)
- Have yet another flag to allow the existing behaviour of not creating directories

The GRPC plugin should do the same thing.

Thoughts?

@anandolee @jtattermusch

### PR DESCRIPTION
**Pull request by jskeet**
This introduces a new C# option, base_namespace.
If the option is not specified, the behaviour is as before: no directories are generated.
If the option *is* specified, all C# namespaces must be relative to the base namespace, and the directories are generated relative to that namespace.

Example:
- Any.proto declares csharp_namespace = "Google.Protobuf.WellKnownTypes"
- We build with --csharp_out=Google.Protobuf --csharp_opt=base_namespace=Google.Protobuf
- The Any.cs file is generated in Google.Protobuf/WellKnownTypes (where it currently lives)

This PR fixes #773.

// cc @anandolee

### CODE REVIEW

**Comment by jskeet** [comment]
@jtattermusch Jan, have you had a chance to look at this?

**Comment by jskeet** [comment]
Yes, that's exactly what it will do - at least, that's what it's intended to do :) I'll double-check that it really *does* do that...

**Comment by jtattermusch** [comment]
@xfxyjwf  is there a way to make a command line option "base_namespace" in "--csharp_opt=base_namespace=Google.Protobuf" shared across multiple protoc plugins (C# plugin and gRPC C# plugin in our case)?  If so, is that something you would recommend?

**Comment by xfxyjwf** [comment]
No, there isn't a way to share the command line options between different plugins. Protoc treat each plugin as an independent code generator and do not pass any information between them.

**Comment by jtattermusch** [comment]
Alright, it looks like exposing GetOutputFile in csharp_names.h should be easy, so I will merge this now and expose the function in a followup PR.

**Pull request merged**
