### PR TITLE
Fix the PHP extension building in Windows

### PR DESCRIPTION
**Pull request by zsxsoft**
Instruction: Follow the guideline "Building PECL extensions" in https://wiki.php.net/internals/windows/stepbystepbuild, copy all files in ``php/ext/google/protobuf/`` to ``phpdev\vc14\x64\pecl\protobuf``, and configure with ``configure --disable-all --enable-cli --enable-protobuf=shared --disable-zts``

image

image
image

This PR just fixed building on Windows, anyway, there're lots of warning when I compiling it and if I call any function like ``\Google\Protobuf\Internal\DescriptorPool::internalAddGeneratedFile``, it will still crash PHP.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by zsxsoft** [comment]
I signed.

**Comment by TeBoring** [comment]
Before dive into the detail of this PR, can we add a continuous test on windows first?

**Comment by zsxsoft** [comment]
I think I need help for writing ``appveyor.bat``, I don't know why it returns OK not as expected..

**Comment by TeBoring** [comment]
I guess it's because you don't mention: goto error.

**Comment by TeBoring** [comment]
You could try: make || goto error

**Comment by zsxsoft** [comment]
I found that ``php_setvars`` and ``phpsdk_buildtree`` will break the batch.

**Comment by zsxsoft** [comment]
OK, AppVeyor build succeeded

**Comment by TeBoring** [comment]
Awesome. Could you add a test scrip to run tests in php/test/test.sh?

**Comment by zsxsoft** [comment]
OK, added. ``phpunit`` command with no result means php crashed.
```
****************************
*    array_test.php
****************************
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
..FF....****************************
*    encode_decode_test.php
****************************
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
****************************
*    generated_class_test.php
****************************
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
****************************
*    generated_phpdoc_test.php
****************************
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
...............................                                  31 / 31 (100%)
Time: 133 ms, Memory: 10.00MB
OK (31 tests, 156 assertions)
****************************
*    map_field_test.php
****************************
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
..FF....****************************
*    well_known_test.php
****************************
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
****************************
*    generated_service_test.php
****************************
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
.........                                                          9 / 9 (100%)
Time: 137 ms, Memory: 10.00MB
OK (9 tests, 34 assertions)
****************************
*    descriptors_test.php
****************************
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
```

**Comment by TeBoring** [comment]
Do you need help to fix failing tests?

**Comment by zsxsoft** [comment]
According to the count of warning, I don't think it's easy to fix even only one test.

**Comment by zsxsoft** [comment]
It'll crash at 
image

Return back to the stack, I found ``getsubhandlers`` returned something wrong when ``f->_index == 0``

image


So it feels like the mistake by ``upb_descreader_newhandlers``.

**Comment by TeBoring** [comment]
ok, I'll take a look.

**Pull request closed without merging**
