### PR TITLE
Podsvirov CMake changes backported to 3.0.x

### PR DESCRIPTION
**Pull request by rpavlik**
These are CMake changes, including an essential bugfix for `protobuf_MODULE_COMPATIBLE`, originally found in #1865 by @podsvirov - all I did was a `git rebase --onto` to get them on the 3.0.x branch.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by rpavlik** [comment]
I previously had the CLA signed (via employer) - I have an invite that I accepted back on august 3, 2015 to authorized-google-contributors. I suspect the fact that we switched to Google Apps, err, GSuite, since then might be causing the confusion with the CLA verification.

**Comment by acozzette** [comment]
ok to test

**Comment by acozzette** [comment]
retest this please (talking to the Jenkins bot)

**Comment by acozzette** [comment]
@rpavlik Actually I believe we are no longer really maintaining the 3.0.x branch and we likely won't be making any more releases in the 3.0.x series. In that case is there any particular reason you need to backport these fixes?

**Comment by rpavlik** [comment]
I signed it!

**Comment by rpavlik** [comment]
I wasn't sure what the branch maintenance policy was - it didn't appear to be laid out clearly anywhere (nor did anything newer than 3.0.0 show up on Google Developers page when I checked), and I assumed the presence of a 3.0.x branch, in the absence of other guidance, was then a stable release. Fine by me if no more 3.0.x releases occur, but then it probably should be documented somewhere :D (release notes of the downloads in GitHub would be one place to start...)

**Pull request closed without merging**
