### PR TITLE
Support to compile OK on MacOS and fix compile warning

### LINKED ISSUE #2155: make error in php on macos
Infos:

    cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/protobuf.so -bundle  .libs/array.o .libs/def.o .libs/encode_decode.o .libs/map.o .libs/message.o .libs/protobuf.o .libs/storage.o .libs/type_check.o .libs/upb.o .libs/utf8.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/def.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/encode_decode.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/map.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/message.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/protobuf.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/storage.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/type_check.o
    ld: 7 duplicate symbols for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [protobuf.la] Error 1

### PR DESCRIPTION
**Pull request by thinkerou**
Fix #2155
1. Delete `ZEND_DECLARE_MODULE_GLOBALS(protobuf)` in `protobuf.h` because it lead to `duplicate symbol _protobuf_globals` error.
2. Fix some warns and errors.

### CODE REVIEW

**Comment by TeBoring** [comment]
ok to test

**Comment by TeBoring** [comment]
Could you squash all commits into a single one?

**Comment by TeBoring** [comment]
Please send you PR to 3.1.x branch.

**Comment by thinkerou** [comment]
OK

**Comment by thinkerou** [comment]
Hi, @TeBoring I found the PR codes have commited on 3.1.x branch, right? need I commit?

**Comment by TeBoring** [comment]
@thinkerou, I have fixed this in 3.1.x branch. Thanks for your help.

**Pull request closed without merging**
