### PR TITLE
changes for CMake to support cross-compilation

### PR DESCRIPTION
**Pull request by Slonegg**
I'm working on GRPC and Protobuf for Android. Here are changes to build protobuf with CMake for Android. Instructions (MSVS + Ninja):

1. Install [Android SDK](https://developer.android.com/studio/index.html)
2. Install [Android NDK](https://developer.android.com/ndk/guides/index.html). Generally only NDK is necessary, SDK just may be useful for other purposes.
3. Set environment variable `ANDROID_NDK=<NDK location>`
4. Install [Ninja](https://github.com/ninja-build/ninja/releases). Just drop `ninja.exe` somewhere where it can be accessed from command line, for example, alongside cmake binaries.
5. Build protobuf for host, because we will need protoc executable that we can run on host:
```
    mkdir _host_build
    cd _host_build
    "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
    cmake ../cmake -G Ninja -Dprotobuf_BUILD_TESTS=OFF
    ninja
```
6. Build protobuf for android
```
    mkdir _android_build
    cd _android_build
    cmake ../cmake -G Ninja -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_STL_TYPE=gnustl_static -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_IMPORT_EXECUTABLES=../_host_build/protobuf_ImportExecutables.cmake
    ninja
```

Also should fix https://github.com/google/protobuf/issues/2719

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by Slonegg** [comment]
I signed it!

**Comment by podsvirov** [comment]
Hello @Slonegg,  this should work, but it does not look very nice for me. We could add `protobuf_CROSSCOMPILING` user option and use the existing mechanism of export and import protobuf targets via `protobuf` package.

**Comment by Slonegg** [comment]
@podsvirov you mean just replace CMAKE_CROSSCOMPILING with protobuf_CROSSCOMPILING? This I can do. I don't understand about using existing mechanism of import/export protobuf, though, this is the first time I look at protobuf sources.

**Comment by podsvirov** [comment]
@Slonegg, a little more changes are required. If you are not in a hurry and give me time, I will suggest a more beautiful solution.

**Comment by Slonegg** [comment]
Sure, thanks @podsvirov, we use our forks anyway.

**Comment by podsvirov** [comment]
Hello @xfxyjwf, CMake project was originally created to build with MSVC, but time showed that it works on other platforms.
Please, do not accept this change yet. In the near future (possibly several days) I will propose alternative changes in accordance with the code that we already have.

**Comment by podsvirov** [comment]
@Slonegg, please review #2998.

With #2998 you can build protobuf libraries for Android via one step:
```
mkdir _android_build
cd _android_build
cmake ../cmake -G Ninja -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_STL_TYPE=gnustl_static
ninja
```

NOTE: -Dprotobuf_BUILD_TESTS=OFF - also not need now.

**Comment by Slonegg** [comment]
@podsvirov I see, but generally you'll still need to compile protobuf twice if you want to develop for android. Because you need protoc executable for host operating system, so you can generate *.cpp *.h for Android/iOS etc.

**Pull request closed without merging**
