### PR TITLE
[ruby] Fix RepeatedField#delete_if

### LINKED ISSUE #4285: Ruby RepeatedField doesn't implement #delete_if correctly
`Google::Protobuf::RepeatedField#delete_if` doesn't appear to be implemented correctly. I think it's defined using the wrong helper method (`define_array_wrapper_method`, instead of `define_array_wrapper_with_result_method`).

Given the following generated Ruby classes:
```ruby
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testing.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Member" do
    optional :id, :string, 1
  end
  add_message "Collection" do
    repeated :collection, :message, 1, "Member"
  end
end

Member = Google::Protobuf::DescriptorPool.generated_pool.lookup("Member").msgclass
Collection = Google::Protobuf::DescriptorPool.generated_pool.lookup("Collection").msgclass
```

This is the behaviour of `RepeatedField#delete_if`:
```ruby
[7] pry(main)> coll = Collection.new(collection: [{id: "a"}, {id: "b"}])
=> <Collection: collection: [<Member: id: "a">, <Member: id: "b">]>
[8] pry(main)> coll.collection.delete_if { |m| m.id == "a" }
=> #<Enumerator: ...>
[9] pry(main)> coll.collection
=> [<Member: id: "a">, <Member: id: "b">]
```

This is the expected behaviour as demonstrated by `Array#delete_if`:
```ruby
[3] pry(main)> arr = [Member.new(id: "a"), Member.new(id: "b")]
=> [<Member: id: "a">, <Member: id: "b">]
[4] pry(main)> arr.delete_if { |m| m.id == "a" }
=> [<Member: id: "b">]
[5] pry(main)> arr
=> [<Member: id: "b">]
```

### PR DESCRIPTION
**Pull request by harto**
Make RepeatedField#delete_if consistent with Array#delete_if.

Fixes #4285.

### CODE REVIEW

**Comment by harto** [comment]
I signed it!

**Comment by janpaul123** [comment]
🎉

**Comment by harto** [comment]
Hi! Anything I can do to help get this reviewed/merged?

**Comment by anandolee** [comment]
ping @TeBoring

**Pull request merged**
