### PR TITLE
Reflection part 2 - for discussion

### PR DESCRIPTION
**Pull request by jskeet**
This is relative to PR #625.

An alternative would be to make Fields a FieldCollection, so we'd use

```csharp
descriptor.Fields[fieldNumber].Accessor.GetValue(...)
```

That's not that different from:
```csharp
descriptor.FieldAccessors[fieldNumber].GetValue(...)
```

... but is less accessor-specific. We could then rename the Fields list to FieldsInDeclarationOrder or something like that.

Oh, and we possibly want to expose a sorted-by-number collection... which FieldCollection could do as an `IEnumerable<T>` of course, with the slight oddity that `fields[5]` wouldn't be the same as `fields.ElementAt(5)`. Hmm.

### CODE REVIEW

**Comment by jtattermusch** [comment]
How about we introduce FieldCollection, that has the same kind of indexer [by field number and by name]  and also expose methods IList<>.InDeclarationOrder()  and IList<>.InFieldNumberOrder() - and there would be no "default" ordering, so that everyone has to specify explicitly which ordering he's interested in and there will be no confusion.

Once we have that, FieldAccessorCollection can just provide abbreviated syntax with the indexer.

**Comment by jskeet** [comment]
I don't think there's any need for FieldAccessorCollection at all, too be honest, once we've got FieldCollection. I'll change this PR to show you want I mean - with the methods you've suggested too.

**Comment by jtattermusch** [comment]
Yeah, this looks pretty good. Two nits for the future:
--  Fields["somefield"].Accessor.GetValue still feels unnecessarily chatty, reintroducing simplified version of FieldAccessorCollection might improve discoverability of the feature by new users.
-- having FieldCollection with indexer, there's no need to expose methods FindFieldByName and FindFieldByFieldNumber, perhaps we can make them internal. I like the idea of getting the API slimmer.

Feel free to merge once travis is green.

**Comment by jskeet** [comment]
Hmm. I suspect Travis may be stuck. Will see whether it's cleared in the morning...

**Pull request merged**
