### PR TITLE
PHP fix int64 decoding

### PR DESCRIPTION
**Pull request by Sufir**
Fix for that issue https://github.com/google/protobuf/issues/2503

Decoding before:
```
+----------------------+----------------------+
| Original             | Decoded              |
+----------------------+----------------------+
| 10000                | 10000                |
| 100000               | 100000               |
| 1000000              | 1000000              |
| 10000000             | 10000000             |
| 100000000            | 100000000            |
| 1000000000           | 13884901888          |
| 10000000000          | 22884901888          |
| 100000000000         | 87115098112          |
| 1000000000000        | 1021474836480        |
| 10000000000000       | 10017179869184       |
| 100000000000000      | 99991410065408       |
| 1000000000000000     | 999982820130816      |
| 10000000000000000    | 10000017179869184    |
| 100000000000000000   | 100000021474836480   |
| 1000000000000000000  | 999999995705032704   |
+----------------------+----------------------+
```

Decoding now:
```
+----------------------+---------------------+
| Original             | Decoded             |
+----------------------+---------------------+
| 1000000             | 1000000             | 
| 10000000            | 10000000            | 
| 100000000           | 100000000           | 
| 1000000000          | 1000000000          | 
| 10000000000         | 10000000000         | 
| 100000000000        | 100000000000        | 
| 1000000000000       | 1000000000000       | 
| 10000000000000      | 10000000000000      | 
| 100000000000000     | 100000000000000     | 
| 1000000000000000    | 1000000000000000    | 
| 10000000000000000   | 10000000000000000   | 
| 100000000000000000  | 100000000000000000  | 
| 1000000000000000000 | 1000000000000000000 |
+---------------------+---------------------+
```

Im not sure about x32 PHP (dont need it) but good work on x64

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by TeBoring** [comment]
ok to test

**Comment by TeBoring** [comment]
Could you also add a test?

**Comment by NicklasWallgren** [comment]
Any progress?

**Comment by TeBoring** [comment]
@Sufir Could you add a test to verify the fix? And reply the comment?

**Comment by TeBoring** [comment]
LGTM

**Pull request merged**
