### PR TITLE
Handle "reserved" field names which would otherwise cause member collisions

### PR DESCRIPTION
**Pull request by jskeet**
(Based on PR #660)

### CODE REVIEW

**Comment by jtattermusch** [comment]
Let's recreate this PR against master.

**Comment by jtattermusch** [comment]
LGTM, please merge into master after rebasing.

**Comment by jskeet** [comment]
Looks like I can't change the target branch of the PR. Will close this and create a new one.

**Comment by KJTsanaktsidis** [comment]
Interestingly the C++ generated code also has this problem. The generated code will not compile if a field is called `descriptor`, `default_instance`,  `unknown_fields` or `mutable_unknown_fields`. Also I suspect you'll run into problems if you try and define an optional field called `foo` and a seperate field called `has_foo`.

**Pull request closed without merging**
