### PR TITLE
Update to new canonical 'ez_setup.py'.

### PR DESCRIPTION
**Pull request by tseaver**
Downloaded from https://bootstrap.pypa.io/ez_setup.py.

### CODE REVIEW

**Comment by tamird** [comment]
@tseaver this is pretty stale. mind updating it?

**Comment by tseaver** [comment]
@tamird rebased for your reviewing pleasure.

**Comment by tamird** [comment]
Sorry, I meant that the file itself is stale - please download the current version

**Comment by tamird** [comment]
@haberman mind merging this?

**Comment by Ivoz** [comment]
Since https://github.com/google/protobuf/commit/3bdfb4b6951ad3db1a9493e86cd76f4f1c4d8986#diff-8cf6167d58ce775a08acafcfe6f40966, I'd guess this can be closed now.

**Pull request closed without merging**
