### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by vidbina**
The Dockerfile should provides an env that contains all deps. This should simplify setup for dev and test purposes.

Shall we setup an automated build for this on Docker hub?

[](https://microbadger.com/images/vidbina/protobuf)

### CODE REVIEW

**Comment by vidbina** [comment]
I signed it!

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by haberman** [comment]
@xfxyjwf does a Dockerfile seem like something we should add to the repo?

**Comment by xfxyjwf** [comment]
A Docker file for protobuf alone doesn't seem very useful because it's rare for an user to only need to use protobuf and nothing else. It's probably helpful for users who are learning using protobuf though, but that should goes into the examples directory.

**Comment by xfxyjwf** [comment]
This PR needs to be reworked in any case (merge conflicts, cla:no, and many unneeded commits).

**Pull request closed without merging**
