### PR TITLE
Add a project targeting .NET Core

### PR DESCRIPTION
**Pull request by Flavien**
This is for the C# implementation.

I created a new project targeting .NET Core (DNX Core 5.0), which should make it cross platform (OS X, Linux). It would be nice to release this as a beta/preview NuGet package for those who need to target .NET Core.

So far it's only the ProtocolBuffersLite assembly.

The solution will still round-trip to Visual Studio 2013, though you will get a message saying it can't open the ProtocolBuffersLiteCoreFx.

### CODE REVIEW

**Comment by Flavien** [comment]
CLA signed

**Comment by jskeet** [comment]
I'd really rather avoid another project if at all possible - any reason we can't just make the existing project work with .NET Core? I believe it should just be a matter of supporting the relevant profile (258 IIRC, but that's off the top of my head.)

Note that in the csharp-experimental branch, I've killed off the Lite project as well - I'm trying to streamline all of this as much as possible.

**Comment by Flavien** [comment]
I've looked more into this. I've created another branch with new projects targeting DNX 4.5.1, DNX Core 5.0 and PCL profile 92 for the ProtocolBuffers and ProtocolBuffers.Serialization projects (non-lite): https://github.com/flavien/protobuf/tree/dnx

The problem with replacing the old projects with those is that you'd need to replace the test projects as well, and NUnit won't work with Visual Studio from an xproj project (Right now, only XUnit works).

**Comment by jskeet** [comment]
Again, I don't think an xproj is needed. Targeting profile 259 should be enough, I believe.
Also note that if you've been working off the master branch, all of that code is legacy, effectively - all work has been performed on the csharp-experimental branch.

**Comment by Flavien** [comment]
I think there might be a misunderstanding. I am not referring to the .NET Core used for Windows Store Applications. I'm referring to the [.NET Core DNX](http://dotnet.readthedocs.org/en/latest/dnx/overview.html) use by ASP.NET 5. I might be wrong, but I believe this can't be targeted by a PCL. JSON.NET had to do [the same](https://github.com/JamesNK/Newtonsoft.Json/blob/coreclr/Src/Newtonsoft.Json/project.json) for example.

**Comment by jskeet** [comment]
No, we're referring to the same thing. While Json.NET does have a project.json, I don't think it's a requirement... I emailed James about that exact question around the time that he created the project.json, interestingly enough. I suspect he created a project.json file so that he could ensure that he tested it running under DNX core... I can investigate similar things.

**Comment by jskeet** [comment]
I've just done this with Noda Time - built it against profile259, adjusted the nuspec file appropriately, and managed to get it building and running under dnxcore. No xproj files required in Noda Time at all.

**Comment by Flavien** [comment]
Great, I see that you already have a [pull request](https://github.com/google/protobuf/pull/638) under way, so I'll wait for the next version of the NuGet package and hopefully it should work with .NET Core.

**Comment by jskeet** [comment]
Indeed. We'll be testing that out ourselves of course - if you could kick the tires too when the package is created, that would be much appreciated :)

I'm going to close this PR for now - we can reopen it if the current plans fails. Let me know if there's anything in this PR that isn't covered by the current plan.

**Comment by Flavien** [comment]
I've been running the [3.0.0-alpha4 package](https://www.nuget.org/packages/google.protobuf) for some time, any idea when the 3.0.0 release will happen?

**Comment by jskeet** [comment]
Couldn't say, I'm afraid. I'm hard at work on json parsing at the moment...

Jon

**Comment by jaredthirsk** [comment]
I don't know anything about PCL's, but I am trying to use this in .NET Core 1.0.1 and it is telling me "One or more packages are incompatible with .NETStandard,Version=v1.4" (my project is a DLL targeting 1.4.)

My understanding of .NET Core is that xproj is not required but project.json is (at least until project.json disappears.)

**Comment by jskeet** [comment]
You should be fine for Google.Protobuf - we target netstandard1.0:
https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/project.json#L46

If you run `dotnet restore` it should show you exactly which dependency is causing the problem.

**Pull request closed without merging**
