### PR TITLE
Fix CMake version check

### PR DESCRIPTION
**Pull request by yeswalrus**
A number of fixes to the config-version.cmake file

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by acozzette** [comment]
ok to test (this comment will kick off the other CI runs)

**Comment by acozzette** [comment]
@yeswalrus Thanks for the pull request!

**Pull request merged**
