### PR TITLE
Fix bug: whether always_print_enums_as_ints is true or false, it alwa…

### PR DESCRIPTION
**Pull request by stone4774**
…ys print the default value of enums as strings

description of the problem:

call the function MessageToJsonString, and set both always_print_primitive_fields and always_print_enums_as_ints to true. it print the default value of enums as strings, does not as ints.

This submission resolved the issue

### CODE REVIEW

**Comment by stone4774** [comment]
Has been submitted, please check again.  Thanks

**Comment by xfxyjwf** [comment]
There is merge conflict with master. Could you update and resolve the conflict?

**Comment by stone4774** [comment]
It has been merged.

**Comment by stone4774** [comment]
Updated and the conflict resolved. Please take a look. Thanks.

**Pull request merged**
