### PR TITLE
Proto3 experimental C# fork

### PR DESCRIPTION
**Pull request by jskeet**
More to do, but this will allow others to contribute more easily...

### CODE REVIEW

**Comment by jskeet** [comment]
One note to be aware of - this branch contains a change to wire_format.h that we may not want. See 
https://github.com/google/protobuf/issues/493 - I can probably create a different workaround if desired.

**Comment by jskeet** [comment]
@jtattermusch @anandolee to review and merge.

**Comment by jtattermusch** [comment]
I went quickly through the changes commit-by-commit because it's too big to display at once. It looks good to me (for what we need right now), let's merge this so we allow contributions from others.

I've tried to identify changes that are potentially dangerous and that should be reviewed separately (as a second pass once we merge this - I am happy to create bugs for these):

"array as backing store"
commit https://github.com/jskeet/protobuf/commit/7532f0256f58e0d11711da4e159534bccbf266f0

"improve string encoding times"
commit https://github.com/jskeet/protobuf/commit/35e4dbd51829216fd1ad85a95c01042346b63c6b

"inlining tag sizes"
commit https://github.com/jskeet/protobuf/commit/828b7e61d0443832d99002fbda12a359e5f9f221
(I think "size += 1 + pb::CodedOutputStream.ComputeRawVarint32Size((uint) dataSize);" is not very understandable because it's not obvious where the "1" comes from, perhaps we could define constants for tag sizes, but let's address that in a follow-up review).

Also some nits:
phone field in Person should be renamed to plural as proto3 suggests ("person.Phone.Add(phoneNumber);" looks weird)

Perhaps we could rename RepeatedField to something else in the future.

**Comment by jtattermusch** [comment]
Merging this with @anandolee 's consent.

**Pull request merged**
