### PR TITLE
cmake: protobuf_generate fix GENERATE_EXTENSIONS, fix DEPENDS, add PROTOC_OUT_DIR

### PR DESCRIPTION
**Pull request by ccvca**
I made two changes to cmake protobuf_generate
 * The parameter GENERATE_EXTENSIONS has been ignored, because the variable was named protobuf_GENERATE_EXTENSIONS instead of protobuf_generate_GENERATE_EXTENSIONS
 * Add the parameter PROTOC_OUT_DIR to specify an alternative output directory for the generated files. If this parameter is not set, all generated files will be placed in ${CMAKE_CURRENT_BINARY_DIR} as before.

Example:
```
find_package(protobuf REQUIRED CONFIG)

add_library(FooBarTarget Foo.proto)
protobuf_generate(TARGET FooBarTarget PROTOC_OUT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src-gen)
```

### CODE REVIEW

**Comment by ccvca** [comment]
I signed it!

**Comment by ccvca** [comment]
411018e : DEPEND used the wrong variable ABS_FIL which is not set. Now the command is triggered every time a .proto file is changed

**Comment by ccvca** [comment]
The Appveyor-Error has been fixed by 291d9a0ab0b452537d22a81b551eaea53fd157a8

**Comment by xfxyjwf** [comment]
Rerunning the appveyor tests.

**Pull request merged**
