### PR TITLE
Use bool deterministic to suppress warning

### LINKED ISSUE #3059: Unused parameter 'deterministic'
See issue #2032
Fix in #2072 

This was fixed in 3.2 but is back in 3.3.

This commit reintroduced it:
d36c0c538a545fac5d9db6ba65c525246d4efa95

### PR DESCRIPTION
**Pull request by scpeters**
Fixes #3059 by re-applying 08b1c718 from #2087.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by scpeters** [comment]
I signed it!

**Comment by xfxyjwf** [comment]
ok to test

**Comment by scpeters** [comment]
sorry to pester, looking forward to 3.3.2 release with this fix, but I understand if you are busy

**Comment by xfxyjwf** [comment]
@scpeters Sorry about that, but there isn't a plan to make a 3.3.2 release at the moment. The next release is planned to be 3.4.0.

**Comment by scpeters** [comment]
That's fine, as long as this gets included in 3.4.0. Should I also make a separate pull request to master or is there a regular forward-merging process that will take care of it?

**Comment by xfxyjwf** [comment]
We will merge everything from 3.3.x branch back to master before we create the 3.4.x branch on top of master, so you don't need to do anything.

**Pull request merged**
