### PR TITLE
Make the use of Unsafe conditional

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref #3781

This is an attempt to workaround the Unsafe warning on JDK 9+.

### CODE REVIEW

**Comment by eed3si9n** [comment]
I signed it!

**Comment by xfxyjwf** [comment]
@eed3si9n Thanks for the patch, but I don't think we can just disable unsafe like this as we have code paths relying on the use of unsafe. I'm working on integrating our internal Java changes to github right now and we should fix the Java 9 issue after all the changes are integrated.

**Comment by xfxyjwf** [comment]
I'm closing this PR for now.

**Comment by eed3si9n** [comment]
@xfxyjwf Could you update the status on #3781 please?
What's the expected schedule for the integration?

**Pull request closed without merging**
