### PR TITLE
add module that enables implementing protoc plugins in Java

### PR DESCRIPTION
**Pull request by jhump**
Resurrecting the work of @tbroyer from https://codereview.appspot.com/912042

The changes in that patch to `plugin.proto`, to add a java package and class name, have already been merged.

This branch adds a new maven artifact that includes the proto file, the generated Java form of it, and Thomas's basic helper classes for implementing a plugin in Java. Description (more-or-less) from his original code review:

----

In C++, writing a code generator plugin is as easy as implementing `CodeGenerator` and passing an instance to `google::protobuf::compiler::PluginMain`; it shouldn't be any harder in Java (or Python BTW).

This patch adds a `JavaHelpers` class which is just a port of `google/protobuf/compiler/java/java_helpers.{h,cc}` with a few additional helper methods; and the helper `Plugin` class.

To implement a protoc plugin in Java, simply write an implementation of `CodeGenerator`, then create a `main()` method like:

```java
  public static void main(String[] args) {
    Plugin.run(new MyCodeGenerator(args));
  }
```

The main difference with C++ is that the Java code needs to be launched from a shell/batch script. Though, on unix platforms, the JAR can be converted into an executable via the technique described here (where the JAR and the script are merged):
http://en.newinstance.it/2012/04/17/self-executing-jar-files/

### CODE REVIEW

**Comment by jhump** [comment]
cc: @cconroy @JasonRosenberg @dragonsinth

**Comment by dragonsinth** [comment]
+1 Please!  This was super critical to writing a decent plugin in Java.

**Comment by jhump** [comment]
Ping. Can someone at least drop a comment on this?
(@xfxyjwf @pherl ?)

**Comment by xfxyjwf** [comment]
Although I think this is useful for those who want to write protoc plugins in Java, I am not sure putting it into protobuf repo is the right choice. I'm concerned that we protobuf-team will not have the resource to make this Java implementation in sync with the C++ implementation and putting it in protobuf repo might just hinder its development.

Have you considered making it a separate github project?

**Comment by jhump** [comment]
I have! One downside to being in a different repo is keeping in sync with `plugin.proto`. Basically, we have to fork that file since there isn't any other clean way to share it between this repo and a Java project outside of the repo.

So, what do you think of dropping the other bits of runtime in here (and I can put that in a separate repo) and just have the generated code here? In that case, it should be no burden on protobuf-team since it would only contain generated code.

If that idea is more agreeable, I have a follow-up question: could we include `plugin.proto` and the resulting generated Java code in the main `protobuf-java` artifact? Or would you prefer we keep it separate and published as a separate maven artifact?

**Comment by pherl** [comment]
Having plugin.proto and its generated code in java artifact sounds good to
me. Would you like to have a PR for the change?

**Comment by jhump** [comment]
I can define this module in a separate repo and artifact, separate from the protobuf repo, if it can easily get at the definitions in `plugin.proto`. See #950 for another approach.

**Pull request closed without merging**
