### PR TITLE
Cherry-pick 99564c3347223b92e49bd40f37b8c0d6fc6a3971 from master to 3.1.x

### PR DESCRIPTION
**Pull request by TeBoring**
In php, class name cannot be "Empty". Modified code generator to (#2375) generate GPBEmpty instead (for google.protobuf.Empty only). Also change runtime code to work with the new generated code accordingly.

### CODE REVIEW

**Comment by TeBoring** [comment]
@xfxyjwf

**Comment by xfxyjwf** [comment]
Why cherry-pick it into 3.1.x? Are you planning to release a 3.1.2 or something?

**Comment by TeBoring** [comment]
Yes, @michaelbausor has a project blocked by this bug to be released.

**Comment by xfxyjwf** [comment]
How far are we from a 3.2.0 release? If the php API is stable, we should start a 3.2.0 release.

**Comment by TeBoring** [comment]
3.2.0 will be mid Dec. However,  @michaelbausor has a tight timeline and cannot wait until then.

**Comment by xfxyjwf** [comment]
LGTM

**Pull request merged**
