### PR TITLE
Store the class object itself

### PR DESCRIPTION
**Pull request by jhaber**
Fix for #3474. This updates the `SerializedForm` to include the `Class` object rather than just the class name as suggested here https://github.com/google/protobuf/issues/3474#issuecomment-401096085 This shifts the burden of finding the right classloader from us to the JVM (which will hopefully handle it better). Based on my understanding of the Java serialization format, this change should be both forwards and backwards compatible

### CODE REVIEW

**Comment by jhaber** [comment]
hmm I was hopeful that creating a new personal fork would fix the CLA issues, guess not 😕

**Comment by xfxyjwf** [comment]
@jhaber I think it's just that the email used in the commit needs to be associated with the github account sending the pull request. Can you update the commit and send it as another pull request (the CLA bot will no longer respond to this pull request)?

**Comment by xfxyjwf** [comment]
Closing for now. Feel free to resend the PR after addressing the CLA issue.

**Comment by jhaber** [comment]
Sorry for the delay, I just got back from vacation. I just added my work email to my github account and will try sending the PR again

**Pull request closed without merging**
