### PR TITLE
 io_win32: support non-ASCII paths

### PR DESCRIPTION
**Pull request by laszlocsomor**
Fixes https://github.com/google/protobuf/issues/3951

### CODE REVIEW

**Comment by pherl** [comment]
Could you check the presubmit in appveyor? io_win32 related tests seem to be failing. https://ci.appveyor.com/project/protobuf/protobuf/build/1.0.5218/job/ckqiny85mwa3o8mr

**Comment by laszlocsomor** [comment]
Ah, the problem is that I removed the CMake-specific temp dir creating logic. Let me fix that.

**Comment by pherl** [comment]
Could you please rebase this against 3.5.x branch where we need to roll out a fix? Also could also test if this can compile without -std=c++11? (sorry we currently don't have test to cover non-c++11 tests for windows).

**Comment by laszlocsomor** [comment]
> Could you please rebase this against 3.5.x branch where we need to roll out a fix?

Yes, but if I do so, how will this PR be upstreamed?

> Also could also test if this can compile without -std=c++11? (sorry we currently don't have test to cover non-c++11 tests for windows).

I will do that tomorrow.

**Comment by pherl** [comment]
We will merge 3.5.x to master then.

**Comment by laszlocsomor** [comment]
> > > Could you please rebase this against 3.5.x branch where we need to roll out a fix?
> >
> > Yes, but if I do so, how will this PR be upstreamed?
>
> We will merge 3.5.x to master then.

Done.

> > Also could also test if this can compile without -std=c++11? (sorry we currently don't have test to cover non-c++11 tests for windows).
>
> I will do that tomorrow.

Did you mean using Bazel or CMake? On Windows or Linux?

**Comment by pherl** [comment]
could you create another PR and select target branch to 3.5.x? (github doesn't seem to allow changing target branch on existing PR)

**Comment by laszlocsomor** [comment]
@pherl : done, see https://github.com/google/protobuf/pull/4013 .

**Pull request closed without merging**
