### PR TITLE
Disable thread local storage for OSX < 10.7

### PR DESCRIPTION
**Pull request by gjasny**

### CODE REVIEW

**Comment by gjasny** [comment]
I signed it!

**Comment by thomasvl** [comment]
@BSBandme this appears to be for the C++ side of things, which I don't really look at.

**Comment by anandolee** [comment]
Are you able to provide a link which documented that __thread keyword requires at least 10.7?

**Comment by gjasny** [comment]
```
$ cat foo.cpp 
__thread int i = 0;

$ clang++ -mmacosx-version-min=10.6 -c foo.cpp
foo.cpp:1:1: error: thread-local storage is not supported for the current target
__thread int i = 0;
^
1 error generated.

$ clang++ -mmacosx-version-min=10.7 -c foo.cpp
$ 
```

**Comment by acozzette** [comment]
@gjasny Thanks for the pull request!

**Pull request merged**
