### PR TITLE
Removes redundant null pointer checks checks

### LINKED ISSUE #242: Remove unnecessary null pointer checks
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [GzipOutputStream](https://github.com/google/protobuf/blob/ed3c8a11f98995c6bf210566ea10659cb3f3abff/src/google/protobuf/io/gzip_stream.cc#L242 "destructor for GzipOutputStream")
* [Open](https://github.com/google/protobuf/blob/ed3c8a11f98995c6bf210566ea10659cb3f3abff/src/google/protobuf/compiler/cpp/cpp_bootstrap_unittest.cc#L108 "Open function")

### PR DESCRIPTION
**Pull request by ejsd1989**
closes #242 

Removed redundant checks for NULL, when it will already be handled by calling 'delete'

### CODE REVIEW

**Comment by haberman** [comment]
This change looks good but you need to sign the CLA before we can accept it. Please let me know if you want to move forward with this. Otherwise I'll have to close the PR. Thanks, Josh

**Comment by ejsd1989** [comment]
Thanks for the reminder, I just updated my CLA.
ᐧ

**Comment by haberman** [comment]
Thanks for contributing!

**Comment by elfring** [comment]
Thanks for your small source code improvement.

**Pull request merged**
