### PR TITLE
Use nullable for optional fields in generated Objective-C code

### PR DESCRIPTION
**Pull request by BenchR267**
Solution for https://github.com/google/protobuf/issues/1430

### CODE REVIEW

**Comment by thomasvl** [comment]
Commented on the issue, the fields shouldn't be coming back nil, if they are, I'd be curious how you got that to happen.

**Comment by BenchR267** [comment]
Yeah, you are right, they should not come back nil, but if not set they are nil, aren't they? If not: even better, that we just have to remove the nullability-flag completely because then they are just not nullable :)
With the current implementation it is possible to set nil (in an request-message-object e.g.) which could break something I guess.

**Comment by thomasvl** [comment]
They never return nil, even if unset.  When unset you get the default value for the field (empty string/data if nothing set for those fields, a message with nothing set for message).  Marking them null_resettable means, they will never return null, but you can set them to null (to "reset" them to their default).  http://nshipster.com/swift-1.2/ is a pretty good writeup of what the tags mean.

This actually allows some pretty powerful usage:

```objective_c
FooMessage *msg = [FooMessage message];
msg.subMessage.stringField = @"something";
```

So even if subMessage wasn't set, by returning a empty message, you can go ahead and assign the value.

This is especially useful in code where you want to build up the message though a few calls and might not know what was already added:

```objective_c
- (void)configureFoo:(FooMessage *)msg {
  msg.subMessage.string= @"something";
  // Otherwise you'd have to do:
  // if (!msg.hasSubMessage) {
  //   msg.subMessage =  [SubMessage message];
  // }
  // msg.subMessage.string= @"something";
}
```

So one line vs. four.  And the deep the object tree, the more useful.

Same goes for the map and repeated (array) fields.

For the strings, protos defines the unset value as an empty string.  While nil is pretty useful in ObjC, returning the empty string there also allows you to blindly set values into things like UI classes that don't always line nil for their properties.

**Comment by BenchR267** [comment]
Yes, you are completely right and it's awesome that these values can't be nil but instead be their initialized empty value. But in this case it would be much better to not define the nullability anyway since they are not optional from the iOS client's view.
Around the class definition are 'NS_ASSUME_NONNULL' calls, so removing the null_resettable would make them just non optionals in Swift which would fit the meaning much more.

**Comment by thomasvl** [comment]
Lost me on that last part, if they aren't tagged `null_resettable` and only wrapped in `NS_ASSUME_NONNULL`, the compiler will error (atleast for ObjC) if you try to assign `nil` to them.

**Comment by BenchR267** [comment]
Yes, but if they are never nil you should not be able to reset them by assigning nil. In that case you should either set an empty value (like "" for strings) or call an reset method on that message/property.

**Comment by thomasvl** [comment]
I guess that last part is up for some debate. Apple has system classes that have the same behavior and they added the annotation to support it.

For proto2 syntax files, the default can be marked on a per field bases, so it isn't always the empty string; so `= @""` isn't always a "clear".

From the code we've seen in the past, the current api seems to strike a reasonable balance, there is api to clear the field, but for the iOS/OS X developers that also expect to be able to assign nil to "clear" something, that is also supported (and matches Apple's behaviors their classes with similar behaviors).

**Comment by BenchR267** [comment]
Yes, I would expect clearing something when setting nil. But I would also expect that it returns nil after it was set to nil, not a default value.
If it always return a default value I would expect to not be able to set it to nil.

Do you have a specific example for Apple classes with that behaviour?

**Comment by thomasvl** [comment]
The nshipster article linked above mentions UIKit's tintColor as an example.  You should be able to grep the system headers to find others.

**Comment by BenchR267** [comment]
Hm, I took a look on the systems header files that contains null_resettable. There are more that I original thought and some of them just don't make sense to me. 
```@property(null_resettable, nonatomic,strong) UIFont      *font;            // default is nil (system font 17 plain)
@property(null_resettable, nonatomic,strong) UIColor     *textColor;       // default is nil (text draws black)```

But I definitely get your point. It makes sense that my proposed changes doesn't make sense because with that, every property would be an optional which would lead to much unwrapping / casting. 
But in my opinion null_resettable just not fits the need, this is just a placeholder for injected dependencies or if it is not 100% clear in every case that this is not nil. Or, the most used case (like the examples above from UILabel) configuration properties that wraps internal configuration properties.

My modified proposal is to define these properties as nonnull, because that's what they are. They are never nil. For resetting the caller should set them to a reasonable value or call a method like reset.

**Comment by BenchR267** [comment]
Hm, are there some more opinions on this topic? If not, I would close this pull request since it is not going to be merged I guess.

**Comment by thomasvl** [comment]
I'm not completely sure I get your comment about place holder dependencies.  From talking to a co-worker, I'm thinking you might be comparing it to something like xibs outlets in Swift?  Where when the object gets initial created the values aren't know and they get wired/set after the fact.  While that happens to use null_resettable/implicitly unwrapped, I don't see that as the only use of null_resettable.

Not too surprising here 😃, but I feel like the current design is trying to strike the right balance for the ObjC developer.  protobufs never really have "no value", instead they have a default or explicitly set value.  While an api to _clear_ or _reset to default_ makes sense (and we have it), using null_resettable is trying to balance that proto behavior with the fact that an ObjC developer will (and does) try setting the property nil to drop a previously set explicit value.

If you want to keep this open a while to see if anyone else comments, that's fine.  Once there is a protobuf release where ObjC support isn't labeled _Beta_ (i.e. _final_/_gm_), we're going to be locked into the api, so this won't really be something we can revisit as changing it could break developer code using the current definition/behavior.

**Comment by BenchR267** [comment]
Yeah, kind of. IBOutlets are created as Implicitly Unwrapped Optionals by default, but they can be nil (e.g. in the initializer of the view controller).
In Swift using these kind of type is an anti pattern. It definitely makes sense with your explanation since the values are never nil but should be resettable with nil. In Objective-C this is the behavior you might expect, in Swift not. And the null_resettable flag is in my opinion just for Swift compatibility, since an Objective-C developer might not take a look on the nullability flags (at least I do not, since they are just like an API comment and does not force the nullability like in Swift).
I would like to keep this open to hear more opinions on this. I think we both have some points in this and I just want to see how others think about this topic :)

**Pull request closed without merging**
