### PR TITLE
Make descriptor.proto compatible with stricter rules for comments in C

### PR DESCRIPTION
**Pull request by devurandom**

### CODE REVIEW

**Comment by devurandom** [comment]
@googlebot: The contribution is too small to fall under copyright or patent rules.

**Comment by edmonds** [comment]
I don't think this commit is right. The block comment delimiters are supposed to appear in output, e.g. https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/DescriptorProtos.SourceCodeInfo.LocationOrBuilder#hasLeadingComments().

**Comment by devurandom** [comment]
Hm, protobuf-c copies these // comments straight into its output, which then upsets the C compiler ("/* within comment"). Do you see any way to circumvent that?

**Comment by edmonds** [comment]
Yes. This is a bug in protobuf-c 1.1.0 which was fixed in 1.1.1, which I released about an hour ago :-)

**Pull request closed without merging**
