### PR TITLE
Google.Protobuf should target net45 (and not net451)

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes https://github.com/google/protobuf/issues/3595.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by pherl** [comment]
Can you change the test csproj as well?

**Comment by jskeet** [comment]
I wouldn't expect it to be feasible to change the test project - IIRC, the test runner needs 451.

**Comment by jskeet** [comment]
LGTM once everything is green.

**Comment by jskeet** [comment]
@jtattermusch Ready to merge? (The only Travis failures are non-C#)

**Pull request merged**
