### PR TITLE
Fix cpp benchmark dependency on mac

### LINKED ISSUE #4864: Macos C++ test is failing on cpp-benchmark
See: https://source.cloud.google.com/results/invocations/9287e8f1-ccc5-40f1-82ce-92abd791d6d8/targets/protobuf%2Fgithub%2Fmaster%2Fmacos%2Fcpp%2Fpresubmit/log

```

++ cd benchmarks
++ make cpp-benchmark
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I../src -I./cpp -I../third_party/benchmark/include    -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fPIC -MT cpp/benchmark-cpp_benchmark.o -MD -MP -MF cpp/.deps/benchmark-cpp_benchmark.Tpo -c -o cpp/benchmark-cpp_benchmark.o `test -f 'cpp/cpp_benchmark.cc' || echo './'`cpp/cpp_benchmark.cc
In file included from cpp/cpp_benchmark.cc:33:
../third_party/benchmark/include/benchmark/benchmark_api.h:19:5: warning: the benchmark_api.h header has been deprecated and will be removed, please include benchmark.h instead [-W#warnings]
#   warning the benchmark_api.h header has been deprecated and will be removed, please include benchmark.h instead
    ^
cpp/cpp_benchmark.cc:34:10: fatal error: 'benchmarks.pb.h' file not found
#include "benchmarks.pb.h"
         ^~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make: *** [cpp/benchmark-cpp_benchmark.o] Error 1
```

### PR DESCRIPTION
**Pull request by BSBandme**
Fix #4864

### CODE REVIEW

**Comment by xfxyjwf** [comment]
I'm not sure whether it's a kokor issue or our build config issue. It looks like the C++ distcheck is still failing but for a different cause:
https://source.cloud.google.com/results/invocations/b099aa02-6a23-481e-835e-cedb4be84de8/targets/protobuf%2Fgithub%2Fmaster%2Fmacos%2Fcpp_distcheck%2Fpresubmit/log

```
++ make dist
/Applications/Xcode_9.1.app/Contents/Developer/usr/bin/make  dist-gzip am__post_remove_distdir='@:'
/Applications/Xcode_9.1.app/Contents/Developer/usr/bin/make  distdir-am
if test -d "protobuf-3.6.0"; then find "protobuf-3.6.0" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "protobuf-3.6.0" || { sleep 5 && rm -rf "protobuf-3.6.0"; }; else :; fi
test -d "protobuf-3.6.0" || mkdir "protobuf-3.6.0"
 (cd src && /Applications/Xcode_9.1.app/Contents/Developer/usr/bin/make  top_distdir=../protobuf-3.6.0 distdir=../protobuf-3.6.0/src \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
/Applications/Xcode_9.1.app/Contents/Developer/usr/bin/make  distdir-am
 (cd conformance && /Applications/Xcode_9.1.app/Contents/Developer/usr/bin/make  top_distdir=../protobuf-3.6.0 distdir=../protobuf-3.6.0/conformance \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: *** No rule to make target `../src/protoc', needed by `protoc_middleman'.  Stop.
make[2]: *** [distdir-am] Error 1
make[1]: *** [distdir] Error 2
make: *** [dist] Error 2
```

**Comment by BSBandme** [comment]
I tried to cat conformance/Makefile.in on kokoro, found that the distdir generated in Makefile.in depends on `BUILT_SOURCES`, but locally it doesn't (KOKORO log can be found [here](https://source.cloud.google.com/results/invocations/a78c8da4-49b3-43bb-a429-6e91f451f3fe/targets/protobuf%2Fgithub%2Fmaster%2Fmacos%2Fcpp_distcheck%2Fpresubmit/log))

I tried to solve this by setting `NODIST_BUILT_SOURCES` and `NODIST_BUILT` but no one works. I'm not sure how to solve this, and I think distdir depend on `BUILT_SOURCES` doesn't make sense. I'll try to figure out how to make configure to not let distdir depend on `BUILT_SOURCES`

**Comment by xfxyjwf** [comment]
3 MacOS tests are still failing with similar errors:
https://source.cloud.google.com/results/invocations/bd13dc80-fe3e-48a5-a701-addd20290315/targets/protobuf%2Fgithub%2Fmaster%2Fmacos%2Fcpp%2Fpresubmit/log
https://source.cloud.google.com/results/invocations/faf2d3e6-0c81-4cd5-a862-2ea214df227c/targets/protobuf%2Fgithub%2Fmaster%2Fmacos%2Fcpp_distcheck%2Fpresubmit/log
https://source.cloud.google.com/results/invocations/c845d29b-fd54-480c-adaa-a42968ceff7b/targets/protobuf%2Fgithub%2Fmaster%2Fmacos%2Fjavascript%2Fpresubmit/log

Have you been able to reproduce the issue locally?

**Comment by BSBandme** [comment]
No, can't repro using latest version automake. 

And I Just found this https://lists.nongnu.org/archive/html/automake/2017-11/msg00050.html
I guess kokoro just upgrade automake to some specific version but not the lastest.

**Comment by BSBandme** [comment]
For js the bug is some kind of different, 
Js build failed on `npm test` which is inside `cd js && npm install && npm test && cd ..` .
So it didn't `cd ..` and so it can't `cd conformance` in next line.
For `npm test` it failed on 
`[libprotobuf FATAL google/protobuf/compiler/js/js_generator.cc:1684] CHECK failed: namespaceObject.compare(0, 6, "proto."):` 
I need to investigate why this failed

**Comment by BSBandme** [comment]
Sorry that it seems that my previous local tests didn't using the latest version of automake. Using the lastest automake can repro the bug.

I think we can just delete the `BUILT_SOURCES` for conformance tests since all the targets has declared dependency of `BUILT_SOURCES.` And I tested locally it seems that it works for both old version and new version of automake.

**Comment by xfxyjwf** [comment]
@BSBandme can you create an issue for the Javascript failure?

**Pull request merged**
