### PR TITLE
Remove useless file that doesn't load

### PR DESCRIPTION
**Pull request by tamird**
This file was broken in ada6556.

@haberman this accounts for the problems I was seeing in #165.

### CODE REVIEW

**Comment by haberman** [comment]
Oh, yes it looks like that is a remnant of the (now-deleted) v1 of the C++ extension!

This should definitely be deleted. But I can't merge yet because it looks like this change breaks the build. Looks like this filename needs to be removed from one more place first:
https://github.com/google/protobuf/blob/master/Makefile.am#L205

**Comment by tamird** [comment]
@haberman thanks! Should be good now

**Comment by tamird** [comment]
@haberman green :)

**Comment by haberman** [comment]
Thanks!

**Pull request merged**
