### PR TITLE
Fix generation of extending nested messages in JavaScript

### LINKED ISSUE #2438: JavaScript Extension of Nested Messages Bug
The ordering of extensions that use nested messages and the nested messages themselves appears to be broken on `3.1.0` (and also latest `master` as of writing: `4280c27`).

Test proto:
```syntax = "proto2";

message ToBeExtended {
  extensions 1 to max;
}

message MyOuterMessage {
  message MyExtension {}
  extend ToBeExtended {
    optional MyExtension my_extension = 1;
  }
}
```

Generating the JavaScript and running it through node using:
`protoc --js_out=import_style=commonjs:./ my_outer_message.proto && node my_outer_message_pb.js`

Throws:
```
TypeError: Cannot read property 'toObject' of undefined
proto.MyOuterMessage.MyExtension.toObject
my_outer_message_pb.js:291
```

This is because `proto.MyOuterMessage.MyExtension` is only defined on line `341` in the generated file.

### PR DESCRIPTION
**Pull request by MarcusImprobable**
Fixes #2438

Moving of the nested `GenerateClass` and `GenerateEnum` messages before `GenerateClassRegistration` ensures that extensions defined in the outer message that use the nested messages work correctly now. Previously the extension definition proceeded the message definition, causing an exception.

### CODE REVIEW

**Comment by marcusimprobable** [comment]
I signed it!

**Comment by haberman** [comment]
Thanks for the fix. Could you include a test to verify the fix and prevent regressions?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by cuongtv51** [comment]
Hi all, pls Admins verify this path.

**Comment by acozzette** [comment]
ok to test (this should make the bots run the CI tests)

**Comment by acozzette** [comment]
@haberman It looks like the test you requested has been added and so this PR might be ready for another look.

**Comment by haberman** [comment]
Thanks for the fix!

**Pull request merged**
