### PR TITLE
Use require_relative instead of require in Ruby code

### LINKED ISSUE #1137: protoc requires files as if they were gems
One of my proto files contains this line: `import "api.proto";`
This gets compiled to Ruby like this: `require 'api'`

This causes an error when requiring those files because it tries to load 'api' as a gem. It would be better for the compiler to generate `require_relative 'api'` instead.

### PR DESCRIPTION
**Pull request by kblanks**
Closes #1137

### CODE REVIEW

**Comment by kblanks** [comment]
That was easier than I expected :sunglasses:

**Comment by haberman** [comment]
What if someone wants to put generated code into a gem, or install it into a system location? It seems that require_relative *only* looks in the current directory, and not in system locations?

Is there a way to make this work for both cases?

**Comment by kblanks** [comment]
Perhaps there could be a compiler option?

**Comment by kblanks** [comment]
@haberman I hate to bump a PR but this is still causing issues for me and others :wrench:

**Comment by haberman** [comment]
Sorry for the slow response on this. Yes a compiler option sounds like the way to go here. `require_relative` as the only option doesn't feel quite right -- my impression is that `require` is generally the "default" option for any Ruby library, and `require_relative` is what you do in special situations where you know something specific about how the file will be used.

**Comment by kblanks** [comment]
@haberman It may sound over the top but maybe a special option could be added into the "require' declaration to specify that it should be relative?

**Comment by haberman** [comment]
@kblanks I think it would make more sense to add it as an option to the code generator.

So in [src/google/protobuf/compiler/ruby/ruby_generator.h](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/ruby/ruby_generator.h) add a `GeneratorOptions` struct like JavaScript has in [src/google/protobuf/compiler/js/js_generator.h](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/js/js_generator.h#L53). Make it a `bool` that defaults to false, but if the user passes the `require_relative` option to the codegen it will put `require_relative` instead of `require` in the generated code.

**Comment by kblanks** [comment]
I'm going to close this since it's not going to work for what's needed. We can still discuss in #1137.

**Pull request closed without merging**
