### PR TITLE
Fix missing import of jspb.Map (#1885)

### PR DESCRIPTION
**Pull request by pherl**

### CODE REVIEW

**Comment by pherl** [comment]
Also cherry-picked the ruby change. PTAL

**Comment by haberman** [comment]
These cherry-picks LGTM.

**Comment by pherl** [comment]
Thanks, I will merge once Travis returns green.

**Comment by haberman** [comment]
This Travis failure is in Java, I don't think it is related.

**Comment by pherl** [comment]
@xfxyjwf Do you think the Java compatibility test failure indicates a breakage already in this branch?

**Comment by xfxyjwf** [comment]
It's a binary incompatible issue that's fixed in master but not in the GA branch. You can cherry-pick:
https://github.com/google/protobuf/commit/30647cae9f8d06af1fea643c4fd9c8d9f25a6048
to the GA branch to fix it.

**Comment by pherl** [comment]
Thanks. Cherry-picked. Will merge once checks are verified.

**Pull request merged**
