### PR TITLE
Remove the C#-specific field_presence_test.proto, using unittest_no_field_presence.proto instead.

### PR DESCRIPTION
**Pull request by jskeet**
This is the start of establishing a C# namespace of "Google.ProtocolBuffers.TestProtos.Proto3" for proto3-syntax protos.
We could optionally split the directory structure as well into Proto2 and Proto3 for clarity.

This addresses part of issue #374.

### CODE REVIEW

**Comment by jskeet** [comment]
@jtattermusch This somewhat undoes an earlier PR of yours
@anandolee This removes the "extra" proto you added, so we can use the common one instead

I don't *think* this will be controversial, but I could be wrong.
Any comments on the use of a ....Proto3 namespace for differentiation? I haven't currently got a Proto2 namespace, but we could do that separately if we wanted to.

**Comment by jtattermusch** [comment]
It doesn't look like it's undoing anything.

Can you also update the generate_protos.sh script so that it's up to date? After running it, all the code should remain the same with the exception of files that have been manually modified:
modified:   csharp/src/ProtocolBuffers.Test/TestProtos/Unittest.cs
modified:   csharp/src/ProtocolBuffers.Test/TestProtos/UnittestCustomOptions.cs
modified:   csharp/src/ProtocolBuffersLite.Test/TestProtos/Unittest.cs
modified:   csharp/src/ProtocolBuffersLite.Test/TestProtos/UnittestLite.cs

**Comment by jskeet** [comment]
It's undoing the earlier removal of UnittestNoFieldPresence.cs :)

And yes, I'll fix up the shell script - I meant to do that before.

**Comment by jskeet** [comment]
Have added the change to the shell script, but I can't easily test it here - could you pull and check that when you run the shell script, there aren't any further changes?

**Comment by jtattermusch** [comment]
Just ran generate_protos.sh and all seems good. LGTM.

**Comment by jtattermusch** [comment]
Jie, please merge once you're happy.

**Pull request merged**
