### PR TITLE
Integrate changes from upstream/master

### PR DESCRIPTION
**Pull request by jtattermusch**
Merge upstream/master. The changes seem orthogonal to C# efforts, so this shouldn't harm us at all.

Main reason to do this is to update appveyor.yml, which is broken in csharp-experimental, but works fine in master (appveyor gives us continous build of C++ under windows, so it's pretty useful to have this working).

### CODE REVIEW

**Comment by jtattermusch** [comment]
@jskeet FYI

**Comment by jskeet** [comment]
Are you going to merge this once it's finished checking, or are you after a review from me? I'll start looking at the other Travis issues...

**Comment by jtattermusch** [comment]
Hm, strange error. But at least appveyor has actually started the build and came up with some results.
I think we can merge this anyway and address the problems later.

**Comment by jtattermusch** [comment]
Please merge if you agree.

**Comment by jskeet** [comment]
I don't honestly know enough about Appveyor to have much idea - but I'll take your word for it that it makes things better.

I think the Travis failures are due to my wire_format.h change, and possibly the lack of regenerating the descriptor protos. Will fix the wire_format one now, rebase from this, and see whether the freeze PR gets better...

**Comment by jtattermusch** [comment]
Well, appveyor is like travis, but it runs the build on Windows. And it's probably good idea to have a way to check that the build of libprotoc and libprotobuf works alright on Windows  as C# cares about Windows support more than the other languages.

**Pull request merged**
