### PR TITLE
Modified FindRubyTestDir to use GOOGLE_THIRD_PARTY_PROTOBUF

### PR DESCRIPTION
**Pull request by AustinSchuh**

### CODE REVIEW

**Comment by xfxyjwf** [comment]
Is there a CL making the same change to our internal code base?

**Comment by AustinSchuh** [comment]
I don't have access to your internal code base to check.

I am building the protobuf library using Bazel, and it lives in //third_party/protobuf/ in my repo. Looks like that is the same place that it lives internally due to the existence of the GOOGLE_THIRD_PARTY_PROTOBUF macro.  I have found that macro very handy in getting ruby tests to run.

**Comment by xfxyjwf** [comment]
@TeBoring , could you take a look at this PR? Did you need the same change in order to port alpha-3 to our internal code base?

**Comment by TeBoring** [comment]
We don't use it internally. Internally, -Ithird_party/protobuf/src is add to copt.

**Pull request merged**
