### PR TITLE
fix index out of range error in C# generation using msvc

### PR DESCRIPTION
**Pull request by warrenfalk**

### CODE REVIEW

**Comment by warrenfalk** [comment]
I signed it!

**Comment by jskeet** [comment]
Assigned to @jtattermusch as I'm not sure why we're looking for a `#` at the end anyway.

**Comment by jtattermusch** [comment]
Thanks for the pull request! Can you please provide a more informative description of the pull request (or link to an existing issue)?

**Comment by jtattermusch** [comment]
The helper functions was borrowed from Java codegen (and I never got to refactor it properly):
https://github.com/google/protobuf/blob/24fe6ba750bf8a247d41fc589460dce1bdd697a1/src/google/protobuf/compiler/java/java_helpers.cc#L104

so probably the same thing should be fixed there. 

@anandolee , you seem to be the author of the original code for in java_helpers, can you please help reviewing?

**Comment by anandolee** [comment]
LGTM

**Pull request merged**
