### PR TITLE
Removed a stray return statement, causing compilation error.

### PR DESCRIPTION
**Pull request by keveman**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by xfxyjwf** [comment]
ok to test

**Comment by keveman** [comment]
Gentle ping.

**Comment by girving** [comment]
Is it too late to merge this in time for @dandelionmane noon push?

**Comment by xfxyjwf** [comment]
Sorry, I was waiting for the test result and didn't notice the updates here...

**Pull request merged**
