### PR TITLE
Update version numbers for beta3

### PR DESCRIPTION
**Pull request by pherl**

### CODE REVIEW

**Comment by xfxyjwf** [comment]
This PR only updates C++/Java/Python. Do it for other languages as well?

**Comment by pherl** [comment]
@jskeet @haberman for the version number bump for beta-3/alpha-6. Let me know if there are other languages missing..

**Comment by xfxyjwf** [comment]
LGTM

**Comment by jskeet** [comment]
Please update the last line of https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/Properties/AssemblyInfo.cs (which we missed last time...). Other than that, it looks fine for C#.

**Comment by pherl** [comment]
Done. Thanks.

**Pull request merged**
