### PR TITLE
Updated CHANGES.txt to mention Ruby extension.

### PR DESCRIPTION
**Pull request by cfallin**

### CODE REVIEW

**Comment by cfallin** [comment]
@pherl to review.

**Comment by pherl** [comment]
LGTM

**Comment by cfallin** [comment]
Added a minor update to `ruby/README.md` as well (removed obsolete reference to git submodule, now that we're bundling directly) -- PTAL.

**Comment by pherl** [comment]
LGTM

**Comment by cfallin** [comment]
Thanks, merging.

**Pull request merged**
