### PR TITLE
Remove ClsCompliant declarations from C# code (fix #318)

### LINKED ISSUE #318: Remove ClsCompliant declarations from C# code
Currently we generate:

```csharp
[ClsCompliant(false)]
```

on properties/methods which use non-CLS-compliant types. It turns out no-one really uses CLS compliance as far as I can tell, so this is just cruft which can add unhelpful warnings. It would be good to have this removed from the C# codegen.

### PR DESCRIPTION
**Pull request by anandolee**

### CODE REVIEW

**Comment by anandolee** [comment]
#318

**Comment by anandolee** [comment]
@jskeet @jtattermusch Please help to review

**Comment by jtattermusch** [comment]
LGTM, but please squash the two commits into one, to maintain a more readable history.

git rebase -i upstream/csharp and then git push -f  ....

**Comment by jskeet** [comment]
Changes themselves LGTM (with a squash as Jan suggests) - I don't know the C++ codebase to know whether this is *all* that's required, but I trust you both on that :)

**Pull request merged**
