### PR TITLE
Support POWER Linux

### PR DESCRIPTION
**Pull request by dougkwan**
This patch adds support for POWER Linux.  Protobuf already support POWER on AIX.  The atomicops are sharable between Linux and AIX so I also rename header file to atomicops_internals_power.h.

### CODE REVIEW

**Comment by dougkwan** [comment]
I actually for work for Google. This patch is work related and has been approved to be released.  Do I still need to sign a CLA? :-)

**Comment by xfxyjwf** [comment]
@dougkwan could you contact our internal CLA team regarding this? From my understanding the CLA bot should already have all Googlers white-listed. A probable cause: you are using your personal email for the github account and this account hasn't been registered to the Google organization.

**Comment by dougkwan** [comment]
I have changed my github account to use my google.com e-mail as my primary e-mail.  Let me close this pull request and create another to see if commit will be associated my work e-mail.

**Comment by dougkwan** [comment]
close pull request because it is not associated with my work e-mail.

**Pull request closed without merging**
