### PR TITLE
Delete "SEBS" (aka: Clean up Kenton's old trash)

### PR DESCRIPTION
**Pull request by kentonv**
The file `SEBS` is a build file for a toy build system I was writing in my spare time six years ago, back when I maintained protobufs. Arguably it was never appropriate for me to have placed this file in the protobuf tree, but it was convenient at the time and didn't seem to hurt anything. It clearly doesn't belong here now, though.

### CODE REVIEW

**Comment by kentonv** [comment]
(CLA signed, though it's probably moot for a delete-only change.)

**Comment by haberman** [comment]
Thanks Kenton!

**Comment by hzeller** [comment]
I like the irony of Kenton having to sign the CLA :)

**Comment by cbsmith** [comment]
That is pretty awesome.

On Fri, Mar 27, 2015 at 1:56 PM, Henner Zeller <notifications@github.com>
wrote:

> I like the irony of Kenton having to sign the CLA :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/protobuf/pull/257#issuecomment-87089806>.
>



-- 
Chris

**Comment by edmonds** [comment]
@kentonv Hey, the fix for the "goto fail" bug was also a delete-only change ;-)

**Pull request merged**
