### PR TITLE
fix compile error on centos in metadata.h for constructors.

### PR DESCRIPTION
**Pull request by michaelpengcn**
I have already tested the compile process on centos. CLA fixed.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by TeBoring** [comment]
LGTM

**Comment by deejross** [comment]
Has this made it into 3.2.1? I just tried that one after trying 3.2.0 and I'm still seeing this issue.

**Comment by jjpepper** [comment]
+1.  I'm having the same issue with RHEL r6.8 (Satniago) and Protobuf 3.3.  @deejross do you have a workaround?

**Comment by jjpepper** [comment]
@deejross, I have a workaround.  In metadata_lite.h:169:

replace:
explicit InternalMetadataWithArenaLite(Arena* arena)
      : InternalMetadataWithArenaBase(arena) {}

with:
  explicit InternalMetadataWithArenaLite(Arena* arena)
      : InternalMetadataWithArenaBase<string,
                                           InternalMetadataWithArenaLite>(arena) {}

**Comment by MerleLK** [comment]
I use the @jjpepper  method and I hacve success, but I don't understand why this problem show on CentOS6.x？

**Pull request merged**
