### PR TITLE
Fixes deprecation warnings/errors on Xcode

### PR DESCRIPTION
**Pull request by sergiocampama**
Renamed the pnacl version of atomicops.h into generic_C11_atomic, and flagged the mac version so that if atomic is enabled, it uses the generic C11 one.

### CODE REVIEW

**Comment by sergiocampama** [comment]
Fixes https://github.com/google/protobuf/issues/2182

**Comment by xfxyjwf** [comment]
Thanks for the patch. Can you also update the references to the renamed pnacl.h file in src/Makefile.am?

**Comment by sergiocampama** [comment]
done

**Comment by xfxyjwf** [comment]
Thanks!

**Pull request merged**
