### PR TITLE
Objective C compiler plugin and runtime

### PR DESCRIPTION
**Pull request by thomasvl**
Alpha 1 drop of Google's Objective C support:

protoc plugin/generator.
Objective C Runtime Support.
Xcode project for testing runtime (and generator).

### CODE REVIEW

**Comment by thomasvl** [comment]
I signed it!

**Comment by TeBoring** [comment]
Could you squash these commits into a single one?

**Comment by thomasvl** [comment]
Oops, sorry, meant to do that.  Squashed.

**Comment by TeBoring** [comment]
github cannot show all changed files. So I just leave comment here.
1) src/Makefile.am#206: libprotoc_la_CPPFLAGS = -I$(top_srcdir)/objectivec
    Do we have to include this directory for protoc?
2) Is there anything need to be added to .gitignore?

**Comment by TeBoring** [comment]
@pherl Please take another look.

**Comment by thomasvl** [comment]
@TeBoring 

1 - That is needed so the objc plugin can pick up a header from the runtime (GPBBootstrap.h) to then write in a version stamp that is then checked when compiling the generated code.  Same sorta thing is done with the C++ code, but the plugin already has that on the include paths.  If there's a better way, I'm open to it, I don't know automake/configure/etc. well.

2 - No, since the Makefiles have to do the same things on all platforms, it doesn't build the OS X/iOS test in the objectivec directory which is about the only reason I can see to pick up more ignores.

**Comment by TeBoring** [comment]
@thomasvl 
1) In release, we have separate packages for different languages. Thus, objectivec/ directory is not available in all packages, and those package will fail to be built because of lack of GPBBootstrap.h
Instead of include that directory, how about defining that macro directly?
-DGOOGLE_PROTOBUF_OBJC_GEN_VERSION="400" We will keep both versions in sync.
2) After building the test directly, I found:
objectivec/.DS_Store
objectivec/ProtocolBuffers_iOS.xcodeproj/project.xcworkspace/xcshareddata/ProtocolBuffers_iOS.xccheckout
objectivec/ProtocolBuffers_iOS.xcodeproj/project.xcworkspace/xcuserdata/
objectivec/ProtocolBuffers_iOS.xcodeproj/xcuserdata/
Can they be ignored?

**Comment by thomasvl** [comment]
@TeBoring 

1. A #define means there are two places that always have to be updated, that seems bad.  How does one build those language specific release?  make distcheck seems pass, and includes them all, no?

2. Yes, those can be dropped.  Most git/OS X users have global ignores for those, but we can add them.  Want me to merge that into the branch?

**Comment by xiaofeng-gg** [comment]
On Mon, May 4, 2015 at 12:35 PM, Thomas Van Lenten <notifications@github.com
> wrote:

> @TeBoring <https://github.com/TeBoring>
>
>    1.
>
>    A #define means there are two places that always have to be updated,
>    that seems bad. How does one build those language specific release? make
>    distcheck seems pass, and includes them all, no?
>
> By default "make distcheck" includes all language packages but that's not
how we distribute release packages. To build the release package for a
specific language, you need to run ./configure with a DIST_LANG parameter.
For example, "./configure DIST_LANG=java". The release package (see: here
<https://github.com/google/protobuf/releases>, we have a separate download
package for each language) we provide for each language will only have:
runtime in that language + C++ runtime and protoc. For this reason protoc
should only depend on C++ runtime and not include anything from other
runtimes.

For the version macro, I think obj-c code generator can use the macro
defined in src/google/protobuf/stubs/common.h while the obj-c runtime uses
a separate macro defined in its own header files. This is what we are
already doing for all other languages right now. For example, Java has a
version number in its pom.xml file, and Python has a version number in its
setup.py. Every time when we update the version number we need to change
all of them together. Before we come out with a better solution, I thin
it's fine to use this approach in objective-c.

**Comment by TeBoring** [comment]
@thomasvl 
1. For java specific release, these files will be included in the package:
  * all protoc header and src
  * all java generator header and src
  * header of other language's generator needed to compile protoc
  * all runtime header and src of java

With these files, protoc, java generator and java generated code can be compiled.

2. Yes, thanks.

**Comment by thomasvl** [comment]
@xiaofeng-gg Thanks, that's the dist magic I was missing.  So clearly what I have won't work.  But I'm not seeing how src/google/protobuf/stubs/common.h helps.  All the CPP symbols it defines: GOOGLE_PROTOBUF_*VERSION are specific to the C++ implementation.  I don't see anything related for java/python would would get captured into the generated source to ensure thing match.  The setup.py/pom.xml seem to link together a version of the library to pull/build, but that doesn't seem to cover ensuring what is recorded into the generated files will work with the runtime?

**Comment by xiaofeng-gg** [comment]
On Mon, May 4, 2015 at 1:32 PM, Thomas Van Lenten <notifications@github.com>
wrote:

> @xiaofeng-gg <https://github.com/xiaofeng-gg> Thanks, that's the dist
> magic I was missing. So clearly what I have won't work. But I'm not seeing
> how src/google/protobuf/stubs/common.h helps. All the CPP symbols it
> defines: GOOGLE_PROTOBUF_*VERSION are specific to the C++ implementation. I
> don't see anything related for java/python would would get captured into
> the generated source to ensure thing match. The setup.py/pom.xml seem to
> link together a version of the library to pull/build, but that doesn't seem
> to cover ensuring what is recorded into the generated files will work with
> the runtime?
>
Right. Currently only C++ has a version mismatch check. For the macros
defined in common.h, only GOOGLE_PROTOBUF_VERSION is actually useful. For
each release we just updated all macros and to the same value. So basically
users will have to use the same version of protoc, runtime and headers. How
will the versioning in objective-c works? Will you allow the generated code
in a certain version to work with a range of different runtime versions?

**Comment by thomasvl** [comment]
On Mon, May 4, 2015 at 4:54 PM, xiaofeng-gg <notifications@github.com>
wrote:

> On Mon, May 4, 2015 at 1:32 PM, Thomas Van Lenten <
> notifications@github.com>
> wrote:
>
> > @xiaofeng-gg <https://github.com/xiaofeng-gg> Thanks, that's the dist
> > magic I was missing. So clearly what I have won't work. But I'm not
> seeing
> > how src/google/protobuf/stubs/common.h helps. All the CPP symbols it
> > defines: GOOGLE_PROTOBUF_*VERSION are specific to the C++
> implementation. I
> > don't see anything related for java/python would would get captured into
> > the generated source to ensure thing match. The setup.py/pom.xml seem to
> > link together a version of the library to pull/build, but that doesn't
> seem
> > to cover ensuring what is recorded into the generated files will work
> with
> > the runtime?
> >
> Right. Currently only C++ has a version mismatch check. For the macros
> defined in common.h, only GOOGLE_PROTOBUF_VERSION is actually useful. For
> each release we just updated all macros and to the same value. So basically
> users will have to use the same version of protoc, runtime and headers. How
> will the versioning in objective-c works? Will you allow the generated code
> in a certain version to work with a range of different runtime versions?
>
>
We're after the same thing C++ has.  The catch is say ObjC finds an issue
were we need to do ensure all sources are regenerated for that.  If we used
the same symbol/define as C++, then all C++ users would also have to
regenerate even if there is no change on the C++ side of things (and the
reverse).

The subs/common.h also is C++ so it couldn't be used directly in a
Objective C source as it won't parse.  Adding another header over in the
C++ directory side of things also seems odd, since the rest of the
Objective C shouldn't/doesn't depend on it.

**Comment by xiaofeng-gg** [comment]
On Mon, May 4, 2015 at 2:11 PM, Thomas Van Lenten <notifications@github.com>
wrote:

> On Mon, May 4, 2015 at 4:54 PM, xiaofeng-gg <notifications@github.com>
> wrote:
>
> > On Mon, May 4, 2015 at 1:32 PM, Thomas Van Lenten <
> > notifications@github.com>
> > wrote:
> >
> > > @xiaofeng-gg <https://github.com/xiaofeng-gg> Thanks, that's the dist
> > > magic I was missing. So clearly what I have won't work. But I'm not
> > seeing
> > > how src/google/protobuf/stubs/common.h helps. All the CPP symbols it
> > > defines: GOOGLE_PROTOBUF_*VERSION are specific to the C++
> > implementation. I
> > > don't see anything related for java/python would would get captured
> into
> > > the generated source to ensure thing match. The setup.py/pom.xml seem
> to
> > > link together a version of the library to pull/build, but that doesn't
> > seem
> > > to cover ensuring what is recorded into the generated files will work
> > with
> > > the runtime?
> > >
> > Right. Currently only C++ has a version mismatch check. For the macros
> > defined in common.h, only GOOGLE_PROTOBUF_VERSION is actually useful. For
> > each release we just updated all macros and to the same value. So
> basically
> > users will have to use the same version of protoc, runtime and headers.
> How
> > will the versioning in objective-c works? Will you allow the generated
> code
> > in a certain version to work with a range of different runtime versions?
> >
> >
> We're after the same thing C++ has. The catch is say ObjC finds an issue
> were we need to do ensure all sources are regenerated for that. If we used
> the same symbol/define as C++, then all C++ users would also have to
> regenerate even if there is no change on the C++ side of things (and the
> reverse).
>
Currently we use the same version number across all languages. For example,
if we have a 3.0.1 release, that means every language is of version 3.0.1.
If for some reason we need to make a small patch to one of the languages
and make a minor release, that will increases the version number of every
language even for those unchanged. It has to be this way because all
languages share the same protoc.

For the issue you mentioned, what we are thinking is to enforce a version
compatibility rule, that the generated code from protoc 3.0.x should be
able to work with any runtime version 3.0.y. So if we have a objective-c
only change which increases the version number from 3.0.1 to 3.0.2, C++
users could still compile their generated code from version 3.0.1 with the
new runtime 3.0.2 (which is actually not changed in this case except for
the version number). We didn't do this before because we only release a new
version like once a year. In the future we will release more frequently and
change the version number more frequently. Using the strict version match
approach as we did before will obviously cause problems to users. We don't
yet have any conclusion on how we do versioning though. Currently we only
have alpha releases where we change things rather freely. Versioning is not
a imminent concern.


>
> The subs/common.h also is C++ so it couldn't be used directly in a
> Objective C source as it won't parse. Adding another header over in the
> C++ directory side of things also seems odd, since the rest of the
> Objective C shouldn't/doesn't depend on it.

What I am suggesting is using stubs/common.h only in the code generators,
but not in the objective-c runtime. And having a separate macro definition
in objective-c headers. There will still be macro duplications but I do not
see a better approach though.

**Comment by thomasvl** [comment]
Update to add the .gitignore entries and break the link between the plugin and runtime sources (from a build POV).  The constants have to be kept in sync, and the Runtime tests include a script to confirm they are in sync.

**Comment by TeBoring** [comment]
check_version_stamps.sh not found

**Comment by thomasvl** [comment]
Missing script added.

**Comment by TeBoring** [comment]
The execution permission seems missing.

**Comment by thomasvl** [comment]
Bit should be fixed.

**Comment by TeBoring** [comment]
LGTM

**Pull request merged**
