### PR TITLE
Bump version number to 3.2.0

### PR DESCRIPTION
**Pull request by TeBoring**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by TeBoring** [comment]
@xfxyjwf

**Comment by TeBoring** [comment]
ok to test

**Comment by xfxyjwf** [comment]
ok to test

**Comment by xfxyjwf** [comment]
@TeBoring to trigger bazel tests, you need to make your Google membership publicly visible:
https://github.com/orgs/google/people?utf8=%E2%9C%93&query=teboring

**Pull request merged**
