### PR TITLE
Updated Version

### PR DESCRIPTION
**Pull request by Fleshgrinder**
Version is still at 3.3.0 instead of the actual 3.3.2.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by Fleshgrinder** [comment]
I signed it!

**Comment by xfxyjwf** [comment]
master branch is still 3.3.0 because 3.3.2 is tagged in the 3.3.x branch. We will update the version number when merging 3.3.x branch back to master.

**Comment by Fleshgrinder** [comment]
In other words master does not contain the latest code? Should I target 3.3.x with my upcoming PRs?

**Comment by xfxyjwf** [comment]
All protobuf releases will be done in the release branch (e.g., 3.3.x is the release branch for 3.3.0, 3.3.1, 3.3.1 etc), so yes there can be changes in the release branch but not yet in master. Most development should happen in the master branch though. A change should only be made in the release branch if there is a planned patch release to include that change.

**Pull request closed without merging**
