### PR TITLE
protoc: support '=' in --proto_path arguments

### LINKED ISSUE #877: Paths with '=' are unsupported
They seem to get caught up in the argument parsing. Debugging further still.

### PR DESCRIPTION
**Pull request by mathstuf**
---
Fixes #877.

### CODE REVIEW

**Comment by mathstuf** [comment]
I've asked about the CLA here. The company is Kitware if it has already been signed (which may be true; I think we've had Gerrit patches before).

**Comment by xfxyjwf** [comment]
Could you avoid using "=" in file paths instead (or avoid passing file paths with "=" to protoc)? It seems very weird to support such file paths. It would be very problematic if the "=" sign appears in proto file import path names as I am pretty we don't have special handling for such names. And I also believe this PR addresses one special case but not the general problem of using "=" in file paths. For example, how would you interpret such a proto_path:
```bash
$ protoc --proto_path=foo/bar=dir/with=sign xxx.proto
```

**Comment by xfxyjwf** [comment]
Regarding the CLA, I can find a corporate CLA signed for Kitware, but I can't find your email address in the authorized contributors from that CLA. Could you ask whoever signed the CLA representing Kitware to give us a updated list of authorized contributors?

**Comment by mathstuf** [comment]
On Tue, Oct 13, 2015 at 13:21:34 -0700, Feng Xiao wrote:
> Could you avoid using "=" in file paths instead (or avoid passing file
> paths with "=" to protoc)?

I wish :) . These are autogenerated paths using sigils to indicate
different parts of the buildname (e.g., = is for architecture).

> It seems very weird to support such file paths. It would be very
> problematic if the "=" sign appears in proto file import path names as
> I am pretty we don't have special handling for such names.

The '=' is in the parentage of the source tree. It shouldn't be in the
import paths at all (AFAIK).

> And I also believe this PR addresses one special case
> but not the general problem of using "=" in file paths. For example,
> how would you interpret such a proto_path:
> ```bash
> $ protoc --proto_path=foo/bar=dir/with=sign xxx.proto
> ```

The code only splits on the first '=', so this would first try
'dir/with=sign' and then if that fails, 'foo/bar=dir/with=sign'.
Supporting *aliases* with '=' seems less interesting :) .

**Comment by xfxyjwf** [comment]
On Tue, Oct 13, 2015 at 1:43 PM, Ben Boeckel <notifications@github.com>
wrote:

> On Tue, Oct 13, 2015 at 13:21:34 -0700, Feng Xiao wrote:
> > Could you avoid using "=" in file paths instead (or avoid passing file
> > paths with "=" to protoc)?
>
> I wish :) . These are autogenerated paths using sigils to indicate
> different parts of the buildname (e.g., = is for architecture).
>
What's the source tree layout of your project? If "=" does not appear in
proto file import paths, there gets to be a way to avoid it in protoc
invocations. For example:
/tmp$ cd dir/with=sign
/tmp/dir/with=sign$ protoc --proto_path=. path/to/protos ...

**Comment by mathstuf** [comment]
On Tue, Oct 13, 2015 at 14:03:01 -0700, Feng Xiao wrote:
> What's the source tree layout of your project? If "=" does not appear in
> proto file import paths, there gets to be a way to avoid it in protoc
> invocations. For example:
> /tmp$ cd dir/with=sign
> /tmp/dir/with=sign$ protoc --proto_path=. path/to/protos ...

Not really. With out-of-source builds, there may not *be* a relative
path to the source tree from the binary tree, so CMake always uses the
absolute path to the source directory. Changing directory into the
source tree is generally not done for out-of-source builds (I don't
think I've ever seen such a thing at least).

**Comment by xfxyjwf** [comment]
On Tue, Oct 13, 2015 at 2:11 PM, Ben Boeckel <notifications@github.com>
wrote:

> On Tue, Oct 13, 2015 at 14:03:01 -0700, Feng Xiao wrote:
> > What's the source tree layout of your project? If "=" does not appear in
> > proto file import paths, there gets to be a way to avoid it in protoc
> > invocations. For example:
> > /tmp$ cd dir/with=sign
> > /tmp/dir/with=sign$ protoc --proto_path=. path/to/protos ...
>
> Not really. With out-of-source builds, there may not *be* a relative
> path to the source tree from the binary tree, so CMake always uses the
> absolute path to the source directory. Changing directory into the
> source tree is generally not done for out-of-source builds (I don't
> think I've ever seen such a thing at least).

Thanks. Seems there isn't a way to workaround here.

I'll merge this PR after the CLA issue is resolved. The original signer of
the Kitware CLA is Berk Geveci. As far as I can tell, he hadn't provided us
a list of authorized contributors under this CLA, so I can't accept this PR
until we get a updated list of authorized contributors. Could you contact
him to update the CLA?

**Comment by mathstuf** [comment]
Thanks. Going through our process here (it seems to have changed since he signed it) :) .

**Comment by mathstuf** [comment]
So we've updated to the Google Groups CLA thing now.

**Comment by mathstuf** [comment]
I signed it!

**Comment by mathstuf** [comment]
Ping? Is there some detection that isn't working?

**Comment by xfxyjwf** [comment]
@mathstuf, I still cannot find the CLA for you (check https://signcla.corp.google.com/). Are you using a different email for your CLA? Presumably the CLA only covers your corp email like mathstuf@kitware.com?

**Comment by mathstuf** [comment]
On Wed, Apr 20, 2016 at 15:04:00 -0700, Feng Xiao wrote:
> @mathstuf, I still cannot find the CLA for you (check https://signcla.corp.google.com/). Are you using a different email for your CLA? Presumably the CLA only covers your corp email like mathstuf@kitware.com? 

The author and committer email are using my Kitware email address
(ben.boeckel@kitware.com) which is an alternate email on this account.

**Comment by xfxyjwf** [comment]
Could you check again? I'm seeing Ben Boeckel <mathstuf@gmail.com> as the commiter:
https://github.com/mathstuf/protobuf/commit/44c36312fe7eb2d77f8b5ea8bc5d2adc50bc5a41.patch

**Comment by mathstuf** [comment]
Ah ha. I had cherry-picked from our internal fork of protobuf into my local github clone without changing `user.email`.

**Comment by xfxyjwf** [comment]
ok to test

**Comment by mathstuf** [comment]
The failing test here doesn't seem related (NuGet package errors).

**Comment by xfxyjwf** [comment]
Thanks!

**Pull request merged**
