### PR TITLE
Fix hash computation for JRuby's RubyMessage

### PR DESCRIPTION
**Pull request by abscondment**
#2037 added a test that exposed a bug in the JRuby extension: `System.identityHashCode` returns a hash that does not consider a Message's values. This means two Messages with identical values will not have identical hashCodes.

This patch uses the pattern from RubyMap to combine the hashCodes from all values in a given message and produce a unique, consistent, value-based hash.

### CODE REVIEW

**Comment by abscondment** [comment]
@haberman Here's the fix for the JRuby breakage - thanks!

**Comment by haberman** [comment]
Thanks! I will merge it once the tests pass.

**Comment by abscondment** [comment]
AppVeyor seems to be tripping over itself.

```
Build execution time has reached the maximum allowed time for your plan (60 minutes).
```

**Comment by haberman** [comment]
Travis is good enough for me here. Thanks again for the fix!

**Pull request merged**
