### PR TITLE
Add remaining not-already-imported well known types files to podspec

### PR DESCRIPTION
**Pull request by murgatroid99**

### CODE REVIEW

**Comment by jcanizales** [comment]
(Please incorporate https://github.com/murgatroid99/protobuf/pull/1 into this branch before merging).

**Comment by jcanizales** [comment]
The version of the podspec currently on the repo doesn't compile correctly. This version is tested to compile and work with ObjC gRPC v0.5.1.

**Comment by jcanizales** [comment]
This includes a workaround for Issue #449 , which breaks all dependents that use Cocoapods.

**Comment by TeBoring** [comment]
LGTM

**Pull request merged**
