### PR TITLE
Add missing includes

### PR DESCRIPTION
**Pull request by jbrianceau**
This changes fixes "use of undeclared identifier 'INT_MAX'"
compilation error.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by jbrianceau** [comment]
I get the following compilation errors when I try to [upgrade Chromium's protobuf version](https://codereview.chromium.org/2495533002/#) ;

```
[2704/12191] CXX newlib_pnacl/obj/third_party/protobuf/protobuf_lite/wire_format_lite.o
FAILED: newlib_pnacl/obj/third_party/protobuf/protobuf_lite/wire_format_lite.o 
/b/c/cipd/goma/gomacc ../../native_client/toolchain/linux_x86/pnacl_newlib/bin/pnacl-clang++ -MMD -MF newlib_pnacl/obj/third_party/protobuf/protobuf_lite/wire_format_lite.o.d -DNACL_TC_REV=f7d719122cd7c2fe3ebc52e7c0b011c583bf3e9c -DV8_DEPRECATION_WARNINGS -DENABLE_PDF=1 -DDCHECK_ALWAYS_ON=1 -DUSE_OPENSSL_CERTS=1 -DNO_TCMALLOC -DUSE_PROPRIETARY_CODECS -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -I../.. -Inewlib_pnacl/gen -I../../third_party/protobuf/src -fno-strict-aliasing -fcolor-diagnostics -O2 -fno-ident -fdata-sections -ffunction-sections -g1 -fvisibility=hidden -Werror -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-unused-function -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -c ../../third_party/protobuf/src/google/protobuf/wire_format_lite.cc -o newlib_pnacl/obj/third_party/protobuf/protobuf_lite/wire_format_lite.o
In file included from ../../third_party/protobuf/src/google/protobuf/wire_format_lite.cc:35:
In file included from ../../third_party/protobuf/src/google/protobuf/wire_format_lite_inl.h:47:
../../third_party/protobuf/src/google/protobuf/message_lite.h:252:50: error: use of undeclared identifier 'INT_MAX'
    GOOGLE_DCHECK_LE(result, static_cast<size_t>(INT_MAX));
                                                 ^
```

```
[2706/12191] CXX newlib_pnacl/obj/third_party/protobuf/protobuf_lite/coded_stream.o
FAILED: newlib_pnacl/obj/third_party/protobuf/protobuf_lite/coded_stream.o 
/b/c/cipd/goma/gomacc ../../native_client/toolchain/linux_x86/pnacl_newlib/bin/pnacl-clang++ -MMD -MF newlib_pnacl/obj/third_party/protobuf/protobuf_lite/coded_stream.o.d -DNACL_TC_REV=f7d719122cd7c2fe3ebc52e7c0b011c583bf3e9c -DV8_DEPRECATION_WARNINGS -DENABLE_PDF=1 -DDCHECK_ALWAYS_ON=1 -DUSE_OPENSSL_CERTS=1 -DNO_TCMALLOC -DUSE_PROPRIETARY_CODECS -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -I../.. -Inewlib_pnacl/gen -I../../third_party/protobuf/src -fno-strict-aliasing -fcolor-diagnostics -O2 -fno-ident -fdata-sections -ffunction-sections -g1 -fvisibility=hidden -Werror -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-unused-function -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -c ../../third_party/protobuf/src/google/protobuf/io/coded_stream.cc -o newlib_pnacl/obj/third_party/protobuf/protobuf_lite/coded_stream.o
In file included from ../../third_party/protobuf/src/google/protobuf/io/coded_stream.cc:41:
In file included from ../../third_party/protobuf/src/google/protobuf/io/coded_stream_inl.h:41:
../../third_party/protobuf/src/google/protobuf/io/coded_stream.h:640:46: error: use of undeclared identifier 'INT_MAX'
  static const int kDefaultTotalBytesLimit = INT_MAX;                                             ^
```
See patch set 9 trybots results in [Chromium's CL](https://codereview.chromium.org/2495533002/#) for further information.

**Comment by jbrianceau** [comment]
I also get the following error with Win trybots :
```
e:\b\c\b\win\src\third_party\protobuf\src\google\protobuf\compiler\js\embed.cc(88): note: while trying to match the argument list '(std::basic_ostream<char,std::char_traits<char>>, std::string)'
e:\b\c\b\win\src\third_party\protobuf\src\google\protobuf\compiler\js\embed.cc(90): error C2039: 'getline': is not a member of 'std'
```

**Comment by jbrianceau** [comment]
@xfxyjwf for review (sorry to bother you again with my Chromium upgrade)

**Comment by xfxyjwf** [comment]
LGTM

Thanks for the patch!

**Pull request merged**
