### PR TITLE
2.6.1 artifacts

### PR DESCRIPTION
**Pull request by aaryav19**

### CODE REVIEW

**Comment by xfxyjwf** [comment]
@aaryav19 I am confused. What does this PR intend to do?

**Comment by aaryav19** [comment]
Sorry for this PR. I am just learning GitHub and by mistakenly i sent this
PR.

**Comment by aaryav19** [comment]
Contacts

**Review by Kalakaarboyz1 — COMMENTED** [review]
Kindly check this out. I tried so many times to report this into google vrp but I don't think they took seriously

**Pull request closed without merging**
