### PR TITLE
close opened file descriptors properly

### PR DESCRIPTION
**Pull request by bryongloden**
[src/google/protobuf/testing/file.cc:95]: (error) Resource leak: file

Found by https://github.com/bryongloden/cppcheck

### CODE REVIEW

**Comment by xfxyjwf** [comment]
Can you update the commit message? What's is "update sha1_driver.c"?

**Comment by bryongloden** [comment]
Greetings @xfxyjwf 👍

F.W.I.W. calling fclose() will ensure the file descriptor is properly disposed of and output buffers flushed so the data written to the file will be present in the file on disk. CREDIT: http://cboard.cprogramming.com/c-programming/137322-need-fclose.html#post1021970

What if I rename the commit message "Update sha1_driver.c because there exist a bug inside it"? Would that be all right? Alternatively, I could rename it "Update sha1_driver.c because there exist a bug on line 95". I'll take suggestions if there is something else you have in mind.

Thank you

**Comment by xfxyjwf** [comment]
I don't really understand how this protobuf change has anything to do with sha1_driver.c. Could you just change the commit message to "close opened file descriptors properly"?

**Comment by bryongloden** [comment]
Sorry @xfxyjwf. I just noticed that the file I'm patching here is named `file.cc` (and not `sha1_driver.c` as the original commit messaged suggested. I believe `sha1_driver.c` was a file name from another project I'm volunteering on, and this was a copy/paste mistake. You could have just said the file name is "`file.cc`" and not "sha1_driver.c" #LOLSEC

**Comment by xfxyjwf** [comment]
Thanks @bryongloden . I see you updated the pull request title. Can you also update the commit description?

**Comment by bryongloden** [comment]
No, this is not directly possible via the GitHub website (where I submitted the patch). I believe the commit message is related to the commit SHA / hash, and if I change it the commit SHA is also changed. [Prabowo Murti](http://stackoverflow.com/users/2236241/prabowo-murti) [recommends](http://stackoverflow.com/a/16011536) creating a comment on that commit. My way is to close this commit and resubmit...

**Comment by xfxyjwf** [comment]
It can't be changed via Github UI, but can you use do "git commit --amend" and "git push -f"? After that it should be reflected on this pull request.

**Comment by bryongloden** [comment]
Sorry @xfxyjwf I'm new to the git command. Just so we're clear, I've done _everything_ on https://github.com/google/protobuf/pull/1923 and https://github.com/google/protobuf/pull/1923/commits/72dcee566c1428ce0200ae4abe455c48960edf16 from the GitHub website, i.e. I haven't ever used the command line tool `git` for anything _ever_.

So to start out trying to change the commit message your way I first press the green button '**clone or download**' from the https://github.com/google/protobuf website. Next I open a terminal on OS X El Capitan and `cd` to the directory of `protobuf` after it is unzipped. Then I type `git init` and next I type `git commit --amend -m "close opened file descriptors properly"`. However, at this point the system then says `"fatal: You have nothing to amend."` Can you please help me understand what commands I'm suppose to type. Subsequent Googling for answers hasn't helped thus far. I'm glad to change the commit message name if I know how.

Thank you

**Comment by xfxyjwf** [comment]
The commands you need run to update the commit:
```bash
$ git clone https://bryongloden@github.com/bryongloden/protobuf
$ cd protobuf
$ git reset --hard origin/patch-1
$ git commit --amend -m "close opened file descriptors properly"
$ git push -f origin master:patch-1
```
You will probably need to type your github password for the last command. After that this pull request should reflect the new commit message.

**Pull request merged**
