### PR TITLE
adding globals() to exec call for python3 compatibility

### PR DESCRIPTION
**Pull request by btabibian**
The recent change in setup.py breaks compatibility with python3. passing globals() to exec provides the same behavior across python 2 and python 3.

http://stackoverflow.com/questions/24733831/using-a-function-defined-in-an-execed-string-in-python-3

### CODE REVIEW

**Comment by btabibian** [comment]
Signed the CLA as an individual.

**Comment by btabibian** [comment]
Added the missing email address to my account.

**Comment by btabibian** [comment]
Can someone help me resolve this issue? I would not want to base my application on the my fork.

**Comment by tamird** [comment]
@btabibian you need to [fix your git config to include your email](https://help.github.com/articles/set-up-git/#setting-up-git) and then reauthor your commit: `git commit --anemd --reset-author && git push -f`

**Comment by btabibian** [comment]
@tamird Thanks for your heads up.

**Comment by tamird** [comment]
@haberman this should be good to merge - the build failure was a strange maven issue on travis' side.

**Comment by btabibian** [comment]
@haberman @tamird I fixed a styling issue and I suppose the rerun was successful.

**Pull request merged**
