### PR TITLE
Update csharp-experimental with changes from upstream/master

### LINKED ISSUE #519: C# cleanup: Revisit changes to wire_format.h
csharp-experimental branch contains a change to wire_format.h that we may not want. See 
#493 - Jon can probably create a different workaround if desired.

@jskeet FYI

### PR DESCRIPTION
**Pull request by jtattermusch**
This also seems to revert the changes you've made in wire_format.h.  So I think this fixes #519 - how would we verify?

### CODE REVIEW

**Comment by jtattermusch** [comment]
CLA is fine, these are changes coming from upstream/master.

**Comment by jskeet** [comment]
I think I reverted the changes to wire_format.h myself a while ago - I have a later commit which adds a local fixup. (It should still be done by someone, but not me...) Will close that issue with a note.

Assuming everything merges cleanly, is there anything you particularly want me to look at here? I'm happy for us to merge otherwise.

**Comment by jtattermusch** [comment]
wire_format.h was my major concern. Besides that, everything looks fine to me.

**Comment by jskeet** [comment]
Great. Will merge and rebase my pending changes.

**Pull request merged**
