### PR TITLE
Updated upb: JSON parser now accepts both camelCase and original case, and flag to choose on output.

### PR DESCRIPTION
**Pull request by haberman**
The flags are:

  UPB_JSON_ACCEPT_LEGACY_FIELD_NAMES
  UPB_JSON_WRITE_LEGACY_FIELD_NAMES

The first just allows the parser to accept the old field names.
The second makes the printer print the old field names.

These flags are intended to be temporary, as a migration aid
for users.

### CODE REVIEW

**Comment by haberman** [comment]
Review to @xfxyjwf.

The upb code was reviewed in the upb repo, but the README changes and the general migration strategy can still be reviewed here.

**Comment by xfxyjwf** [comment]
We discussed this issue before and ended up deciding the parser should accept both forms. For the serializer there will be a public runtime option for users to keep using the original field name if they want. So we don't need the first option, and the second one can be a public flag.

The conformance test currently covers part of these:
https://github.com/google/protobuf/blob/master/conformance/conformance_test.cc#L664

**Comment by haberman** [comment]
@xfxyjwf PTAL.

**Comment by haberman** [comment]
Retitled the PR to reflect the new approach: now the parser always accepts both and the output is controlled by a runtime flag.

**Comment by xfxyjwf** [comment]
LGTM

**Pull request merged**
