### PR TITLE
Allow Python Protobufs to work with numpy int32/float

### PR DESCRIPTION
**Pull request by eiderman**
This change allows Python protobufs to accept any numeric type that follows the python numbers protocol. It also speeds up adding items to arrays.

### CODE REVIEW

**Comment by eiderman** [comment]
I signed it!

**Comment by anandolee** [comment]
Sorry we missed your PR. Our code base has already changed  to work with numpy int32/float, and is now very similar with your change.

I am closing it for clean up.

**Comment by eiderman** [comment]
Thanks! This landed in the internal repo long ago.

**Comment by thisch** [comment]
Does that mean that protobuf already supports serializing numpy arrays (size > 1) or only numpy scalars? BTW there are no unit-tests in the protobuf repo, which test the numpy support.

**Pull request closed without merging**
