### PR TITLE
Remove pre-installed softwares from prebuild steps 

### PR DESCRIPTION
**Pull request by matt-kwong**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by pherl** [comment]
Probably wait and see if kokoro mac tests pass.

**Comment by pherl** [comment]
From the log I guess we still need the "node". Not sure what happened to the objc job though.

**Comment by matt-kwong** [comment]
All of the required Kokoro tests are passing. This is ready to be merged.

**Comment by pherl** [comment]
Could you also send a PR to merge to 3.4.x as well?

**Comment by matt-kwong** [comment]
Opened #3556

**Pull request merged**
