### PR TITLE
Integrate google internal changes to master

### PR DESCRIPTION
**Pull request by pherl**
@TeBoring @nmittler for review.

### CODE REVIEW

**Comment by TeBoring** [comment]
LGTM

**Comment by danielweis** [comment]
LGTM for Java changes.

**Comment by pherl** [comment]
@jskeet  Hi Jon, it seems the csharp continuous build is complaining. Do you think this change is related? https://ci.appveyor.com/project/protobuf/protobuf/build/1.0.1198/job/2hyw95nphfqgoqaj

**Comment by jskeet** [comment]
It looks like there's a typo somewhere for one thing:

BeforeGenerateProjectPriFile

I'm not yet sure what it *should* be, but that's a pretty odd error. I'll have a look and see what I can find out.

**Comment by jskeet** [comment]
Hmm. There's no sign of that in the source code, and checking out the pull request locally, the solution file builds fine. My *guess* is that the problem is with the machine that Appveyor is running on.

Is it worth just trying to rerun the Appveyor build, if that's feasible? If there's a way of forcing a "machine clean" first, that would be even better...

**Comment by pgrosu** [comment]
Hi Jon/Jisi,

I think the error is the following missing file that would probably be retrieved via NuGet:

(EnsureNuGetPackageBuildImports target) -> 
  C:\projects\protobuf\csharp\src\Google.Protobuf\Google.Protobuf.csproj(158,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NuSpec.ReferenceGenerator.1.4.1\build\portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10\NuSpec.ReferenceGenerator.targets


Hope it helps,
Paul

**Comment by pgrosu** [comment]
Interesting... When I perform some changes to the `csharp` protion of the `appveyor.bat` script in the following way, it seems to work:

```
%comspec% /k "C:\Program Files\Microsoft Visual Studio 14.0\Common7\Tools\VsMSBuildCmd.bat"
git clone -q https://github.com/google/protobuf.git C:\projects\protobuf
cd c:\projects\protobuf
git fetch -q origin +refs/pull/1199/merge:
git checkout -qf FETCH_HEAD
wget --quiet https://googlemock.googlecode.com/files/gmock-1.7.0.zip
unzip gmock-1.7.0.zip
cd csharp\src
wget --quiet https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
nuget restore
msbuild Google.Protobuf.sln /p:Platform="Any CPU" 
wget --quiet https://github.com/nunit/nunit/releases/download/3.0.1/NUnit-3.0.1.zip
unzip NUnit-3.0.1.zip
bin\nunit3-console Google.Protobuf.Test\bin\Debug\Google.Protobuf.Test.dll 
```

Below are the result, showing only the relevant parts - I put an ellipsis (...) for the longer portions:

```
> %comspec% /k "C:\Program Files\Microsoft Visual Studio 14.0\Common7\Tools\VsMSBuildCmd.bat"
> git clone -q https://github.com/google/protobuf.git C:\projects\protobuf
> cd c:\projects\protobuf
> git fetch -q origin +refs/pull/1199/merge:
> git checkout -qf FETCH_HEAD
> wget --quiet https://googlemock.googlecode.com/files/gmock-1.7.0.zip
> unzip gmock-1.7.0.zip
Archive:  gmock-1.7.0.zip
   creating: gmock-1.7.0/
   creating: gmock-1.7.0/build-aux/
  inflating: gmock-1.7.0/build-aux/config.h.in
...
> cd csharp\src
> wget --quiet https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
> nuget restore
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files\MSBuild\14.0\bin'.
Feeds used:
  C:\Users\Me\AppData\Local\NuGet\Cache
  C:\Users\Me\.nuget\packages\
  https://api.nuget.org/v3/index.json

Restoring NuGet package NuSpec.ReferenceGenerator.1.4.1.
Restoring NuGet package NUnit.2.6.4.
Restoring NuGet package NUnitTestAdapter.2.0.0.
Adding package 'NUnit.2.6.4' to folder 'c:\projects\protobuf\csharp\src\packages'
Adding package 'NUnitTestAdapter.2.0.0' to folder 'c:\projects\protobuf\csharp\src\packages'
Adding package 'NuSpec.ReferenceGenerator.1.4.1' to folder 'c:\projects\protobuf\csharp\src\packages'
Added package 'NUnitTestAdapter.2.0.0' to folder 'c:\projects\protobuf\csharp\src\packages'
Added package 'NUnit.2.6.4' to folder 'c:\projects\protobuf\csharp\src\packages'
Added package 'NuSpec.ReferenceGenerator.1.4.1' to folder 'c:\projects\protobuf\csharp\src\packages'

> msbuild Google.Protobuf.sln /p:Platform="Any CPU"
Microsoft (R) Build Engine version 14.0.24720.0
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 1/30/2016 10:23:26 AM.
Project "c:\projects\protobuf\csharp\src\Google.Protobuf.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Project "c:\projects\protobuf\csharp\src\Google.Protobuf.sln" (1) is building "c:\projects\protobuf\csh arp\src\Google.Protobuf\Google.Protobuf.csproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "bin\Debug\".
  Creating directory "obj\Debug\".
ResolveAssemblyReferences:
  A TargetFramework profile exclusion list will be generated.
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with
respect to the input files.
CoreCompile:
  C:\Program Files\MSBuild\14.0\bin\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt
  /warn:4 /doc:bin\Debug\Google.Protobuf.xml /define:DEBUG;TRACE /reference:"C:\Program Files\Reference
   Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile259\mscorlib.dll" /reference:"C:\Pro
...
  Google.Protobuf.JsonDump -> c:\projects\protobuf\csharp\src\Google.Protobuf.JsonDump\bin\Debug\Google
  .Protobuf.JsonDump.exe
  Copying file from "obj\Debug\Google.Protobuf.JsonDump.pdb" to "bin\Debug\Google.Protobuf.JsonDump.pdb
  ".
Done Building Project "c:\projects\protobuf\csharp\src\Google.Protobuf.JsonDump\Google.Protobuf.JsonDum p.csproj" (default targets).

The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files\MSBu ild\Microsoft\NuGet\Microsoft.NuGet.targets (186,61)" does not exist in the project, and will be ignore d.
Project "c:\projects\protobuf\csharp\src\Google.Protobuf.sln" (1) is building "c:\projects\protobuf\csh arp\src\Google.Protobuf.Conformance\Google.Protobuf.Conformance.csproj" (6) on node 1 (default targets) .
PrepareForBuild:
  Creating directory "bin\Debug\".
  Creating directory "obj\Debug\".
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with
respect to the input files.
CoreCompile:
  C:\Program Files\MSBuild\14.0\bin\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:anycpu32bi
  tpreferred /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+ /reference:c:\projects\pro
  tobuf\csharp\src\Google.Protobuf\bin\Debug\Google.Protobuf.dll /reference:"C:\Program Files\Reference
...
CopyFilesToOutputDirectory:
  Copying file from "obj\Debug\Google.Protobuf.Conformance.exe" to "bin\Debug\Google.Protobuf.Conforman
  ce.exe".
  Google.Protobuf.Conformance -> c:\projects\protobuf\csharp\src\Google.Protobuf.Conformance\bin\Debug\
  Google.Protobuf.Conformance.exe
  Copying file from "obj\Debug\Google.Protobuf.Conformance.pdb" to "bin\Debug\Google.Protobuf.Conforman
  ce.pdb".
Done Building Project "c:\projects\protobuf\csharp\src\Google.Protobuf.Conformance\Google.Protobuf.Conf ormance.csproj" (default targets).

Done Building Project "c:\projects\protobuf\csharp\src\Google.Protobuf.sln" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.49

> wget --quiet https://github.com/nunit/nunit/releases/download/3.0.1/NUnit-3.0.1.zip

> unzip NUnit-3.0.1.zip
> bin\nunit3-console Google.Protobuf.Test\bin\Debug\Google.Protobuf.Test.dll
NUnit Console Runner 3.0.5813
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  CLR Version: 4.0.30319.42000

Test Files
    Google.Protobuf.Test\bin\Debug\Google.Protobuf.Test.dll


Test Run Summary
    Overall result: Passed
   Tests run: 868, Passed: 868, Errors: 0, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2016-01-30 15:23:45Z
    End time: 2016-01-30 15:23:48Z
    Duration: 2.998 seconds

Results (nunit3) saved as TestResult.xml

>
```

Most likely either the `appveyor.bat` script might need updating, and/or like Jon (@jskeet) suggested of ensuring that the build environment is clean and has all its tools up to date.

Hope it helps,
Paul

**Comment by jskeet** [comment]
I've just checked that the file it claims isn't present is definitely part of NuSpec.ReferenceGenerator.1.4.1. That's weird.

Adding @jtattermusch who may have seen this - I believe he added the NuSpec reference detection (as part of issue #1051).

**Comment by nmittler** [comment]
LGTM

**Comment by pgrosu** [comment]
One could try to include the packages `NUnit.2.6.4`, `NuSpec.ReferenceGenerator.1.4.1`, `NUnitTestAdapter.2.0.0` under the `csharp\src\packages` folder, but those could change with time, and having the script get the most updated version would seem more reasonable.

~p

**Comment by pherl** [comment]
OK. The failure doesn't seem to be related with this PR. I will merge it now and we can fix the C# issue separately.

**Pull request merged**
