### PR TITLE
Windows: expand wildcard arguments

### PR DESCRIPTION
**Pull request by laszlocsomor**
Fixes https://github.com/google/protobuf/issues/3957

### CODE REVIEW

**Comment by laszlocsomor** [comment]
I think the MacOS JRuby failure is a flake, given that this commit modifies Windows-specific `cc_binary.linkopts`.

**Comment by pherl** [comment]
Any idea if the command line is expanded before the long path change? Also how about other builds that do not use bazel? We cross compile the protoc.exe for windows under linux so probably won't be able to link this object file. Are there any alternatives?

**Comment by laszlocsomor** [comment]
> Any idea if the command line is expanded before the long path change?

Yes, command line expansion is completely unrelated to long path support.
For the expansion, I'm merely linking in a precompiled object file that's part of the compiler's set of standard libraries (and other precompiled object files).

> Also how about other builds that do not use bazel? We cross compile the protoc.exe for windows under linux so probably won't be able to link this object file. Are there any alternatives?

Good point. I don't know; the object file I'm linking in is installed either by Visual C++, or by the Windows SDK. Both are native Windows software, so I think in case of cross-compilation, you'll either have to implement the path expansion logic in protoc, or use some third-party library.

**Comment by F21** [comment]
Is there any update for this one? The 3.5.x series is currently unusable for generating Go code on Windows if we have multiple .proto files in the same package.

**Comment by laszlocsomor** [comment]
@F21 : No updates from my side. AFAIK the Protobuf Team cross-compiles the Windows version on Linux, so I guess my proposed solution of linking to a pre-built object file would only work when building on Windows. I'll look at 3.4.x and 3.5.x and try to figure out why 3.4.x can support wildcards and why 3.5.x can't.

**Comment by F21** [comment]
@laszlocsomor Thanks for the update! 👍 I haven't written any C++ for many years, so I'll leave it to the experts 😄

**Comment by laszlocsomor** [comment]
@pherl :
I downloaded the 3.4.0 and 3.5.1 sources and release binaries.
- release 3.4.0 supports wildcards, 3.5.1 doesn't
- if I build protoc.exe using bazel on windows (`bazel build //:protoc`), neither of them supports wildcards
- if I comment out `SUPPORT_LONGPATHS` in `src/google/protobuf/stubs/io_win32.cc` then rebuild with bazel, they still do not support wildcards

How can I crosscompile protoc for Windows under Linux?

**Comment by pherl** [comment]
Please check https://github.com/google/protobuf/blob/master/protoc-artifacts/README.md in particular maven invokes this script: https://github.com/google/protobuf/blob/master/protoc-artifacts/build-protoc.sh  For windows cross compile, we need `i686-w64-mingw32-gcc` (32bit) and `x86_64-w64-mingw32-gcc` (64bit) deb packages.

**Comment by laszlocsomor** [comment]
Thanks @pherl ! I could successfully build protoc.exe from source, however the binaries I built still don't support wildcards, not even my 3.4.0 build.

This is the command I used:

```
$ ./autogen.sh && ./configure && protoc-artifacts/build-protoc.sh windows x86_64 protoc
```

It produced the output under `protoc-artifacts/target/protoc.exe`.

Do you know what I may have done wrong?

**Comment by F21** [comment]
Any updates?

**Comment by laszlocsomor** [comment]
No updates from me.
Waiting for guidance on how to build protoc 3.4.0 such that it supports wildcard expansion so I can compare that with 3.5.1.

**Comment by xfxyjwf** [comment]
@laszlocsomor this PR looks good to me. Could you resolve the merge conflicts?

**Comment by laszlocsomor** [comment]
@xfxyjwf : Thanks for looking! I just rebased on master and pushed again.

**Comment by laszlocsomor** [comment]
The Linux C++ Distcheck failure seems unrelated to me:
```
++ for FILE in '$(<../dist.lst)'
++ file src/google/protobuf/wrappers.proto
++ cd ..
++ '[' '!' -z 'ruby/tests/test_ruby_package.proto ' ']'
++ echo 'Missing files in EXTRA_DIST: ruby/tests/test_ruby_package.proto '
Missing files in EXTRA_DIST: ruby/tests/test_ruby_package.proto 
++ exit 1
```

The MacOS JRuby failures I cannot assess.

@xfxyjwf : Please advise how to proceed.

**Comment by xfxyjwf** [comment]
The Linux C++ Distcheck failure is caused by this PR:
https://github.com/google/protobuf/pull/4627

**Comment by laszlocsomor** [comment]
Thanks!

**Pull request merged**
