### PR TITLE
Fix spelling error of __GNUC_MINOR__

### PR DESCRIPTION
**Pull request by Rasrack**

### CODE REVIEW

**Comment by Rasrack** [comment]
I signed it!

**Comment by pherl** [comment]
OK to test

**Comment by acozzette** [comment]
Thanks for the pull request!

**Comment by matthauck** [comment]
I think I was the one that spelled this wrong first time around :disappointed:. Looks like `undef <= 1` resolves to true... on gcc <= 4.1...? :man_shrugging: 

Was about to submit a PR to fix it and found this one instead. Any chance this can get backported to 3.5.x branch?

**Comment by acozzette** [comment]
Sure, I just sent out PR #5001 to backport this to 3.5.x.

**Comment by matthauck** [comment]
Sweet, thanks!

**Pull request merged**
