### PR TITLE
Add auto-generated header to C# generated files

### PR DESCRIPTION
**Pull request by jtattermusch**
Partial fix for https://github.com/google/protobuf/issues/3388

Similar change for gRPC: https://github.com/grpc/grpc/pull/13739

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @yaakov-h

**Comment by anandolee** [comment]
ok to test

**Comment by jtattermusch** [comment]
@anandolee  please merge if the tests look alright (I'm not sure about the "Jenkins" checkmark failure)

**Comment by Spintronic** [comment]
@jtattermusch any idea when the "<auto-generated>" tag might get release via Nuget? v3.5.1 does not appear to contain the change.

**Comment by Spintronic** [comment]
the `<auto-generated>` tag

**Comment by jtattermusch** [comment]
@anandolee  what's the ETA for protobuf 3.6?

**Comment by anandolee** [comment]
I can't say an ETA for 3.6, but we usually do a major release once a quarter so target on March maybe

**Pull request merged**
