### PR TITLE
Remove static initializers from Status class.

### PR DESCRIPTION
**Pull request by xyzzyz**
Statically initialized Status objects are replaced with POD types, and
an implicit conversion constructor is added to create Status instance
from these.

This will result in an extra constructor call when using Status::OK and friends, and I'm not sure if this is desirable. Additionally, I think StatusPod type should be in a separate namespace, as I'm not sure we want to expose it as a part of protobuf interface.

### CODE REVIEW

**Comment by xyzzyz** [comment]
Hm, seems like I forgot to run unit tests. It turns out that there are real problems with my proposed implementation, and it really breaks the API. 

Do you see any way to remove these static initializers here without breaking the API?

**Comment by xfxyjwf** [comment]
A possible workaround:
```cpp
class Status {
  static const Status& OK;
}
class StatusPod {
};
const StatusPod kPodOk = {...};
const Status& Status::OK = *reinterpret_cast<const Status*>(&kPodOk);
```

**Comment by haberman** [comment]
add to whitelist

**Comment by xyzzyz** [comment]
xfxyjwf: I don't think it's going to work: StatusPod is not the same as Status, so a) after reinterpret_cast, Status::OK would point to memory that could be out of bounds b) string constructor in Status would not be run.

**Comment by xfxyjwf** [comment]
Hmm, you are right. We probably need to change Status to make it work. How about we change the error_message_ to a string pointer?
```cpp
class Status {
  error::Code error_code_;
  std::string* error_message_;
}
```

**Comment by xyzzyz** [comment]
It will still be statically initialized as long as it is not POD (e.g. it has a constructor, destructor, methods etc).

I created an issue to brainstorm on solution: https://github.com/google/protobuf/issues/1404

**Comment by xyzzyz** [comment]
Hmm, could you take a look at the pull request? The CI is not passing -- the tests are there, however, they work on my machines. I don't see anything obviously wrong with the code. Could you help me?

**Comment by xfxyjwf** [comment]
Close old issues/prs. Note that we begin to allow C++11 features in protobuf so this PR can probably be reworked to take advantage of C++11 features (such as constexpr).

**Pull request closed without merging**
