### PR TITLE
Detect generated code of WKT, addressbook and conformance protos

### LINKED ISSUE #1212: Detect descriptor.proto changes and fail if C# needs regenerating
If descriptor.proto has changed and the C++ hasn't been regenerated, we get a continuous build failure. The same should be true for C#.

Ideally, we should do the same for all our generated code (including wrapper types), but at least descriptor.proto.

This probably involves:
- Editing `generate_descriptor_protos.sh` to call the C# file, just like Objective C
- Detecting the failure in `travish.sh` or wherever the C++ code does it. (Will need to investigate further.)

Note that this does _not_ involve running any C# code - just protoc.

### PR DESCRIPTION
**Pull request by anandolee**
Add auto detect for generated code of WKT protos, addressbook.proto and conformance.proto

fixes #1212

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by anandolee** [comment]
I'd prefer only add .proto files that are stable into the detect test. We'd better not add unittest .proto files into it which may both other languages too much. Keep these parameters in hard code makes the adding more serious and formal.

**Comment by jskeet** [comment]
So long as people know to make the change, of course. I agree it should be relatively rare. Do we have a document somewhere saying "When you add a WKT or similar, you should change X files; when you modify an existing WKT you should rerun Y generation." ?

**Comment by anandolee** [comment]
It is mentioned in the comments of this file:

// If this test fails, run the script
// "generate_descriptor_proto.sh" and add the changed files under
// csharp/src/ to your changelist.

Is it enough?

**Comment by jskeet** [comment]
That's okay for knowing what to do if the test fails - it's more when the tests should be expanded. But that can definitely come later.

**Pull request merged**
