### PR TITLE
Create 3.4.x branch

### PR DESCRIPTION
**Pull request by pherl**
Integration from Google internal.

### CODE REVIEW

**Comment by xfxyjwf** [comment]
I remember 3.3.x branch is not merged back to master yet. Is this 3.4.x branch based off master or 3.3.x?
 Better to merge 3.3.x into master first. @TeBoring

**Comment by xfxyjwf** [comment]
@TeBoring  has a PR https://github.com/google/protobuf/pull/3375 to merge 3.3.x to master. I think you can do another merge from master to 3.4.x after that.

**Comment by pherl** [comment]
No. But we can always do another merge back when 3.3.x is merged back into
master. There are quite a bit of bootstrapping issue right now. I guess
it's easier to resolve the conflicts for now.

**Comment by TeBoring** [comment]
Just merged 3.3.x into master.

**Comment by pherl** [comment]
I will merge this PR for now so people can work on the fix. Currently the following are broken:
- Python3: iterkeys/iteritems/itervalues are removed. __bool__ should be implemented in the deterministic serialization test.
- Jekins 32bit doesn't build.
- Java compatibility doesn't build.

**Pull request merged**
