### PR TITLE
Add support for the TILE-Gx processor family.

### PR DESCRIPTION
**Pull request by martiert**

### CODE REVIEW

**Comment by martiert** [comment]
The CLA has been signed by Cisco Systems.

**Comment by pherl** [comment]
Hmm, could you please sign the CLA so that the googlebot recognize your ID? You can click "signed by your employer" option in the page.

**Comment by edmonds** [comment]
The header guard `GOOGLE_PROTOBUF_ATOMICOPS_INTERNALS_ARM64_GCC_H_` appears to be copied from another file. At least, the `tile` architecture seems to be unrelated to ARM.

**Comment by martiert** [comment]
I'll fix the header guard and submit a patch for that. Thanks for spotting
that Edmonds.

Jisi: I don't see a "signed by your employer" option, just one that let's
me sign for my employer and add a responsible. At least on the links I get
from googlebot.

**Comment by pherl** [comment]
Hi, I've fixed the header and pushed it to head. For the CLA, sorry I remembered it wrong. If the copy right belongs to your employer, could please select the "You plan to submit contributions on behalf of Your employer"? and sign the CLA at https://cla.developers.google.com/clas  ?

**Comment by pherl** [comment]
Hi Martin,

It looks like Cisco has not signed the most recent CLA. Could you please contact your employer for signing the recent CLA? There will be an email group for the contributors of the cooperative CLA, and you would need to add yourself into the mail-group.

**Comment by martiert** [comment]
I'll notify our legal department about that so they can fix it. thanks.

**Pull request merged**
