### PR TITLE
skip group tag for backward compatibility

### PR DESCRIPTION
**Pull request by raoofha**
I don't know what I'm doing but this worked for me.

### CODE REVIEW

**Comment by raoofha** [comment]
I signed it!

**Comment by TeBoring** [comment]
what didn't work for you?

**Comment by raoofha** [comment]
@TeBoring if a message contains a group tag it causes an exception, as a workaround we can just skip the group tag

**Comment by TeBoring** [comment]
Could you add a test?

**Comment by raoofha** [comment]
@TeBoring not at the moment but I look into it

**Comment by TeBoring** [comment]
Feel free to reopen when you have time to add a test.

**Pull request closed without merging**
