### PR TITLE
Add proto2 to proto3 util

### PR DESCRIPTION
**Pull request by BSBandme**
This change is [Reviewable](https://reviewable.io/reviews/google/protobuf/4699)

### CODE REVIEW

**Comment by xfxyjwf** [comment]
Is this ported from our internal code base?

**Comment by BSBandme** [comment]
No, I just added this for new.

**Comment by BSBandme** [comment]
Any updates for this?

**Comment by BSBandme** [comment]
Any updates for this?

**Comment by xfxyjwf** [comment]
Review status: 1 of 7 files reviewed at latest revision, all discussions resolved.

---

*[benchmarks/util/data_proto2_to_proto3_util.h, line 25 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxUoWKCTPjqd9mPxPL:-LDxUoWKCTPjqd9mPxPM:b-mmcau5) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/data_proto2_to_proto3_util.h#L25)):*
> ```objc
>       const FieldDescriptor* field = set_fields[i];
>       if (ShouldBeClear(field)) {
>         reflection->ClearField(message, field);
> ```

"continue" if it's already cleared?

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 26 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxVKge7uMwDewgkLdf:-LDxVKge7uMwDewgkLdg:bt2mpr7) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L26)):*
> ```cpp
> 
> string StripProto(string filename) {
>   if (filename.substr(filename.size() - 11) == ".protodevel") {
> ```

Change this to StripSuffix instead?  It will help avoid these magic numbers.

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 35 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxWK2n2HYhAmFcxlpo:-LDxWK2n2HYhAmFcxlpp:b-xjx7eb) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L35)):*
> ```cpp
> }
> 
> DescriptorPool new_pool_;
> ```

Don't use global objects. If you must have a global object, do it like this:

DescriptorPool* GetDescriptorPool() {
  static DescriptorPool* pool = new DescriptorPool();
  return pool;
}

See: https://engdoc.corp.google.com/eng/doc/devguide/cpp/styleguide.shtml?cl=head#Static_and_Global_Variables

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 41 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxYTGeC9PNE5aXK_tH:-LDxYTGfDNA2BuNInzOM:bctkyqw) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L41)):*
> ```cpp
> class Proto2ToProto3Generator : public CodeGenerator {
>  public:
>   virtual bool GenerateAll(const std::vector<const FileDescriptor*>& files,
> ```

Use "final" instead of "virtual".

See: https://engdoc.corp.google.com/eng/doc/devguide/cpp/styleguide.shtml?cl=head#Inheritance

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 50 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxXU9JD8GUVt-xoHZu:-LDxXU9JD8GUVt-xoHZv:b-a4tqw2) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L50)):*
> ```cpp
>             (new_pool_.FindFileByName(file->name()) == nullptr);
>         for (int j = 0; j < file->dependency_count(); j++) {
>           can_generate &= (new_pool_.FindFileByName(
> ```

This implementation uses bit-wise operators on bool values and doesn't short-cut (i.e., if can_generator is already false, you will continue with the loop even though can_generator will never be changed from false to true).

Consider adding a CanGenerate() helper function instead:

bool CanGenerate(file) {
  if (new_pool_.FindFileByName(file) != nullptr) return false;
  for (...) {
    if (new_pool_.FindFileByName(dep) == nullptr) return false;
  }
  ...
  return true;
}

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 71 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxYc02B0T2pOfvcmlV:-LDxYc02B0T2pOfvcmlW:b-eh1wx4) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L71)):*
> ```cpp
>   }
> 
>   virtual bool Generate(const FileDescriptor* file,
> ```

Use final

---

*[benchmarks/util/schema_proto2_to_proto3_util.h, line 167 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxZ-0IBSFPSfhrWgkY:-LDxZ-0J20Q3eW7mW2pL:b2nh5sb) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/schema_proto2_to_proto3_util.h#L167)):*
> ```objc
>  private:
>   static bool ShouldClearLabel(const FieldDescriptorProto *field) {
>     return field->label() == FieldDescriptorProto::LABEL_OPTIONAL ||
> ```

Isn't LABEL_OPTIONAL the default value? Why do you need to clear it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/protobuf/4699)*

**Comment by BSBandme** [comment]
Review status: 1 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[benchmarks/util/data_proto2_to_proto3_util.h, line 25 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxUoWKCTPjqd9mPxPL:-LEAmdyO0kQCaRBhsgXT:b-896fix) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/data_proto2_to_proto3_util.h#L25)):*
<details><summary><i>Previously, xfxyjwf (Feng Xiao) wrote…</i></summary><blockquote>

"continue" if it's already cleared?
</blockquote></details>

Done.

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 26 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxVKge7uMwDewgkLdf:-LEAlkmuDNdLMs79TYh4:barmsh9) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L26)):*
<details><summary><i>Previously, xfxyjwf (Feng Xiao) wrote…</i></summary><blockquote>

Change this to StripSuffix instead?  It will help avoid these magic numbers.
</blockquote></details>

I think StripSuffix is absl's function? change to use rfind instead.

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 35 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxWK2n2HYhAmFcxlpo:-LE7gisZ2AA4sw_L3hmC:b-3yv395) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L35)):*
<details><summary><i>Previously, xfxyjwf (Feng Xiao) wrote…</i></summary><blockquote>

Don't use global objects. If you must have a global object, do it like this:

DescriptorPool* GetDescriptorPool() {
  static DescriptorPool* pool = new DescriptorPool();
  return pool;
}

See: https://engdoc.corp.google.com/eng/doc/devguide/cpp/styleguide.shtml?cl=head#Static_and_Global_Variables
</blockquote></details>

In fact I think static local DescriptorPool still violates the guide, since it has non-trivial destructor.  
I don't know how to change this code to correct one, since Generator::GenerateAll need "this" pointer to be const, add the pool to the Proto2ToProto3Generator is not doable. 

Anyway I changed to function approach since at least it changes the initilaization to dynamic.

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 41 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxYTGeC9PNE5aXK_tH:-LEAlw3FC71uKu_XHCJi:b-896fix) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L41)):*
<details><summary><i>Previously, xfxyjwf (Feng Xiao) wrote…</i></summary><blockquote>

Use "final" instead of "virtual".

See: https://engdoc.corp.google.com/eng/doc/devguide/cpp/styleguide.shtml?cl=head#Inheritance
</blockquote></details>

Done.

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 50 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxXU9JD8GUVt-xoHZu:-LEAlyyZ-UcKczNLiMbr:b-896fix) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L50)):*
<details><summary><i>Previously, xfxyjwf (Feng Xiao) wrote…</i></summary><blockquote>

This implementation uses bit-wise operators on bool values and doesn't short-cut (i.e., if can_generator is already false, you will continue with the loop even though can_generator will never be changed from false to true).

Consider adding a CanGenerate() helper function instead:

bool CanGenerate(file) {
  if (new_pool_.FindFileByName(file) != nullptr) return false;
  for (...) {
    if (new_pool_.FindFileByName(dep) == nullptr) return false;
  }
  ...
  return true;
}
</blockquote></details>

Done.

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 71 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxYc02B0T2pOfvcmlV:-LE7gePT1wOTVyvovuX-:b-896fix) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L71)):*
<details><summary><i>Previously, xfxyjwf (Feng Xiao) wrote…</i></summary><blockquote>

Use final
</blockquote></details>

Done.

---

*[benchmarks/util/schema_proto2_to_proto3_util.h, line 167 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxZ-0IBSFPSfhrWgkY:-LEAn9w978i9N_pyJusY:b-896fix) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/schema_proto2_to_proto3_util.h#L167)):*
<details><summary><i>Previously, xfxyjwf (Feng Xiao) wrote…</i></summary><blockquote>

Isn't LABEL_OPTIONAL the default value? Why do you need to clear it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/protobuf/4699)*

**Comment by xfxyjwf** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 35 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxWK2n2HYhAmFcxlpo:-LEApMd_-PuSOAd7y3I4:b-boehb1) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L35)):*
<details><summary><i>Previously, BSBandme (Yilun Chong) wrote…</i></summary><blockquote>

In fact I think static local DescriptorPool still violates the guide, since it has non-trivial destructor.  
I don't know how to change this code to correct one, since Generator::GenerateAll need "this" pointer to be const, add the pool to the Proto2ToProto3Generator is not doable. 

Anyway I changed to function approach since at least it changes the initilaization to dynamic.
</blockquote></details>

What I suggested is the common pattern used in google3. Note that it's using a static pointer instead of a static object so the destructor of the object will never be called.

Please read the style guide again, and in particular the last part about common patterns:
https://engdoc.corp.google.com/eng/doc/devguide/cpp/styleguide.shtml?cl=head#Static_and_Global_Variables

"If all else fails, you can create an object dynamically and never delete it by binding the pointer to a function-local static pointer variable: static const auto* const impl = new T(args...); (If the initialization is more complex, it can be moved into a function or lambda expression.)"

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/protobuf/4699)*

**Comment by BSBandme** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[benchmarks/util/protoc-gen-proto2_to_proto3.cc, line 35 at r1](https://reviewable.io/reviews/google/protobuf/4699#-LDxWK2n2HYhAmFcxlpo:-LEAt5w_BMfAEbU6gfBz:bfdvc7n) ([raw file](https://github.com/google/protobuf/blob/193af9f4c1ebfeec4c9322fc4bbb2a513267d345/benchmarks/util/protoc-gen-proto2_to_proto3.cc#L35)):*
<details><summary><i>Previously, xfxyjwf (Feng Xiao) wrote…</i></summary><blockquote>

What I suggested is the common pattern used in google3. Note that it's using a static pointer instead of a static object so the destructor of the object will never be called.

Please read the style guide again, and in particular the last part about common patterns:
https://engdoc.corp.google.com/eng/doc/devguide/cpp/styleguide.shtml?cl=head#Static_and_Global_Variables

"If all else fails, you can create an object dynamically and never delete it by binding the pointer to a function-local static pointer variable: static const auto* const impl = new T(args...); (If the initialization is more complex, it can be moved into a function or lambda expression.)"
</blockquote></details>

Got it. Thx!

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/protobuf/4699)*

**Pull request merged**
