### PR TITLE
Fixing unused parameter warnings under Clang.

### PR DESCRIPTION
**Pull request by drivehappy**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by pherl** [comment]
ok to test

**Comment by pherl** [comment]
Would you like to patch this to the 3.4.x branch also? We will probably have a 3.4.1 release pretty soon.

**Comment by drivehappy** [comment]
Yea, that would be ideal - I would like to patch #3494 as well if possible. What's the process here, should I open another PR for the patch into the 3.4.x branch itself?

**Comment by pherl** [comment]
Yes, please open another PR for the merging into the release branch.

**Pull request merged**
