### PR TITLE
nuspec dependency fixes

### PR DESCRIPTION
**Pull request by jskeet**
This is a *speculative* fix at the moment - Jan, if you could build a new package based on this and give it a try, I'd appreciate it. (When the snk file is checked in, it'll be easier for me to test this myself :)

### CODE REVIEW

**Comment by jskeet** [comment]
Given the discussion on the issue #1203, I'm happy for this to be merged if a quick test confirms that it fixes the problem.

**Comment by jtattermusch** [comment]
Sorry, didn't get to test it yet. Hopefully I'll be able to do that tomorrow.

**Comment by jtattermusch** [comment]
Checking in the snk here: https://github.com/google/protobuf/pull/1220

**Comment by jskeet** [comment]
Now that the SNK is in, I've validated this locally. So basically if it looks okay to you, Jan, we can merge.

**Pull request merged**
