### PR TITLE
Post alpha2 integrate

### PR DESCRIPTION
**Pull request by pherl**
The first commit is generated by integration script; following commits are manual fixes. @cfallin @xfxyjwf @TeBoring  for review.

### CODE REVIEW

**Comment by cfallin** [comment]
LGTM, but maybe have @xfxyjwf or @TeBoring check over the maps changes too.

**Comment by TeBoring** [comment]
test for map lite is not merged intentionally. Do we need to merge it now?
Otherwise, LGTM

**Comment by pherl** [comment]
Last time I tried it's broken. I added a TODO for you. Feel free to work a fix and re-enable the tests.

**Comment by pherl** [comment]
I'll merge the PR for now. We can have another PR to add maps in master.

**Pull request merged**
