### PR TITLE
Add rvalue setters for non-arena strings on C++11.

### PR DESCRIPTION
**Pull request by ckennelly**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by xfxyjwf** [comment]
test this please

**Comment by acozzette** [comment]
ok to test

**Comment by damienmg** [comment]
Has ci.bazel.io vetting worked on this one? It is broken since the merge of this PR.

**Comment by xfxyjwf** [comment]
@damienmg Checking the commit history, it seems ci.bazel.io tests were not ran for this PR even though I commented "test this please".

**Comment by damienmg** [comment]
:/ there is a job though for this PR: http://ci.bazel.io/job/PR-protobuf/12/

**Comment by xfxyjwf** [comment]
@damienmg Probably because the PR was updated again after I commented "test this please"?

**Comment by damienmg** [comment]
Yes looks like it, the tested commit is different. If you want to force a test, you can try to use "retest this please"

**Comment by xfxyjwf** [comment]
I think the culprit is actually https://github.com/google/protobuf/pull/2517 where Adam changed automake and cmake files for a generated .cc file but didn't update BUILD file. @acozzette Could you help take a look? Travis cpp test also fails after that PR.

**Comment by ckennelly** [comment]
Assuming I'm looking at the right Jenkins dashboard, this broke earlier, at http://ci.bazel.io/job/protobuf/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/539/

**Comment by damienmg** [comment]
Yes this is the correct failure.

**Comment by acozzette** [comment]
Sorry about that, I've sent out this pull request that should fix it: https://github.com/google/protobuf/pull/2521

**Pull request merged**
