### PR TITLE
Install google/protobuf/stubs/strutil.h

### PR DESCRIPTION
**Pull request by earhart**

### CODE REVIEW

**Comment by xfxyjwf** [comment]
Why does this header need to be installed?

**Comment by earhart** [comment]
For now, we're using it for StrCat.

**Comment by xfxyjwf** [comment]
I can understand that some users might find these utility functions useful, but as they are not part of protobuf public API, I think we shouldn't include them as public headers.

**Comment by earhart** [comment]
Ok -- thanks!

**Pull request closed without merging**
