### PR TITLE
Fix offset type macro to match the tables it is used in

### LINKED ISSUE #3061: GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET produces an int, but is used in a location that needs a uint32
While `GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET` casts its value to a `google::protobuf::uint32`, `GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET` casts to an `int`. This generates warnings (MSVC 2015) when filling in the offset table in generated code.

### PR DESCRIPTION
**Pull request by randomguy3**
Fixes #3061.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by xfxyjwf** [comment]
ok to test

**Comment by xfxyjwf** [comment]
Obsoleted by PR https://github.com/google/protobuf/pull/3063

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by xfxyjwf** [comment]
Oops, thought the other PR was merged and it appears not.

**Pull request merged**
