### PR TITLE
Remove the executable bit from several source code files

### PR DESCRIPTION
**Pull request by sschuberth**
This potenitally avoids compiler warnings.

### CODE REVIEW

**Comment by xfxyjwf** [comment]
Closing due to conflicts.

**Comment by sschuberth** [comment]
@xfxyjwf I've resolved the conflicts, please re-open. And this time, I suggest to not wait half a year again before merging for new conflicts to arise.

**Comment by xfxyjwf** [comment]
Sorry for the late response. The volume of incoming issues and pull requests are larger than what we can handle and many of them fall through the cracks. I'm setting up a new process to make sure all pull requests will be handled timely.

For this PR, it seems I can't reopen it (the button is gray with a "the remote-exec-bit branch was force-pushed or recreated" tooltip). Can you open a new pull request?

**Comment by sschuberth** [comment]
> I'm setting up a new process to make sure all pull requests will be handled timely.

Thanks. I'd also suggest to use a bot to ping owners of unmerged PRs to resolve any conflicts.

> Can you open a new pull request?

Done: https://github.com/google/protobuf/pull/4824.

**Pull request closed without merging**
