### PR TITLE
Add file option php_class_prefix

### PR DESCRIPTION
**Pull request by TeBoring**
This option will be prepended to generated classes of all messages in
the containing file.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by TeBoring** [comment]
test it please

**Comment by TeBoring** [comment]
@stanley-cheung to review.

**Comment by TeBoring** [comment]
The failed test in jenkins is due to update of composer.json. This needs to be fixed after the PR is merged.

**Pull request merged**
