### PR TITLE
Add $ before url_prefix_len to make it a variable.

### LINKED ISSUE #3617: Use of undefined constant url_prifix_len
After a change to the test script in #3563 the PHP implementation is failing with

```
1) WellKnownTest::testAny
Use of undefined constant url_prifix_len - assumed 'url_prifix_len'

php/src/Google/Protobuf/Any.php:212
php/tests/well_known_test.php:46

2) WellKnownTest::testAnyUnpackInvalidTypeUrl
Use of undefined constant url_prifix_len - assumed 'url_prifix_len'

php/src/Google/Protobuf/Any.php:212
php/tests/well_known_test.php:68

3) WellKnownTest::testAnyUnpackMessageNotAdded
Use of undefined constant url_prifix_len - assumed 'url_prifix_len'

php/src/Google/Protobuf/Any.php:212
php/tests/well_known_test.php:78

4) WellKnownTest::testAnyUnpackDecodeError
Use of undefined constant url_prifix_len - assumed 'url_prifix_len'

php/src/Google/Protobuf/Any.php:212
php/tests/well_known_test.php:89
```

### PR DESCRIPTION
**Pull request by TeBoring**
Fix #3617

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by pherl** [comment]
Shall we put this onto the 3.4 branch too?

**Comment by pherl** [comment]
Also any test to cover this?

**Comment by TeBoring** [comment]
It's strange that no tests were broken.

**Comment by pherl** [comment]
Please verify that this is covered by some test. We probably need to bump the micro version and tag a 3.4.2 for PHP.

**Comment by TeBoring** [comment]
Any support is in master only.

**Comment by TeBoring** [comment]
https://stackoverflow.com/questions/2941169/what-does-the-php-error-message-notice-use-of-undefined-constant-mean
I think this is reported as a notice instead of error. That's why no tests were broken.

**Comment by TeBoring** [comment]
http://php.net/manual/en/function.substr.php
Actually, we don't have to check the length before calling substr.

**Comment by TeBoring** [comment]
Broken test is due to unrelated javanano.

**Pull request merged**
