### PR TITLE
Update docker file

### PR DESCRIPTION
**Pull request by TeBoring**
* Remove oracle-java7
* Add hhvm

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by RyanGordon** [comment]
I tested this locally and it looks like it works; It just takes a long time and Jenkins is timing out at 120 minutes.

**Comment by TeBoring** [comment]
Do you know how to install hhvm on debian 9?

**Comment by RyanGordon** [comment]
It looks like Debian 9 stretch HHVM package is a WIP: https://github.com/hhvm/packaging/commit/e99fdd2157d85133fd64d39194794e996ef27e1e

**Comment by TeBoring** [comment]
I prefer to wait a little bit until hhvm can be installed on Debian 9, so
that it won't affect test of other languages. What do u think about it?

**Comment by RyanGordon** [comment]
That works for me. Are there changes to the Dockerfile that need to be made outside of hhvm for Debian 9 support?

**Comment by TeBoring** [comment]
Maybe some for other languages. I will handle it in another PR.

**Comment by xfxyjwf** [comment]
Closing as there haven't been any updates for a while.

**Pull request closed without merging**
