### PR TITLE
Update minimal ios and osx version for deployment.

### PR DESCRIPTION
**Pull request by TeBoring**

### CODE REVIEW

**Comment by TeBoring** [comment]
@jcanizales to review

**Comment by jcanizales** [comment]
LGTM, but I'd have @thomasvl and @dmaclach review, because "deployment target" and "base SDK" still confuse me. For example, I see on Apple's documentation that `nullable`, `nonnull` etc. are supported starting with XCode 6.3, but I can't make the link between that and iOS version. It sounds more like a feature of clang, and they do say the ABI of the files doesn't change by using them.

**Comment by TeBoring** [comment]
In the test, I see the deployment target for ios and osx is 7.1 and 10.9 respectively.
https://github.com/google/protobuf/blob/master/objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj#L863
https://github.com/google/protobuf/blob/master/objectivec/ProtocolBuffers_OSX.xcodeproj/project.pbxproj#L814

**Comment by thomasvl** [comment]
Bo - As you point out, the project is set to iOS 7.1, but you made the podspec 8.0, why the difference?

**Comment by TeBoring** [comment]
I was going to change it to 7.1. Just waited for confirmation.

**Pull request merged**
