### PR TITLE
Add LICENSE in package.xml

### PR DESCRIPTION
**Pull request by TeBoring**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by xfxyjwf** [comment]
I have https://github.com/google/protobuf/pull/3074 already. Isn't this just a duplicate?

**Comment by xfxyjwf** [comment]
I merged the other PR. You can update this PR to add php specific release notes.

**Comment by TeBoring** [comment]
Kind of duplicate. Need to add a line for LICENSE

**Comment by xfxyjwf** [comment]
Can you rebase this PR?

**Pull request merged**
