### PR TITLE
Fixed issue #65 and #157

### PR DESCRIPTION
**Pull request by wolf34736**
commit 49dcfb7 is about issue #65 

commit a865679 is about issue #157

[Review on Reviewable](https://reviewable.io/reviews/google/protobuf/314)

### CODE REVIEW

**Comment by edgar-pek** [comment]
I've signed it. Sorry for the delay.

**Comment by xfxyjwf** [comment]
Hi @edgar-pek , this PR mixes quite a few different things together. Could you split it and send them separately?

**Comment by edgar-pek** [comment]
I've created a pull request #490 that fixes this issue.

**Comment by haberman** [comment]
I'm closing this PR since it superseded by your other PR(s).

**Pull request closed without merging**
