### PR TITLE
whitelisting aix platform as it has sched_yield

### PR DESCRIPTION
**Pull request by amandeepgautam**
As per discussion here:https://github.com/google/protobuf/issues/4101

### CODE REVIEW

**Comment by acozzette** [comment]
@amandeepgautam Thanks for the pull request. Have you signed the CLA at https://cla.developers.google.com/ yet?

**Comment by amandeepgautam** [comment]
@acozzette Just did.

**Comment by amandeepgautam** [comment]
logged out from a conflicting account and logged in with correct account. Hoping it will pass this time.

**Comment by acozzette** [comment]
@amandeepgautam Could you double-check that your commits have the same email address that you used to sign the CLA?

**Comment by amandeepgautam** [comment]
@acozzette Thanks. Yes that was the problem. I used the correct keys for github, but committed with incorrect email id.

**Comment by acozzette** [comment]
@amandeepgautam Thanks!

**Pull request merged**
