### PR TITLE
Fix string::back() usage in googletest.cc

### LINKED ISSUE #4075: string::back used (not supported on pre-C++11)
Ran into the following issue when trying to build `protobuf` 3.5.0 where `string::back` was used. The [`string::back` method only exists in C++11]( http://en.cppreference.com/w/cpp/string/basic_string/back ). Found [`back` used on this line]( https://github.com/google/protobuf/blob/9c197b7ecba6019b7c81c673cf100b2fad4033ad/src/google/protobuf/testing/googletest.cc#L135 ). Snippet of this error taken from [this log]( https://ci.appveyor.com/project/conda-forge/protobuf-feedstock/build/1.0.106/job/wlim812l64mbq5j3 ) shown below.

```
C:\bld\protobuf_1513724287833\work\protobuf-3.5.0\src\google\protobuf\testing\googletest.cc(135) : error C2039: 'back' : is not a member of 'std::basic_string<_Elem,_Traits,_Ax>'
        with
        [
            _Elem=char,
            _Traits=std::char_traits<char>,
            _Ax=std::allocator<char>
        ]
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
```

### PR DESCRIPTION
**Pull request by pherl**
Fixes #4075

### CODE REVIEW

**Comment by xfxyjwf** [comment]
@jakirkham Can you help test this PR on visual studio 2008?

**Comment by jakirkham** [comment]
Testing it in these [builds]( https://ci.appveyor.com/project/jakirkham/protobuf-feedstock/build/1.0.2 ). We only care about the first two for these purposes. If one of the two passes, the other almost assuredly will pass as they only differ by architecture (32-bit vs. 64-bit).

**Comment by pherl** [comment]
Looks like it's passing. Merging this PR.

**Comment by jakirkham** [comment]
Yep, was just about to say the same. Thanks for the patch.

**Pull request merged**
