### PR TITLE
Convert C# projects to Portable Class Libraries

### PR DESCRIPTION
**Pull request by jskeet**
This pull request should only be merged after pull request #317 - it's basically the successor to that.

### CODE REVIEW

**Comment by jskeet** [comment]
@jtattermusch to review.

**Comment by jtattermusch** [comment]
Now that #317 got merged, can you rebase this one so it doesn't contain stuff from #317 and I can see the actual changes? Thanks

**Comment by jskeet** [comment]
Aargh. Failed on the merge. Will abandon this branch and try again...

**Comment by jtattermusch** [comment]
Perhaps reset --hard one commit back and rebase -i upstream/csharp  and   push -f  would work?

**Comment by jskeet** [comment]
Maybe - will see what I can do. It's all very confusing.

**Comment by jskeet** [comment]
Done - back to just the commit I wanted (I think!)
Goodness knows what I've done to my xUnit branch, but we'll sort that out another day. This is ready for review now, thanks.

**Comment by jtattermusch** [comment]
LGTM.

**Pull request merged**
