### PR TITLE
Tidying up reflection further

### PR DESCRIPTION
**Pull request by jskeet**
This is in preparation for DynamicMessage (and possibly just Any support).

Will see whether our CI systems cope with the C# 6...

### CODE REVIEW

**Comment by gabikliot** [comment]
Would that mean that only C# 6 projects would be able to use the C# protobuf nugets (would they need to run on .NET 4.6)? That would hurt adoption, since C# 6 is pretty young and there are some stability issues with .NET 4.6 (it does not run on Azure yet) and as a result some projects delay moving to C# 6/.NET 4.6.

**Comment by jskeet** [comment]
No, it won't require C# 6 to run, or to build the generated code - it will only require C# 6 to build the Google.Protobuf library itself. All the features in C# 6 work with earlier versions of .NET, although the support for string interpolation changes a little bit depending on whether FormattableString is available.

**Comment by gabikliot** [comment]
Great, thanks.

**Comment by jskeet** [comment]
Merged with master, which has changed which C++ file was edited. Should all still be fine, but worth waiting for CI obviously.

**Comment by jtattermusch** [comment]
LGTM after fixing the nits.

**Comment by jskeet** [comment]
Thanks - merged with previous commit; repushing with changes and will merge when CI is happy.

**Comment by jskeet** [comment]
Java build fail appears to be unrelated to change. Merging.

**Pull request merged**
