### PR TITLE
Integrated internal changes from Google

### PR DESCRIPTION
**Pull request by acozzette**

### CODE REVIEW

**Comment by xfxyjwf** [comment]
LGTM

**Comment by acozzette** [comment]
@xfxyjwf I added a few more commits so do you want to take another look before I merge this? Now I believe all the tests should be passing. The CLA bot is confused but I think that shouldn't be a problem since and you and I are the only authors of commits in this pull request.

**Comment by xfxyjwf** [comment]
Thanks Adam. The changes all look good to me.

**Comment by acozzette** [comment]
Thanks, Feng! I'll merge this now then.

**Pull request merged**
