### PR TITLE
Changelog update for 3.0.2

### PR DESCRIPTION
**Pull request by pherl**

### CODE REVIEW

**Comment by pherl** [comment]
@thomasvl @jskeet @haberman

**Comment by jskeet** [comment]
legacy_enum_values was removed in 3.0.0 for C# - as is already documented. No need to mention it in 3.0.2.

**Comment by pherl** [comment]
I noticed that the PR wasn't really merged into the GA branch... Could you double check with the v3.0.0 tag?

**Comment by xfxyjwf** [comment]
LGTM

**Comment by jskeet** [comment]
The flag removal one? Ick. Will have a look tomorrow.

**Comment by thomasvl** [comment]
LGTM

**Comment by jskeet** [comment]
Yup, you're right. I guess the 3.0.0 release notes only say the flag isn't *supported*, so we can probably leave that... LGTM.

**Pull request merged**
