### PR TITLE
Fixing HHVM Compatibility

### PR DESCRIPTION
**Pull request by RyanGordon**
This is a followup to https://github.com/google/protobuf/pull/3225 after a small HHVM compatibility was introduced recently.

Adding HHVM tests will happen in a separate PR, tracked here: https://github.com/google/protobuf/pull/3343

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by TeBoring** [comment]
ok to test

**Comment by TeBoring** [comment]
Just let you know, we won't declare being compatible with hhvm in 3.4 release (although it actually is). Instead, we will wait until test is added.

**Comment by RyanGordon** [comment]
That works for me :+1:

**Comment by TeBoring** [comment]
Could you test 3.4.x to make sure it works for you?

**Comment by RyanGordon** [comment]
The latest master?

**Comment by TeBoring** [comment]
No, the 3.4.x branch, which we will have a release soon.

**Comment by RyanGordon** [comment]
Will do today :+1:

**Comment by RyanGordon** [comment]
Okay just checked out 3.4.x and did some basic testing on it. It works on HHVM and the PHP code changes look compatible to me :+1:

**Comment by TeBoring** [comment]
SG

**Pull request merged**
