### PR TITLE
Generated Code Changes for PHP

### PR DESCRIPTION
**Pull request by TeBoring**
1) Support array constructor
2) Use namespace instead of '_' for nested messages/enums.
3) Fixed the issue that reserved name in package or proto file path is not skipped.

### CODE REVIEW

**Comment by TeBoring** [comment]
All changes had been reviewed in php-generated-dev branch.

**Comment by acozzette** [comment]
Do we need these changes for the 3.6 release? If so then maybe we should merge them into the 3.6.x branch instead of master.

**Comment by TeBoring** [comment]
SGTM

**Comment by acozzette** [comment]
LGTM

**Pull request merged**
