### PR TITLE
Factored Conformance and Benchmark test messages into shared test schema.

### PR DESCRIPTION
**Pull request by haberman**

### CODE REVIEW

**Comment by haberman** [comment]
@jskeet could you take a look at what C# changes are required for this change?

**Comment by jskeet** [comment]
Hmm. The simplest approach for the conformance tests will be to make the conformance project reference the test project, which would contain this.

As this is all post-GA, I'm personally happy for you to commit this leaving the C# code broken, and raise an issue for me to fix it all up. Given my personal timeline that probably means it being broken until ~August 31st, but I think it'll be a lot less *work* time than trying to do it all in one go.

I may take this opportunity to add checks in the build scripts to make sure any changes to test protos (or descriptor protos) also rebuild the generated C# code (which is checked into git).

**Comment by haberman** [comment]
@jskeet, would you be able to fix this now? If I checked this in could you fix C# shortly thereafter?

**Comment by jskeet** [comment]
@haberman: If it's just a matter of regenerating the C# code, you could try doing it yourself - run `generate_protos.sh` in the `csharp` directory. (You may need to adjust it for where you've built `protoc`.) If that causes problems, I could certainly have a look - although I'm trying to reduce the amount of protobuf work I do.

**Comment by haberman** [comment]
@jskeet @jtattermusch I'm having trouble properly regenerating the C# protos for the conformance tests. Any chance I could get some help from one of you?

**Comment by jskeet** [comment]
This commit should be what you need:
https://github.com/jskeet/protobuf/commit/7f38b504990b089b19bb10de7d524fb5c4a8f2e9

You'll need to rerun the generator script afterwards, of course.

**Comment by haberman** [comment]
At long last, this PR is (I believe) green. @xfxyjwf want to take a look and LGTM?

**Comment by haberman** [comment]
Yikes, I spoke too soon. This passes on AppVeyor, but Jenkins is showing errors running the conformance tests: https://grpc-testing.appspot.com/job/protobuf_pull_request/711/testReport/(root)/csharp/csharp/

**Comment by haberman** [comment]
Ok I think it's really ready now! @xfxyjwf want to take a look?

**Comment by xfxyjwf** [comment]
LGTM

**Pull request merged**
