### PR TITLE
First steps to making the C# runtime work with new codegen

### PR DESCRIPTION
**Pull request by jskeet**
After committing, the runtime itself should build and tests should pass. The protogen library will no longer build; that is to be removed in the next set of commits.

The new generated files committed here are built with protoc.exe with the new codegen, but with a few modifications.

### CODE REVIEW

**Comment by jskeet** [comment]
@jtattermusch to review this - although it's primarily replacing generated code.

**Comment by jtattermusch** [comment]
Besides the minor comment, LGTM.

Maybe one thing: can you put a list of manual changes you've done into an initial comment in auto generated files?

**Comment by jskeet** [comment]
Sure - will rebuild, see what the differences are, and then add the comments into a new commit. I've added another commit on my local branch though, so it may involve some shenanigans...

**Comment by jskeet** [comment]
Added commit 5ca6dd76fb39d7f76297f6a2a95466bbc8d5b691 to indicate the manual changes. It looks like it's changing more because it was generated by running protoc with just `-I src` instead of `-I src\google\protobuf`; the new file is the more appropriate one.

**Comment by jskeet** [comment]
@anandolee This is now ready to merge if you're happy.

**Pull request merged**
