### PR TITLE
Added accessors for nested messages in Javanano

### PR DESCRIPTION
**Pull request by ennerf**
This adds accessors for nested messages so that references can be kept in order to reduce garbage. This addresses Issue #167. 

Note that this changes the default behavior and breaks backwards compatibility. How do you normally handle this? Would this go into a separate branch first?

### CODE REVIEW

**Comment by ennerf** [comment]
Do you think setMessage(null) should be allowed in case someone wants to explicitely remove the reference?

**Comment by telkomsel666** [comment]
#1

**Comment by xfxyjwf** [comment]
Does this PR change the generated API of message fields? Although proto3 is still alpha, this nano implementation (ported from AOSP) is already used by many people both inside and outside Google. We cannot change the API or it will break existing users.

**Comment by ennerf** [comment]
Yes it does change the API for nested messages generated with "accessors". I thought this is roughly what you had in mind in #167. 

Were you only referring to the clear() function?  If so, how would you decide whether or not to serialize a message? I can change the implementation if you could give me some guidance on what you'd like to see.

**Comment by xfxyjwf** [comment]
Sorry, I misunderstood what is already implemented. I was thinking accessors are already generated for message fields with optional_field_style=accessors. If that's not the case, making such a change will be API incompatible and we'll need to add another flag to make a smooth transition for old users. As there are already quite some flags in the nano implementation, we are still finalizing the plan about what flags to be kept, what flags to be removed and how we migrate existing users. Could you hold on this PR and wait until we have a finalized plan for all the nano options? Hopefully we can have something in the next month.

**Comment by ennerf** [comment]
Sure, just let me know whenever you decide on something. If you end up adding another flag for this, it'd probably be best to create accessors for all the other reference fields as well.

I think the current behavior of "optional_field_style=accessors" is a bit odd. It generates accessors for primitive and enum fields, but leaves reference and message fields to their defaults. This results in inconsistent syntax and prohibits welcome memory optimizations.

**Comment by acozzette** [comment]
I'm going to close this pull request because we no longer support the javanano implementation.

**Pull request closed without merging**
