### PR TITLE
Update .NET SDK to 2.0.3

### PR DESCRIPTION
**Pull request by jskeet**
This will allow SourceLink as per #4179, and mean that we can use C#
7.X language features in the library (but not in generated code).

This does not affect which platforms we're *targeting*, so end users
won't see any difference.

(Will assign a reviewer when CI is happy.)

### CODE REVIEW

**Comment by gentlejack** [comment]
Files changed.

**Comment by jskeet** [comment]
@gentlejack: I'm not sure what your comment is meant to indicate. Could you elaborate?

**Comment by jskeet** [comment]
It looks like Travis is stalled here - @anandolee, do you know anything about this?

**Comment by xfxyjwf** [comment]
@jskeet All travis tests should now be covered by corresponding kokoro test cases. For C#, I think it's the "Linux C#" one (which is passing for this PR). You can click the details link and there will be a sponge link you can view the test result:
https://sponge.corp.google.com/target?id=c5df01e1-3f4c-436e-8158-267952cbc0b0&target=protobuf%2Fgithub%2Fmaster%2Fubuntu%2Fcsharp%2Fpresubmit&searchFor=

The plan is to replace both jenkins/travis with kokoro eventually. Let me know if there is something covered by travis but not by kokoro,

**Comment by jskeet** [comment]
@xfxyjwf: Does kokoro use the `.travis.yml` file to work out what to install? If not, then a) I've probably missed something in this change, and b) we won't know whether Travis works without it running.

**Comment by xfxyjwf** [comment]
oh, sorry, I haven't checked the actual change in this PR and it seems you are changing the test environment settings. Kokoro doesn't use .travis.yml, instead it uses scripts in the kokoro directory. The one for csharp is:
https://github.com/google/protobuf/blob/master/kokoro/linux/csharp/build.sh

The setup is done in this file:
https://github.com/google/protobuf/blob/master/kokoro/linux/prepare_build_linux_rc

I guess you can try to change this file and check the kokoro result of "Linux C#". It should finish much faster than travis.

**Comment by jskeet** [comment]
Okay - will do that in the morning. I'd still like to see Travis pass or fail with this change though...

**Comment by jskeet** [comment]
Added another commit for the kokoro environment - although it was already green, which surprises me. It's possible that something else was already installing .NET Core SDK 2.0, although that seems a tad unlikely.

**Comment by jskeet** [comment]
Hmm... and the C++ tests *still* haven't started.

Do you think we're safe to merge this change? I suspect so, but I wouldn't want to go ahead without double checking.

**Comment by xfxyjwf** [comment]
I think it's fine to merge as long as other tests are passing. Travis is too slow and I usually merge without it nowadays.

**Comment by jskeet** [comment]
Thanks - done!

**Pull request merged**
