### PR TITLE
Merge ruby fix repeated message field to development branch

### PR DESCRIPTION
**Pull request by rxbynerd**
https://github.com/google/protobuf/pull/2519 landed on master in November 2017, but hasn't been queued for release.

Opening a new PR to the 3.5.x development branch to try and bump this along - the original PR is from December 2016 😥 

cc @haberman and @TeBoring from the original pull request

### CODE REVIEW

**Comment by rxbynerd** [comment]
@haberman @TeBoring @xfxyjwf @pherl _PLEASE_ can I get some movement on this? It's been a year and half.

**Comment by TeBoring** [comment]
Sorry for the delay. Could you send PR to master?

**Comment by rxbynerd** [comment]
@TeBoring [the original PR](https://github.com/google/protobuf/pull/2519) (from December 2016) was to master, but master isn't actually released, this branch is - the code has been in master since https://github.com/google/protobuf/pull/2519 was merged, but it hasn't been released, as nobody merged master into 3.5.x

**Comment by TeBoring** [comment]
We will have 3.6 release soon. Still need this?

**Comment by rxbynerd** [comment]
@TeBoring what's the timeframe for 3.6? if it's two weeks, fine, it's another drop in the ocean, if it's 1+ month, yes, I would prefer a new 3.5.x release with this bug fix in - I would _really_ love to move on this project I've been delaying since the original PR

**Comment by TeBoring** [comment]
About two weeks.

**Comment by TeBoring** [comment]
Close this for now since we will have 3.6 release soon.

**Comment by rxbynerd** [comment]
Okay - please can we get an update to the contribution guidelines to this repo?

This two-step merge situation wasn't detailed, so the original PR was delayed heavily in terms of getting out the door.

**Comment by TeBoring** [comment]
Changes into master will only be release in the next major release. If it's bug fix, we can merge it to a released branch.

**Pull request closed without merging**
