### PR TITLE
Straddle Python 2.6, 2.7, 3.3, and 3.4

### PR DESCRIPTION
**Pull request by tseaver**
Uses #161, #162, #163, #164, and #165 as diff base.

Tests for all four supported Python versions run under tox, without the need for `2to3`.

### CODE REVIEW

**Comment by pherl** [comment]
@haberman

**Comment by haberman** [comment]
Hi Tres,

Thanks a lot for doing all this work. I inherited maintenance of the protobuf-Python code at Google several months ago, and these changes represent a lot of the direction we want to move in (better Python 3 support, dropping google-apputils dependency, improving setup.py and integration with standard Python packaging).

Unfortunately -- and I'm really sorry about this -- I think there are some problems that will prevent us from being able to merge these changes right now:

1. I think there was an miscommunication earlier when https://github.com/google/protobuf/pull/143 was merged. We are unfortunately not at liberty to drop Python 2.5 support at this time, because Google AppEngine is committed to supporting Python 2.5 until at least next month, and possibly longer. We may want to drop official 2.5 support for open-source users, but as we use one single code-base for both open-source and internal use (such as AppEngine), we unfortunately must keep the source Python 2.5-compatible for the time being. I'll make this more clear in the Python README.

2. As far as dropping google-apputils as a dependency (and using unittest) instead: in the internal branch of python Protobuf, the code has started using a feature that doesn't seem to exist in `unittest`: the ability to parameterize a test, ie. run a whole suite multiple times while varying one parameter. Sample code looks like this:

```python
@parameterized.Parameters(
    (unittest_pb2),
    (unittest_proto3_arena_pb2))
class MessageTest(googletest.TestCase):

  def testExtremeFloatValues(self, message_module):
    message = message_module.TestAllTypes()
    # etc.
```

I will merge our internal changes back to GitHub as soon as I can, though it might be a couple weeks. Hopefully at that point we can find a way to merge with your changes.

Thanks,
Josh

**Comment by haberman** [comment]
Wanted to ping this PR -- we're now free to drop Python 2.5 compat! Don't know if you saw.

If you're willing to bring this PR up to date, I'm really interested in merging Python 3 support now that we don't need 2.5.

**Comment by tseaver** [comment]
@haberman ATM, my itch is scratched by 3.0.0a1, which supports Python 2.6, 2.7, and 3.4.  I still believe that straddling is superior to '2to3', but don't have cycles to update this patch.

**Comment by Kentzo** [comment]
@haberman What work is required to bring that PR up to date? Do you have some tasks in mind?

**Comment by haberman** [comment]
The PR currently doesn't merge cleanly, because it's fallen out of date with the tree. Bringing it up to date so it merges cleanly (and the tests pass) would be a good start.

**Comment by jleclanche** [comment]
Commits e17f78b and 58dbea9 can be dropped entirely. There's more conflicts further down...

**Pull request merged**
