### PR TITLE
include java_doc_comment.h in distribution

### LINKED ISSUE #1435: Include Javadoc methods in distribution
For now, grpc will have to copy & paste the javadoc code from the protobuf compiler. Ideally it should just be using the same methods to generate its service documentation.

I have a PR on the way ...

### PR DESCRIPTION
**Pull request by nmittler**
Fixes #1435

### CODE REVIEW

**Comment by nmittler** [comment]
@xfxyjwf PTAL

**Comment by nmittler** [comment]
FYI I've also done some minor refactoring to expose a simple `WriteDocComment` method that will be used by grpc when it's available.

**Comment by xfxyjwf** [comment]
@pherl to review since Jisi is working on the next release.

**Comment by haberman** [comment]
Ping @pherl?

Nathan I think the PR needs some conflicts to be resolved.

**Comment by nmittler** [comment]
@haberman rebased onto the latest master branch

@pherl PTAL ... this should be an easy one.

**Comment by pherl** [comment]
The file location is internal (in google) and thus missing export macros for windows platforms. The file needs to be moved to the public header directory internally. Also, if we public the API, the API needs to be minimum and stable. I would select a few underlying functions to be public so users would easy to construct doc comments on their own, without adding options to the API to control different style. That said, I think it's easier to create another header just listing underlying functions.

**Comment by nmittler** [comment]
@pherl

> I would select a few underlying functions to be public so users would easy to construct doc comments on their own, without adding options to the API to control different style. That said, I think it's easier to create another header just listing underlying functions.

The file doesn't have that much in it, really.  It should be fine to make public as-is.

**Comment by pherl** [comment]
Please make the change internal, by creating another file in the public folder and only expose underlying functions. In this case, the surrounding by pre tag option should be avoided. We could simply produce something a block of comments body, and let the call site add /** and */.

**Comment by carl-mastrangelo** [comment]
ping, is there anything more to do here?

**Comment by nmittler** [comment]
@carl-mastrangelo Yes, see https://github.com/google/protobuf/pull/1436#issuecomment-216652662

**Comment by TeBoring** [comment]
obsolete

**Pull request closed without merging**
