### PR TITLE
Fix podspec by adding missing comma

### PR DESCRIPTION
**Pull request by jcanizales**
@TeBoring to review.

@nicolasnoble: This is the change I told you that Beta gRPC needs.

### CODE REVIEW

**Comment by jcanizales** [comment]
Bo, do you want me to send the change to a branch besides master?

**Comment by TeBoring** [comment]
Has this blocked the release of grpc?

**Comment by jcanizales** [comment]
It breaks the compile of protobuf using the podspec (because it makes the `Wrappers.pbobjc.h` and `.m` files to be ignored). We need it for our beta (0.11) release.

**Comment by TeBoring** [comment]
Could you merge it to the beta-1 branch?

**Comment by jcanizales** [comment]
Sure

**Comment by TeBoring** [comment]
I created v3.0.0-alpha-4.1 branch with your change. Could you check it works?

**Pull request merged**
