### PR TITLE
Build scripts to publish precompiled protoc binaries

### PR DESCRIPTION
**Pull request by zhangkun83**
It will upload precompiled protoc binaries with the name ``protoc-<version>-<os>-<arch>.exe``, which can be consumed by upcoming Gradle/Maven plugins for protobuf.
@pherl : please take a look.

### CODE REVIEW

**Comment by zhangkun83** [comment]
@pherl I have created a README.
@ejona86 please also take a look

**Comment by ejona86** [comment]
It seems like it may not be _too_ hard to convert this to Maven. Maven would seem to make more sense to me because they are already using Maven for protobuf-java.

**Comment by zhangkun83** [comment]
It may not be too hard, but I am not sure whether it's trivial. With the Gradle wrapper the user would not need to install extra software, and the wrapper adds about 70KB to the source tree. I wonder if we need to produce protoc artifacts for other repositories/languages, which would be easier to implement in Gradle than in Maven.

**Comment by ejona86** [comment]
I'm more concerned about it being _another_ technology in the tree and _another_ step to distribute artifacts. Right now, Maven is already in use and used with Sonatype for distribution (including signing). With using Gradle, that means both have to be properly set up, which seems like a maintenance burden.

**Comment by zhangkun83** [comment]
Fair enough. I will switch it to Maven. I will do it in the existing protobuf/java directory. Does sound good to you?

**Comment by ejona86** [comment]
I think doing the work in protobuf/java will force the name of the binary to be a bit strange (e.g., protobuf-java-binary.exe). But it would be "good enough" for me.

**Comment by zhangkun83** [comment]
Maven-based solution is #268
Closing this PR.

**Pull request closed without merging**
