### PR TITLE
Removes ignored const from return type

### PR DESCRIPTION
**Pull request by Jdavid1001**
See https://github.com/google/protobuf/issues/2425

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by xfxyjwf** [comment]
ok to test

**Comment by Jdavid1001** [comment]
@xfxyjwf I've joined Google now. Does that make it fine?

**Comment by xfxyjwf** [comment]
Can you reply as instructed by the google bot? 
```
Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.
```

**Comment by Jdavid1001** [comment]
I signed it!

**Comment by xfxyjwf** [comment]
@Jdavid1001 The signcla checker still reports you haven't signed Google CLA.

**Comment by Jdavid1001** [comment]
Had to recommit with my @google.com email. Please let me know if there are any other concerns.

**Comment by xfxyjwf** [comment]
Thanks!

**Pull request merged**
