### PR TITLE
Needed on Solaris for PATH_MAX

### PR DESCRIPTION
**Pull request by dago**
This include is needed on Solaris or `PATH_MAX` will be reported as undefined. Please see the full build log at
  https://buildfarm.opencsw.org/buildbot/builders/protobuf-solaris10-i386/builds/359/steps/shell_2/logs/stdio

Current build status on Solaris is available at
  https://buildfarm.opencsw.org/buildbot/waterfall?category=protobuf

### CODE REVIEW

**Comment by dago** [comment]
I signed it!

**Comment by dago** [comment]
Checking for `limits.h` is safer as there is also Solaris on x86 which fails to match the original conditional.

**Comment by dago** [comment]
Essentially yes, but as there was a test in configure I thought it may be best to use the result of the check. I wouldn't mind an unconditional include instead of the shielded one.

**Comment by xfxyjwf** [comment]
Let's remove the #ifdef/#endif check then. It's unnecessary complication to the code.

**Comment by xfxyjwf** [comment]
Looks good. Could you squash the commits into one?

**Comment by dago** [comment]
I created another pull request in my attempt to boil down my commits, please apply pull request #1758 and close this one. Thanks!

**Comment by haberman** [comment]
Closing as requested.

**Pull request closed without merging**
