### PR TITLE
Add go_package to field_mask.proto.

### LINKED ISSUE #2057: file_mask.proto is missing a go_package
https://github.com/google/protobuf/blob/master/src/google/protobuf/field_mask.proto

This file probably needs

```
option go_package = "github.com/golang/protobuf/ptypes/fieldmask";
```

I have filed https://github.com/golang/protobuf/issues/226 to track including it in the Go protobuf package.

### PR DESCRIPTION
**Pull request by tswast**
Fixes #2057.

### CODE REVIEW

**Comment by xfxyjwf** [comment]
Can you ask someone from golang/protobuf to LGTM it? I can help merge the change after that.

**Comment by tswast** [comment]
@zombiezen Could you take a look? I have updated this based on your comment here: https://github.com/golang/protobuf/pull/227

@broady I think we should regenerate https://github.com/google/go-genproto Would this change affect the current script used?

**Comment by tswast** [comment]
Ping. Sorry I lost track of this.

**Comment by broady** [comment]
LGTM, but I think the canonical location for these proto files is in the internal Google repo.

Ross? @zombiezen

**Comment by zombiezen** [comment]
@pongad, can you take a look at this?

**Comment by pongad** [comment]
I have already made a similar change in the internal Google repo.
The difference is that the option is
`option go_package = "google.golang.org/genproto/protobuf/field_mask;field_mask";`
so that the package structure is similar to the one we have inside Google.

Currently, I'm waiting for another CL for `descriptor.proto` to land. Once that lands, I'll work on copying those change en masse to this repo.
go-genproto's regen.sh might have to be updated to read go_package option to get the new package structure though.

**Comment by pongad** [comment]
This change has already landed. Should we close this?

**Comment by tswast** [comment]
Thanks @pongad

**Comment by tswast** [comment]
@broady Can you update genproto?

**Pull request closed without merging**
