### PR TITLE
Fix missing std::tr1::hash on GCC 4.1

### PR DESCRIPTION
**Pull request by matthauck**
Rather than crashing on use (doh!) better to just declare this platform
is missing a proper hash_map/hash_set implementation and use
the std::map/std::set emulation.

Fixes regression introduced by #1913

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by xfxyjwf** [comment]
Closing as this seems a duplicate of https://github.com/google/protobuf/pull/2906

**Comment by matthauck** [comment]
Yes, this was an intentional duplicate (see comment on #1913). I wasn't sure which implementation would be preferred.

**Comment by xfxyjwf** [comment]
I see. I actually prefer the fallback to <map> <set> approach in this PR. The other PR casts int64 to size_t for hash and that is too week a hash function that invites hash flooding for 32bit systems where size_t is only 32bit.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by xfxyjwf** [comment]
ok to test

**Comment by matthauck** [comment]
looks like there are conflicts here now. :cry:

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by matthauck** [comment]
ok. updated with master. Is there anything left pending on this PR to pull this in?

**Comment by matthauck** [comment]
_ping_.

**Pull request merged**
