### PR TITLE
Merge C# proto3 from csharp-experimental to master

### PR DESCRIPTION
**Pull request by jtattermusch**
I think we are now in a good shape to merge C# proto3 back into master. Most of the proto3 functionality has been implemented and we addressed the cleanup we wanted:

C# cleanup tasks:
https://github.com/google/protobuf/issues?q=is%3Aissue+milestone%3A%22C%23+code+cleanup%22+is%3Aclosed

### CODE REVIEW

**Comment by jtattermusch** [comment]
@anandolee @pherl @xfxyjwf   for review.

@jskeet FYI

CLA is fine, all code written by googlers.

**Comment by pherl** [comment]
Please wait for the API review before merging.

**Comment by jtattermusch** [comment]
@anandolee @pherl  I think we can proceed with this PR now (please see my e-mail).

**Comment by jtattermusch** [comment]
@anandolee @pherl Freezing has been removed in #654 and #659. Once Travis becomes green, this should be ready to merge.

**Comment by jtattermusch** [comment]
Travis is green with the exception of jruby test, which I don't believe is related to this PR, because it was definitely passing before we passing in the past and the most recent PRs couldn't have really caused it.

**Comment by anandolee** [comment]
All the code in charp experimental are reviewed previously. 
LGTM

**Comment by pherl** [comment]
Could you please double check the CLA tag?

**Comment by jtattermusch** [comment]
CLA is red because googlebot doesn't correctly handle situations where the autor field of the commit is not the same as the commiter field. That happens when you are merging branch that contains commits from multiple contributors. I've doublechecked that all the commits in this PR are from Jon, Jie or me.

**Comment by pherl** [comment]
LGTM

**Comment by jtattermusch** [comment]
Wohoo!

**Pull request merged**
