### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by ottok**
Non-functional spelling fixes patch that should be easy to apply.

### CODE REVIEW

**Comment by ottok** [comment]
CLA: I signed it!

**Comment by ottok** [comment]
I checked the failing Travis-CI tests. They don't seem to have anything to do with the changes in this PR. Looking at https://travis-ci.org/google/protobuf/builds it seems that current master branch has a lot errors anyway, and looking at all recent PRs they all fail, so the Travis-CI situation is most likely generic and does not apply just for this PR.

```
[14:04:20] Error: Command failed: testbinary.proto:188:10: Option "(jspb.generate_from_object)" unknown.
proto3_test.proto: Import "testbinary.proto" was not found or had errors.
proto3_test.proto:54:3: "ForeignMessage" is not defined.
proto3_test.proto:73:12: "ForeignMessage" is not defined.

test_map_basic(BasicTest::MessageContainerTest) [/home/travis/build/google/protobuf/ruby/tests/basic.rb:471]:
Failed assertion, no message given.

py27-cpp runtests: commands[1] | python setup.py -q build --cpp_implementation --warnings_as_errors
google/protobuf/pyext/message.cc:2825:19: error: unused variable 'module_docstring' [-Werror,-Wunused-const-variable]
static const char module_docstring[] =
                  ^

test_map_basic(BasicTest::MessageContainerTest)
/Users/travis/build/google/protobuf/ruby/tests/basic.rb:485:in `test_map_basic'
     482:       # We only assert on inspect value when there is one map entry because the
     483:       # order in which elements appear is unspecified (depends on the internal
     484:       # hash function). We don't want a brittle test.
  => 485:       assert m.inspect == "{\"jkl;\"=>42}"
     486: 
     487:       assert m.keys == ["jkl;"]
     488:       assert m.values == [42]
```

**Comment by xfxyjwf** [comment]
@ottok Could you check the CLA again? I couldn't find a CLA signed by you (github name) nor by Seravo Oy.

**Comment by ottok** [comment]
Please check now again.
Otto Kekäläinen / Seravo

**Comment by xfxyjwf** [comment]
This PR appears to cause the jruby tests to fail (the javascript failure is caused by some other issue). I am rerunning the test.

**Comment by xfxyjwf** [comment]
The test passed after rerunning. Probably a flaky test case.

**Pull request merged**
