### PR TITLE
[C#] Update test project to be used with dotnet test and Visual Studio Test Explorer

### PR DESCRIPTION
**Pull request by ObsidianMinor**
This PR updates NUnit to 3.9.0, adds the NUnit3TestAdapter and Microsoft.NET.Test.Sdk packages, removes the bootstrap Program.cs, and updates the test command in buildall.sh and AppVeyor.bat from dotnet run to dotnet test.

### CODE REVIEW

**Comment by ObsidianMinor** [comment]
I signed it!

**Comment by ObsidianMinor** [comment]
Could this be reviewed @xfxyjwf?

**Comment by ObsidianMinor** [comment]
Could this be reviewed @anandolee?

**Comment by xfxyjwf** [comment]
This looks like a pure testing config change. I'll merge it when the linux C# test passes.

**Comment by JohnHBrock** [comment]
@ObsidianMinor Could you also update the Testing section of the README in /csharp?

**Comment by ObsidianMinor** [comment]
Updated the README @JohnHBrock

**Comment by xfxyjwf** [comment]
Great, thanks!

**Pull request merged**
