### PR TITLE
Need to expose generated protobuf C++ headers

### PR DESCRIPTION
**Pull request by abergmeier-dsfishlabs**
… so they can actually be accessed from other libraries.

### CODE REVIEW

**Comment by smr277** [comment]
How would you use this with, say, a cc_library? Would you just include it in deps as ":<proto_library>"?

**Comment by abergmeier-dsfishlabs** [comment]
We signed it!

**Comment by xfxyjwf** [comment]
@abergmeier You probably need to make another pull request using that account that signed the CLA?

**Comment by abergmeier-dsfishlabs** [comment]
On the bazel repo it was only necessary to run the cla-bot again...

**Comment by abergmeier-dsfishlabs** [comment]
@davidzchen So are you tracking this manually then?

**Comment by abergmeier-dsfishlabs** [comment]
Anyone looking at that?

**Comment by xfxyjwf** [comment]
LG. Thanks!

**Comment by abergmeier-dsfishlabs** [comment]
@davidzchen ping

**Comment by carloAI2** [comment]
For others who are trying to integrate C++ protobufs using Bazel into their own projects. I was able to invoke protobuf's protobuf.bzl file with the following recipe:

Under `WORKSPACE` add protobuf repo:
```
new_local_repository(
    name = "protobuf",
    build_file = "third_party/protobuf/BUILD",
    path = "third_party/protobuf"
)
```

Under your BUILD bazel file in your local project:
```
load("@protobuf//:protobuf.bzl", "cc_proto_library")
cc_proto_library(
  name = "my_proto",
  srcs = ["my.proto"],
  default_runtime = "@protobuf//:protobuf",
  protoc = "@protobuf//:protoc",
  visibility = ["//visibility:public"],
)
```

Then, in the command line, simply do: ```bazel build :my_proto```

... and Bazel will automatically generate the file. When including headers, make sure to include relative to where the WORKSPACE file is located. For me, to access the autogenerated protobuf files, I did:

```#include "lib/my_proto.pb.h"```

**Pull request merged**
