### PR TITLE
ObjectiveC: make file name same as class name when objc_class_prefix is set

### PR DESCRIPTION
**Pull request by axxapy**
There is no technical limitation but in general classes names and file names supposed to be the same in ObjC.

There is at least one case when it does not work without this fix:
if there are messages with same names but in different packages, you can not put generated .h files into framework since it has plain file structure (no directories) for headers. So each file must have unique name.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by axxapy** [comment]
I signed it!

**Comment by thomasvl** [comment]
There are plenty of cases where .proto files have multiple classes in them and the file name is about the collection, not any specific message within it.  This would also be a breaking change as developers would have to do a lot of source updates to \#import the new headers, not to mention all the Xcode project files updates it would trigger.

If we did anything to change the names of the generated files, I'd likely suggest we revisit #864.  The mangling we do is a historical thing from what was done internally at Google, but as that issue points out, it makes integration into other build systems much more difficult.

**Comment by thomasvl** [comment]
Also, the current transform does make automated builds hard, but atleast it can be done since the output name is only dependent on the input name.  Using the prefix would mean an automated build system has to be able to parse/extract from the file the prefix to figure out what the output name is.

**Comment by axxapy** [comment]
Well, collisions are possible anyway
For instance, when there are two messages one with name "Boo" and objc prefix "Foo" and another with name "FooBoo" - in this case we will have two different files with same classes names.

According concern that it will force a lot of developers to redo their imports I totally agree.

What would you say if I add special option for enabling this behavior? By default it will be switched off.

**Comment by thomasvl** [comment]
> Well, collisions are possible anyway
> For instance, when there are two messages one with name "Boo" and objc prefix "Foo" and another with name "FooBoo" - in this case we will have two different files with same classes names.

Sorry, not sure I'm following since I didn't bring up anything about collisions.  Yes, there could be class name collisions and/or file name collisions.  I'm not sure that what is being suggested here really changes that fact, it just introduces _another way_ file collisions could happen.  If anything, that could be an argument for not adding this as it is another way for filename collisions to happen.

> What would you say if I add special option for enabling this behavior? By default it will be switched off.

The catch with something like this is making it work as things chain.  For example, the `#import` directives to include the Well Know Types wouldn't use the prefix since that's how the files are distributed with this library.  This then ripples, if a developer makes a framework that exposes some protos, they will include the headers in their framework.  If a second developer then uses that framework and protos in their own, they need the imports to match the naming style used in the framework.  Trying to let each developer pick something can quickly ballon into something like [generator option `named_framework_to_proto_path_mappings_path`](https://github.com/google/protobuf/tree/master/objectivec#objective-c-generator-protoc-options), which I believe still isn't complete because of the issues raised in #1814.

**Comment by axxapy** [comment]
Fair enough.

Still problem with framework imports exists:
lets say we have two proto messages:

    package.request.Signin
    package.response.Signin

They will be compiled to

    ./package/request/Signin.pbobjc.h
    ./package/request/Signin.pbobjc.m
    ./package/response/Signin.pbobjc.h
    ./package/response/Signin.pbobjc.m

which is totally fine until you put them into framework: xcode simply can not import both at the same time because it has plain file structure for frameworks which causes filename collision.

To make it work you have to have unique message names across all protobuf structure which seems very strange requirement.

One way to solve this problem is to add prefix to filename (implemented in this pull request).
But may be there is another already existent solution I don't see?

**Comment by thomasvl** [comment]
While not common, you can actually use sub directories within Frameworks for headers.  Cocoapods exposes this with their podspec setting `header_mappings_dir`.

**Comment by thomasvl** [comment]
Another option (and likely more complete, but not perfect) to deal with collisions would be to support using the path to generate the file names.  So _foo/bar/baz.proto_ would generate _foo\_bar\_baz.pbobjc.h_ and _foo\_bar\_baz.pbobjc.m_.

I'm still a little worried adding any options can cascade into making things harder to integrate.

**Pull request closed without merging**
