### PR TITLE
control repeated_field memory increase on mobile platform

### PR DESCRIPTION
**Pull request by afpro**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by afpro** [comment]
I signed it!

**Comment by xfxyjwf** [comment]
@afpro Can you explain what this PR is trying to improve? My understanding is that this only helps when the repeated size is between 1M and 2M. For smaller sizes it doesn't help, and for larger sizes it makes the performance worse.

**Comment by afpro** [comment]
i'm using tensorflow with DT_HALF dtype, this dtype use int32 for 16 bit data.
while parsing proto file, repeated field size is indeterminate.
if it's size is 256+1, it will keep 512 elements memory.
my model is about 80mb, after loaded in memory, use 137mb memory, that's not right.
(RepeatedField don't have a strip method)

**Comment by afpro** [comment]
CI already fucked me up, oops.
i'll close this pr, try it on my own project first.

**Pull request closed without merging**
