### PR TITLE
[PROTOBUF-3404] add --with-zlib=PATH to configure.ac script

### PR DESCRIPTION
**Pull request by xiaoshuang-lu**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by xiaoshuang-lu** [comment]
duplicates #3404

**Comment by pherl** [comment]
ok to test

**Comment by xiaoshuang-lu** [comment]
Hi @pherl, this patch looks fine?

**Comment by xiaoshuang-lu** [comment]
Thanks, @pherl. So merge to master branch?

**Pull request merged**
