### PR TITLE
Fix Podspec version number

### PR DESCRIPTION
**Pull request by jcanizales**
This was released as `3.0.0-alpha-4.1`

### CODE REVIEW

**Comment by jcanizales** [comment]
@TeBoring

**Comment by TeBoring** [comment]
It's ok to leave it there. I am going to update the version number of all languages to 3.0.0-alpha5-pre/3.0.0-beta-2-pre.

**Comment by jcanizales** [comment]
If that's going to happen soon, sure. Otherwise it breaks local development, in which your dependency says `~> 3.0.0-alpha-4.1` but the local protobuf podspec can't satisfy that requirement.

**Comment by TeBoring** [comment]
I have doubt why local development environment depends on the version
number in HEAD. Does it mean we cannot change version number?

**Comment by jcanizales** [comment]
There are two use cases for telling Cocoapods to use a podspec from a local directory instead of downloading it from GitHub:
* You want to be able and make changes to that codebase (e.g. to test or fix the podspec file), so you have the protobuf repo cloned.
* You're using a submodule (like gRPC).

In those cases, if a library requires `Protobuf ~> 3.0.0-alpha-4.1` (which works when the podspec is downloaded from Cocoapods), the local podspec won't fulfill that requirement because it declares its version to be `3.0.0-alpha-4`, a previous one. The problem isn't that you can't change the version number in HEAD, rather the opposite, that you didn't.

**Comment by jcanizales** [comment]
To be clear, anything after `3.0.0-alpha-4` is fine (even unreleased versions), including any beta version.

**Comment by TeBoring** [comment]
Is merging alpha-4.1 branch into master ok?

**Pull request merged**
