### PR TITLE
Issue 3112: Object class with fully qualified name

### PR DESCRIPTION
**Pull request by lundefugl**
#3112: It workes in our use case  with this changes.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by lundefugl** [comment]
I signed it!

**Pull request merged**
