### PR TITLE
Add missing csharp_doc_comment.cc to protoc_lib.

### PR DESCRIPTION
**Pull request by mzhaom**
Fix bazel build

### CODE REVIEW

**Comment by pherl** [comment]
Thanks for the PR. Could you run the update file list script from the root directory and see if the file is missed in other places?

**Comment by mzhaom** [comment]
In addition to change to BUILD file, ./update_file_lists.sh also produced change to cmake/extract_includes.bat.in, but the output doesn't look right to me, for example:

+copy ${PROTOBUF_SOURCE_WIN32_PATH}\..\src\google\protobuf^Gny.h include\google\protobufny.h

I have no idea where ^G came from.

Is this a known issue?

**Comment by mzhaom** [comment]
All right, after switching to bash to run this script, the diff shown in this PR is the only change.

**Comment by pherl** [comment]
LGTM

**Pull request merged**
