### PR TITLE
Fix C# nuget build on Kokoro

### PR DESCRIPTION
**Pull request by jtattermusch**

### CODE REVIEW

**Comment by jtattermusch** [comment]
After fixing build_nuget.bat, we are still hitting:
```
**T:\src\github\protobuf\csharp>dotnet restore src/Google.Protobuf.sln 
The specified SDK version [2.0.3] from global.json [T:\src\github\protobuf\csharp\global.json] not found; install specified SDK version

Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 

  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
**
```
sponge/776524c4-dea0-4c2c-830b-0ab907b490f3

**Comment by jtattermusch** [comment]
With the global.json hack I got a successful build of Google.Protobuf.3.6.0.nupkg

https://sponge.corp.google.com/target?id=df15955f-da72-4907-847d-26bdc206680f&target=protobuf%2Fgithub%2Fmaster%2Frelease%2Fcsharp%2Fwindows%2Frelease&searchFor=

**Comment by jtattermusch** [comment]
CC @jskeet  in case you have opinions.

**Comment by jtattermusch** [comment]
I upgraded global.json to 2.1.3  along with updating the install script in `prepare_build_linux_rc`. Everything should work now.

@anandolee  please review.

**Comment by jtattermusch** [comment]
@anandolee  @xfxyjwf  friendly ping - can we review and merge this?

**Comment by mkosieradzki** [comment]
@jtattermusch @jskeet I needed to bump sdk version to 2.1.300 in global JSON to get it working with .NET Core 2.1 on appveyor: like in this example https://docs.microsoft.com/en-us/dotnet/core/tools/global-json

**Pull request merged**
