### PR TITLE
WIP: support PHP namespace option

### PR DESCRIPTION
**Pull request by michaelbausor**
This is a WIP PR to support the (currently not existing) php_namespace proto option.

cc @TeBoring @bshaffer

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by TeBoring** [comment]
duplicate of #3162

**Pull request closed without merging**
