### PR TITLE
CMake prerelease versioning

### LINKED ISSUE #1579: CMake users cannot differentiate between prerelease versions
The Tweak version or some other option to differentiate would be extremely helpful for people requiring exact builds. Right now users with beta-2 and beta-3 on their computer don't have a good way of picking between them.

### PR DESCRIPTION
**Pull request by yeswalrus**
Allows CMake users to differentiate between prerelease builds and pick between them successfully.
Requires exact version number matches for prerelease builds.

E.x. To use protobuf 3.0.0-beta-3:
```
set(protobuf_FIND_VERSION_PRERELEASE beta-3)
find_package(protobuf 3.0.0 EXACT)
```

Fixes #1579

### CODE REVIEW

**Comment by yeswalrus** [comment]
@podsvirov @xfxyjwf Any comments? Is there any way this could be merged before we finish with all this business with the examples?

**Comment by podsvirov** [comment]
I have no objections. There is an incident - it is necessary to users.

**Comment by yeswalrus** [comment]
@xfxyjwf The examples are in! if there are no objections, can we merge this one?

**Comment by xfxyjwf** [comment]
Merged. Thanks very much for the help!

**Comment by yeswalrus** [comment]
My pleasure - Next up, cross compiling support and I'll be satisfied

**Comment by yeswalrus** [comment]
@podsvirov Thank you as well!

**Comment by podsvirov** [comment]
@yeswalrus, do not mention it. Thank you google for opening such a good tool.

**Pull request merged**
