### PR TITLE
Merge 3.2.x to master

### PR DESCRIPTION
**Pull request by TeBoring**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by TeBoring** [comment]
@xfxyjwf to review.

**Comment by xfxyjwf** [comment]
What is this? I thought 3.2.x was merged into master months ago.

**Comment by TeBoring** [comment]
There were some new changes in 3.2.x after the previous merge.

**Comment by TeBoring** [comment]
I can also cherry-pick these changes if you want.

**Comment by xfxyjwf** [comment]
Why does this pull request start with commits back to last Dec? Shouldn't it only contain the commits after the last merge?

**Comment by TeBoring** [comment]
There were some changes from master cherry-picked. Perhaps the git cannot figure it out.

**Comment by xfxyjwf** [comment]
Please rebase the branch against master. As it currently stands, this PR is going to mess up with our commit history so much that I would not merge it like this.

**Comment by TeBoring** [comment]
Done

**Pull request merged**
