### PR TITLE
remove pass by reference for php setters

### PR DESCRIPTION
**Pull request by bshaffer**
See #3339 and #3300

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by TeBoring** [comment]
ok to test

**Comment by TeBoring** [comment]
Seems that there's a memory leak test failure in php7.0. You can comment out that test for now. I'll fix that in a subsequent PR.

**Comment by bshaffer** [comment]
@TeBoring ok done

**Pull request merged**
