### PR TITLE
Add C++ Cocoapods support

### PR DESCRIPTION
**Pull request by codingrhythm**
This PR adds C++ support for Cocoapods.

### CODE REVIEW

**Comment by codingrhythm** [comment]
I signed it!

**Comment by TeBoring** [comment]
Could you explain more about why we need to support this support? Doesn't current ```./autogen.sh && ./configure && make``` work? Or shall we use homebrew?

**Comment by codingrhythm** [comment]
@TeBoring thanks for your response. So one stupid question here, how can I use `./autogen.sh && ./configure && make` to build binary for mobile platforms (e.g. fat binary for iOS). I am new to this build system.

**Comment by TeBoring** [comment]
http://blog.omega-prime.co.uk/2011/03/08/how-to-build-3264-bit-fat-universal-binaries/
You could define ```CXXFLAGS="-arch i386 -arch x86_64" CFLAGS="-arch i386 -arch x86_64" LDFLAGS="-arch i386 -arch x86_64"```

**Comment by codingrhythm** [comment]
@TeBoring Thanks. This PR is not longer valid then.

**Pull request closed without merging**
