### PR TITLE
Add static MyMessage.parser().

### PR DESCRIPTION
**Pull request by pherl**
In preparation of deprecating the PARSER public instance.

Change-Id: I3e332d83bc4b4f8467769f8e45c758978ace8f21

### CODE REVIEW

**Comment by pherl** [comment]
@zhangkun83

**Comment by zhangkun83** [comment]
Also update the version number in pom.xml?

**Comment by zhangkun83** [comment]
LGTM

**Comment by pherl** [comment]
Merged manually into a new branch.

**Pull request closed without merging**
