### PR TITLE
Remove the C# Freeze API

### PR DESCRIPTION
**Pull request by jtattermusch**
Based on the pushback in the API review, I think the best thing to do is to remove the Freeze API for now (as requested by @pherl).
We can reintroduce this once we reach decision if we should support Freeze or not.  Reverting this change should be easy, applying an inverted diff and regenerating code is pretty straightforward.

### CODE REVIEW

**Comment by jskeet** [comment]
LGTM so far, although I'd probably have gone further. Merging, and we can work out whether to remove more later (but not much later).

**Comment by MHDante** [comment]
As a curiosity, is this change permanent? The mutability of messages has bit my team few times.

**Comment by jskeet** [comment]
Yes, I'd be very surprised if we reimplemented Freeze at this point.

**Comment by Falco20019** [comment]
I would also like to see immutability come back some time since it would fit our needs better and would fit better with the other platforms.

**Comment by jskeet** [comment]
@Falco20019: I think at this point it would make more sense to have an entirely separate generator (and support library) for immutable protobufs. I'm glad we removed Freeze - it's a pain working with types that *might* be immutable or might not be.
If record types end up in C# 9, I can easily imagine we might want to have a version that works with those.

**Pull request merged**
