### PR TITLE
Add preserve_proto_field_names option to JsonPrintOptions

### PR DESCRIPTION
**Pull request by mojoBrendan**
As requested in #2432 

I'm not sure if this is best implemented in JsonObjectWriter or elsewhere.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by mojoBrendan** [comment]
I signed it!

**Comment by mojoBrendan** [comment]
This change is closer to the java and python options.

**Comment by xfxyjwf** [comment]
ok to test

**Comment by xfxyjwf** [comment]
Thanks! The change looks good to me. I'll merge after the tests pass.

**Comment by timotheecour** [comment]
@mojoBrendan @xfxyjwf  not very clear from the PR whether it also works in reverse direction:
is there an option in `JsonStringToMessage` to read snake case (as opposed to just camelCase) ?

**Comment by xfxyjwf** [comment]
@timotheecour For JsonStringToMessage, it will accept both camelCase and snake_case. No need to set an option.

**Pull request merged**
