### PR TITLE
Php notice silent (fast fix enum notices)

### PR DESCRIPTION
**Pull request by Sufir**
Fast fix for this issue https://github.com/google/protobuf/issues/2465

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by TeBoring** [comment]
I think this has been fixed in 3.2.x branch. Could you help verify?

**Comment by TeBoring** [comment]
Commit e259b515a5baae2d7d7623af62ea87079a5e91a0 added a test to verify this case.

**Comment by Sufir** [comment]
@TeBoring no it not fixed. In 3.2.x-dev #e259b515a5baae2d7d7623af62ea87079a5e91a0
I still see notices

> Notice: Undefined index: .SU13.Click.Type in ../vendor/google/protobuf/php/src/Google/Protobuf/Internal/DescriptorPool.php on line 125

> Notice: Undefined index: in ../vendor/google/protobuf/php/src/Google/Protobuf/Internal/DescriptorPool.php on line 126

Just use `error_reporting = E_ALL` for development.

**Comment by TeBoring** [comment]
Not sure 3.2.x-dev reflect the latest change.
You can download the code and run the test directly. Or can you paste your
test case here?

**Comment by Sufir** [comment]
My test case very saimple:

```
; php.ini
error_reporting = E_ALL
```

```
// composer.json
    "require": {
        "google/protobuf": "3.2.x-dev" // or master
    },
    "autoload": {
        "files": [
          "src/click.pb.php"
        ]
    }
```

```
<?php
// index.php
require 'vendor/autoload.php';
```

In output:
Output

Here source proto and generated code: https://gist.github.com/Sufir/e5892fd48dfd7b7affb30a65f5489458

**Comment by Sufir** [comment]
> Not sure 3.2.x-dev reflect the latest change.
What branch reflect latest change, if not master and not 3.2.x?

**Comment by TeBoring** [comment]
Sorry, I cannot find the 3.2.x-dev tag on https://packagist.org/packages/google/protobuf.
I think the tag on packagist is not updated, so there is no tag reflecting latest changes.

**Comment by TeBoring** [comment]
I just update packagist with the latest change. Now you can try again in your way.

**Comment by Sufir** [comment]
Now I tried 
#e259b515a5baae2d7d7623af62ea87079a5e91a0 from 3.2.x branch,
#60d4f8af483e0234ee5b7f7544bcd578a34412ad from tag 3.2.x-dev,
#fb71df9f0b5a8457255e35cd4cd19c46396e97f1 from master branch
same result. Notice not fixed, offset undefind.

**Comment by TeBoring** [comment]
Have you re-generate your code?

**Comment by Sufir** [comment]
No code not re-generate. That was generated by [latest release protoc v3.1.0](https://github.com/google/protobuf/releases/tag/v3.1.0)

**Comment by TeBoring** [comment]
I think you need to re-compile the code generator from source and use that to re-generate code.

**Comment by TeBoring** [comment]
https://github.com/google/protobuf/tree/master/src
You can follow this link to compile the protobuf compiler.

**Comment by TeBoring** [comment]
Does it work?

**Comment by chxj1992** [comment]
re-compiling protoc from source(master branch) doesn't solve the issue

**Pull request closed without merging**
