### PR TITLE
Adds a podspec for the proto3 Objective-C runtime.

### PR DESCRIPTION
**Pull request by jcanizales**
Users that manage their dependencies with Cocoapods need this to be able and use libraries generated by protoc.

### CODE REVIEW

**Comment by jcanizales** [comment]
@thomasvl @dmaclach FYI, per our conversation this morning.

**Comment by thomasvl** [comment]
The _PackagePrivate files still need to be #imported into the generated pbobjc.m files, so do they still end up exposed for that to work?

This puts the podspec at the top of the tree but doesn't name in any way to indicate it is only the runtime, aren't we eventually going to need a way to get the source and also the compiler so someone can compile their own protos?  How do we place those next too it?

Should we add this file to objectivec_EXTRA_DIST in Makefile.am to it gets including in generated zips/tarballs?

**Comment by jcanizales** [comment]
> The _PackagePrivate files still need to be #imported into the generated pbobjc.m files, so do they still end up exposed for that to work?

Not directly, right? Currently I only see `GPBProtocolBuffers.h` and `GPBProtocolBuffers_RuntimeSupport.h` imported explicitly, so we could declare those two as the only public headers and the generated library would still work. Actually that'd reduce the pollution of the headers search path, so I think I should do it. It would prevent people from, say, importing only `PBArray.h` to declare a category, but I think it's worth it.

> This puts the podspec at the top of the tree but doesn't name in any way to indicate it is only the runtime, aren't we eventually going to need a way to get the source and also the compiler so someone can compile their own protos? How do we place those next too it?

The current way to compile protos is to install protoc on one's machine (either by cloning this repo + make install, or using a homebrew recipe someone's creating). Cocoapods won't be able to cover that dependency use case as Bazel does, because the authors don't want to have anything to do with build steps, only installing dependencies in your XCode project.

Still someone might want to use Cocoapods to write an OSX app that depends on the compiler code, but when the use case comes, we can put the runtime library and the compiler library as different subspecs inside the podspec file. That's better than using two different podspecs in that it's cleaner for the repo: The podspec does need to be at the top of the tree.

> Should we add this file to objectivec_EXTRA_DIST in Makefile.am to it gets including in generated zips/tarballs?

No, Cocoapods will just fetch it from this git repo no problem. When the 3.0.0 release is official, though, we will want to send a (slightly modified) copy of it to the Cocoapods repo; I'll be sure to do that. Without that, users have to manually point Cocoapods to `'https://github.com/google/protobuf.git'`, which is a pain.

**Comment by jcanizales** [comment]
>> The _PackagePrivate files still need to be #imported into the generated pbobjc.m files, so do they still end up exposed for that to work?

> Not directly, right? Currently I only see `GPBProtocolBuffers.h` and `GPBProtocolBuffers_RuntimeSupport.h` imported explicitly, so we could declare those two as the only public headers and the generated library would still work. Actually that'd reduce the pollution of the headers search path, so I think I should do it. It would prevent people from, say, importing only PBArray.h to declare a category, but I think it's worth it.

Actually I was wrong: If only `GPBProtocolBuffers.h` and `GPBProtocolBuffers_RuntimeSupport.h` are declared public, they can't import things like `GPBArray.h` themselves. Which indicates the generated `.pbobjc.m` were not importing the `_PackagePrivate.h` files neither directly nor indirectly. Is that expected?

**Comment by thomasvl** [comment]
On Thu, May 14, 2015 at 7:05 PM, Jorge Canizales <notifications@github.com>
wrote:

> The _PackagePrivate files still need to be #imported into the generated
> pbobjc.m files, so do they still end up exposed for that to work?
>
> Not directly, right? Currently I only see GPBProtocolBuffers.h and
> GPBProtocolBuffers_RuntimeSupport.h imported explicitly, so we could
> declare those two as the only public headers and the generated library
> would still work. Actually that'd reduce the pollution of the headers
> search path, so I think I should do it. It would prevent people from, say,
> importing only PBArray.h to declare a category, but I think it's worth it.
>
If you look at
https://github.com/google/protobuf/blob/master/objectivec/google/protobuf/Descriptor.pbobjc.m,
you'll see it directly imports RuntimeSupport, and that intern imports
the _PackagePrivate headers.  So when the generated protos those headers
need to be importable.

 This puts the podspec at the top of the tree but doesn't name in any way
> to indicate it is only the runtime, aren't we eventually going to need a
> way to get the source and also the compiler so someone can compile their
> own protos? How do we place those next too it?
>
> The current way to compile protos is to install protoc on one's machine
> (either by cloning this repo + make install, or using a homebrew recipe
> someone's creating). Cocoapods won't be able to cover that dependency use
> case as Bazel does, because the authors don't want to have anything to do
> with build steps, only installing dependencies in your XCode project.
>
That isn't true.  You can check out the code, do a build, and you get a
protoc that you can run from the build location.   So it could be all be
done within a checkout and never install into the machine.

Still someone might want to use Cocoapods to write an OSX app that depends
> on the compiler code, but when the use case comes, we can put the runtime
> library and the compiler library as different subspecs inside the podspec
> file. That's better than using two different podspecs in that it's cleaner
> for the repo: The podspec does need to be at the top of the tree.
>

Ok, should we add Runtime then to this one so we start to carve out the
space for different subspecs?


>  Should we add this file to objectivec_EXTRA_DIST in Makefile.am to it
> gets including in generated zips/tarballs?
>
> No, Cocoapods will just fetch it from this git repo no problem. When the
> 3.0.0 release is official, though, we will want to send a (slightly
> modified) copy of it to the Cocoapods repo; I'll be sure to do that.
> Without that, users have to manually point Cocoapods to '
> https://github.com/google/protobuf.git', which is a pain.
>

I'm not so worried from that pov, it's more from the POV of the zip/tarball
should be a copy of the repo (i.e. - match what you get from a checkout).

**Comment by jcanizales** [comment]
> If you look at [Descriptor.pbobjc.m] (https://github.com/google/protobuf/blob/master/objectivec/google/protobuf/Descriptor.pbobjc.m),
you'll see it directly imports RuntimeSupport, and that intern imports the _PackagePrivate headers.  So when the generated protos those headers need to be importable.

Right. It's weird that everything worked alright when I made them private. Must be a Cocoapods bug. I've made all the headers public now.

> That isn't true. You can check out the code, do a build, and you get a protoc that you can run from the build location. So it could be all be done within a checkout and never install into the machine.

Ah sweet, but that's not the issue though: for XCode to pick up changes in the .proto and trigger a rerun of protoc, that'd need to be set as a special build phase (or as a build rule) in the XCode project. But a podspec can't instruct Cocoapods to do such a thing to a project (there have been workarounds, but the Cocoapods authors are moving away from them). Much less can we make it trigger a rebuild for changes in protoc's code itself. For those things we need Bazel.

> Ok, should we add Runtime then to this one so we start to carve out the space for different subspecs?

I don't think it's necessary, as the specs themselves are versioned. I've done it before in the gRPC podspec without disruption.

**Comment by jcanizales** [comment]
> the zip/tarball should be a copy of the repo (i.e. - match what you get from a checkout).

If that's the case then I'll add it.

**Comment by thomasvl** [comment]
On Fri, May 15, 2015 at 12:57 AM, Jorge Canizales <notifications@github.com>
wrote:

> If you look at Descriptor.pbobjc.m
> <https://github.com/google/protobuf/blob/master/objectivec/google/protobuf/Descriptor.pbobjc.m>
> ,
> you'll see it directly imports RuntimeSupport, and that intern imports the
> _PackagePrivate headers. So when the generated protos those headers need to
> be importable.
>
> Right. It's weird that everything worked alright when I made them private.
> Must be a Cocoapods bug. I've made all the headers public now.
>
> That isn't true. You can check out the code, do a build, and you get a
> protoc that you can run from the build location. So it could be all be done
> within a checkout and never install into the machine.
>
> Ah sweet, but that's not the issue though: for XCode to pick up changes in
> the .proto and trigger a rerun of protoc, that'd need to be set as a
> special build phase (or as a build rule) in the XCode project. But a
> podspec can't instruct Cocoapods to do such a thing to a project (there
> have been workarounds, but the Cocoapods authors are moving away from
> them). Much less can we make it trigger a rebuild for changes in protoc's
> code itself. For those things we need Bazel.
>

You're mixing arguments.  Before you said you said the issue was that devs
had to install protoc to compile protos, which isn't true.  Now you are
saying the issue is there is no way for podspecs to know how to regenerate
when based on a .proto change.  That was true for installs also; but the
argument is different that your reason last time.  The point still holds, a
spec could be used to get the compiler and have it built.  Yes, a bit of
custom script/makefile might be needed to fully add the .protos into the
build process, but that doesn't seem to mean we shouldn't have an easy way
to get the compiler pulled/built to then use, no?

**Comment by jcanizales** [comment]
Sorry for not being clear. I was initially replying to:

> aren't we eventually going to need a way to get the source and also the compiler so someone can compile their own protos

By saying that:
* We _already_ have a way to get the source and the compiler, for people to compile their protos.
* Cocoapods can't help people do that.

I didn't mean installation was an issue; rather that installation solved that use case. The fact that there's a 3rd way to run protoc that doesn't involve installation is not relevant; rather it's yet another way that use case is solved, so it strengthens the argument.

Cocoapods won't run protoc (nor make XCode run it), because it doesn't want to get involved in build steps. And it won't recompile protoc's source if necessary, because it only manages dependencies among libraries that are part of the final app, not among tools too. So the only use case for a podspec of the compiler code is for someone that wants to use that code directly in their app (some OSX app).

**Comment by jcanizales** [comment]
We agree that we should have an easy way to get the compiler pulled/built to then use. Cocoapods, unfortunately, isn't.

**Comment by jcanizales** [comment]
Friendly ping

**Comment by jcanizales** [comment]
I'm not really sure who has merge access... @TeBoring ?

**Pull request merged**
