### PR TITLE
Update gmock links.

### PR DESCRIPTION
**Pull request by pherl**
Cherry-pick commit to the master into the javalite branch.

The original link is no longer available.

### CODE REVIEW

**Comment by pherl** [comment]
for https://github.com/google/protobuf/issues/2266

**Comment by xfxyjwf** [comment]
bazel tests are failing. I think we need to update the WORKSPACE file as well.

**Comment by xfxyjwf** [comment]
ok to contribute

**Comment by xfxyjwf** [comment]
I have no idea how the CLA check works.. Seems broken to me.

**Pull request merged**
