### PR TITLE
Internal merge

### PR DESCRIPTION
**Pull request by haberman**

### CODE REVIEW

**Comment by haberman** [comment]
Commits were authored by Jisi who is a Googler, so it is ok.

**Comment by haberman** [comment]
Looks like Jenkins tests have passed. @xfxyjwf, want to take a look?

**Comment by xfxyjwf** [comment]
LGTM

Thanks!

**Comment by haberman** [comment]
The one Travis failure is also failing at head (objectivec_osx), so I'm going to merge this now.

**Pull request merged**
