### PR TITLE
Merge protobuf C# into master

### PR DESCRIPTION
**Pull request by jtattermusch**
This is a huge change, but all the contained changes have already been approved before they have been merged into csharp branch.

This pulls:
-- the rewritten version of C# codegen (under src/google/protobuf/compiler/csharp)
-- the C# runtime library (under csharp/)

csharp/README.md contains basic info about C# protobufs.

### CODE REVIEW

**Comment by jtattermusch** [comment]
@anandolee, @pherl please take a look.

**Comment by anandolee** [comment]
Yes, with syntax = "proto2" there's no change for the C# runtime.

Just not sure if the discussion this morning is let users to download C# runtime from old repo or here? @pherl

**Comment by anandolee** [comment]
@TeBoring 
If you will do upintegrade after this merge, you may need to remove "option csharp_namespace = "Google.ProtocolBuffers.DescriptorProtos";" in desriptor.proto

**Comment by jtattermusch** [comment]
Please let me know if there's some more inputs I can provide to make this review go smooth.

**Comment by pherl** [comment]
@anandolee The generated code needs to be compatible with the old runtime. Users are supposed to be able to use either.

**Comment by jtattermusch** [comment]
The generated code is is compatible with the old C# runtime library once you specify syntax = "proto2", which is clearly stated in csharp/README.md.
Obviously, the generated code is also compatible with the new C# runtime library (that's part of this pull request), but we are not planning to provide NuGet package for the new C# runtime library yet.

**Comment by anandolee** [comment]
This request is good to merge because all contributions are reviewed under charp branch.

For cla:no
Details about C# proto2 CLA signers and consent to contribute can be found in go/csharp-protobuf-migration document.

**Pull request merged**
