### PR TITLE
Remove redundant `the`.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Rebased.

**Comment by dongjoon-hyun** [comment]
Hi! This is just a simple typo fix for only comments.

**Comment by haberman** [comment]
Looks good, but could you re-wrap the lines that are now shorter? Also there's one string that looks like it might all fit on the same line now.

**Comment by dongjoon-hyun** [comment]
Sure! You mean the line of 'objectivec/DevTools/pddm.py', right?

**Comment by dongjoon-hyun** [comment]
@haberman . For `ppmd.py`, I can make it shorter, i.e., one line, but for the others, I think re-wrap is not necessary. Could you point some lines that you think strange?

**Comment by haberman** [comment]
Looks good, thanks.

**Comment by dongjoon-hyun** [comment]
Thank you, @haberman !

**Pull request merged**
