### PR TITLE
C#: Fix NullReferenceException in CodedInputStream.Dispose

### PR DESCRIPTION
**Pull request by yaakov-h**

### CODE REVIEW

**Comment by yaakov-h** [comment]
I signed it!

**Comment by yaakov-h** [comment]
Travis job 3014.13 seems to be stuck...

**Comment by yaakov-h** [comment]
... Anybody?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by acozzette** [comment]
retest this please (this should re-run the CI jobs)

**Comment by yaakov-h** [comment]
That looks better, the failing build above looks like the original one, not a new one.

**Comment by acozzette** [comment]
@anandolee Do you want to review this pull request? I don't really know C# so I wouldn't be able to review it well.

I'm confused about the Travis results; it claims that there was an error with the C# build, but on the other hand when I look through the log everything looks fine.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by anandolee** [comment]
Sorry, I missed this request. Will review it tomorrow

**Comment by yaakov-h** [comment]
In attempting to resolve the merge conflict, it appears that this exception has now already been fixed, albeit in a slightly different manner.

Whoops! 😅

**Pull request closed without merging**
