### PR TITLE
Make PHP c extension work with PHP7

### PR DESCRIPTION
**Pull request by TeBoring**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by TeBoring** [comment]
Fixed #2840, #2151, #2187

**Comment by jessedobbelaere** [comment]
@TeBoring Any idea when there will be a pecl package release for 3.3.x to test this out? 
I'll try it out and build from source meanwhile. Curious about the speed improvements compared to the php package.

**Comment by TeBoring** [comment]
ETA for 3.3 release is end of this week.
We did benchmark for prototype with php5.5. The improvement was about 10X.

**Pull request merged**
