### PR TITLE
Add -DHAVE_ZLIB to the bazel BUILD rule.

### PR DESCRIPTION
**Pull request by yasushi-saito**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by xfxyjwf** [comment]
ok to test

**Comment by xfxyjwf** [comment]
I don't see a dependency on zlib for the cc_library/cc_binary rules. Is it an implicit dependency for all cc_library/cc_binary rules?

**Comment by anandolee** [comment]
Closing for no response. Feel free to reopen

**Pull request closed without merging**
