### PR TITLE
Fixed "make distcheck" for the Autotools build

### PR DESCRIPTION
**Pull request by acozzette**
To make the test pass I needed to fix out-of-tree builds and add another
build artifact to CLEANFILES.

### CODE REVIEW

**Comment by xfxyjwf** [comment]
The travis test is still failing. Probably need to add jsembed.cc to a DIST list or something?

**Comment by acozzette** [comment]
retest this please

**Comment by acozzette** [comment]
@xfxyjwf I've now updated EXTRA_DIST and so I think everything should finally be working. Do you think I should wait for another Travis run to be safe or merge this sooner than that?

**Comment by acozzette** [comment]
retest this please

**Comment by xfxyjwf** [comment]
Please wait for the travis test.

**Comment by acozzette** [comment]
The Bazel CI build failed but it doesn't seem to be related to my change so I'll go ahead and merge this to fix the Travis failure.

**Pull request merged**
