### PR TITLE
Fix missing import of jspb.Map (#1885)

### PR DESCRIPTION
**Pull request by gegles**
Fix missing import of jspb.Map (#1885)

### CODE REVIEW

**Comment by gegles** [comment]
I signed it!

**Comment by haberman** [comment]
Could you take a quick look and see if we have any tests that serialize/deserialize a map? If not, let's add one and hopefully it will exercise this code path.

**Comment by gegles** [comment]
@haberman, I had looked for it already, but could not find any. I am pretty new to codebase, where would you want me to add one? Can you point me to the right file/section?

**Comment by haberman** [comment]
Ah, I think I found the problem. Internally we have a `maps_test.js` that tests this, but I missed that file when we open-sourced the new maps code.

For now let's just add a quick test in `js/binary/proto_test.js`. You can use the `TestMapFields` message from `testbinary.proto`. Let's just make sure a message with some map data can round-trip to binary format and back.

Thanks and sorry for the bug!

**Comment by haberman** [comment]
I'll merge this for now and we can worry about a test later.

**Pull request merged**
