### PR TITLE
fix attributes warning

### LINKED ISSUE #2802: "warning: type attributes ignored after type is already defined [-Wattributes]" caused by dllexport_decl
Since the update to protobuf 3.2 I get a lot of __type attributes ignored after type is already defined [-Wattributes]__ warnings, using gcc 6.3.
These are caused by `$dllexport_decl$` in [`"friend struct $dllexport_decl$ $file_namespace$::TableStruct;\n"`](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_message.cc#L1465). Removing the expression fixed the issue.

### PR DESCRIPTION
**Pull request by hesmar**
fixes #2802

### CODE REVIEW

**Comment by hesmar** [comment]
I signed it!

**Comment by acozzette** [comment]
ok to test (this will just trigger the remaining CI bots to run)

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by acozzette** [comment]
Thanks @hesmar!

**Pull request merged**
