### PR TITLE
Fix Protobuf.podspec

### PR DESCRIPTION
**Pull request by TeBoring**

### CODE REVIEW

**Comment by TeBoring** [comment]
@thomasvl @jcanizales

**Comment by TeBoring** [comment]
@thomasvl @jcanizales : Previously, if someone depends his project on protobuf, files not listed in source_files could not be found. Use the elder version that list all files in source_files.

**Comment by thomasvl** [comment]
LG, but i'm really deferring to @jcanizales

**Comment by jcanizales** [comment]
I'll take a closer look after the gRPC Beta frenzy :) For the moment, this is the best option.

**Pull request merged**
