### PR TITLE
Update io_win32_unittest.cc

### PR DESCRIPTION
**Pull request by ybsave**
Fix the same issue mentioned in #3533.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ybsave** [comment]
@googlebot already signed

**Comment by pherl** [comment]
There are also non C++11 usages that we need to remove as well. I have sent out https://github.com/google/protobuf/pull/3769

**Comment by pherl** [comment]
It should have been fixed in #3769 Thanks for the patch though!

**Pull request closed without merging**
