### PR TITLE
Ruby: make sure map parsing frames are GC-rooted.

### PR DESCRIPTION
**Pull request by haberman**
Fix for https://github.com/google/protobuf/issues/2004

Review to @nicolasnoble.

### CODE REVIEW

**Comment by haberman** [comment]
retest this please

**Comment by nicolasnoble** [comment]
cc @murgatroid99

**Comment by nicolasnoble** [comment]
Your CI ruby tests don't seem very happy :)

**Comment by haberman** [comment]
That's better. :) Jenkins is happy now, hopefully Travis will follow suit.

**Comment by haberman** [comment]
Ok tests are all green, merging.

**Comment by haberman** [comment]
Btw, if you have any comments on the change, let me know and I can submit a follow-up change.

**Comment by haberman** [comment]
Sorry I submitted before LGTM, I wanted a chance to get it into the impending protobuf 3.0.2 release.

**Comment by timanovsky** [comment]
Hi, can you guys publish 3.0.2 gem please?

**Pull request merged**
