### PR TITLE
Remove the protobuf-module.cmake file.

### PR DESCRIPTION
**Pull request by yeswalrus**
This file is a clone of the old FindProtobuf.cmake module, but enabling it encourages use of out of date practices. Better to remove it entirely and get users to use more modern constructs. If users simply MUST have the old functionality they can use the FindProtobuf.cmake file included in CMake since 2.8

### CODE REVIEW

**Comment by xfxyjwf** [comment]
@podsvirov, could you take a look at this pull request? I'll merge this pull request if removing that file looks good to you.

**Comment by podsvirov** [comment]
Hi @xfxyjwf, and thank you are granting my opinion.

I often say, we do not need a revolution, but we need evolution.

When I make changes to CMake project, I want to provide enhanced functionality to preserving backward compatibility. I do not see anything wrong with that.

CMake tool for a long time include built-in FindProtobuf.cmake module to work with protobuf.

I want to ensure a smooth transition:
find_package(Protobuf) => find_package(Protobuf CONFIG)
find_package(Protobuf CONFIG) => find_package(protobuf CONFIG)

CMake users long used protobuf and call it Protobuf.

I have studied the changes from @yeswalrus . And I think he has a good ideas. But he does not like backward compatibility. In particular, PR #1578 has disrupted work of protobuf-module.cmake script.

Dear @xfxyjwf, please do not merge these changes.

In the near future I will try to improve the protobuf-module.cmake script.
Also to remind you that I have provided the option to disable this functionality.

**Comment by yeswalrus** [comment]
Preserving backwards compatibility is great, and I'd be happy to do some work to enable it if that's the direction for the module, but this is a major release version which is the only appropriate time to make such a breaking change. I'm of the opinion that in the new version it should be as easy as possible to use the new, preferred method, while still being possible to use the older one (which it is, using the FindProtobuf module shipped with CMake.)

Users of the old MODULE will still be able to use identical syntax - New users or upgrading users will need to use the CONFIG option since CMake ships with a find module anyways, and it should not be difficult for them to switch from Protobuf to protobuf at the same time.

**Comment by podsvirov** [comment]
@yeswalrus imported targets it's good! But how easy to use the protobuf::protoc target to generate code?

Module now provide two methods protobuf_generate_cpp and protobuf_generate_python.
I wish that these methods were available to CONFIG mode.

I am working hard to improve based on your ideas. Changes need to be broken down into individual requests. Watch now click [there](https://github.com/google/protobuf/compare/master...podsvirov:topic-cmake-project).

**Comment by yeswalrus** [comment]
@podsvirov Very easy! 
```
add_custom_command( 
  OUTPUT foo.pb.h foo.pb.cpp
  COMMAND protobuf::protoc 
  ARGS "--cpp_out=${CMAKE_CURRENT_BINARY_DIR} foo.proto"
  MAIN_DEPENDENCY foo.proto
  COMMENT "Generating foo.pb.cc and foo.pb.h"
```
I would rather add proper documentation and an example of how to use add_custom_command. I still think continuing support for those custom functions is a mistake.
For one, protoc suports far more than just C++ and Python. Supporting those two implies that we should have support for the others as well. What about, for example, c#? What if users want to use custom command line arguments for protoc such as an import path? Neither of those use cases is supported by the legacy functions.

I'll grant you, there's some repetition there so a simple custom function might help reduce the amount of boiler plate.
A better function would: 
- Be language agnostic
- Allow custom arguments to protoc
- handle cmake 3.3+'s ability to specify sources after target declarations using target_sources

A rough sketch of usages:
```
protobuf_generate(PROTOFILES foo.proto LANGUAGES cpp python OUT_VAR foo_SRCS)
add_library(foo "${foo_SRCS}")
...
add_library(foo "... foo.pb.h foo.pb.cpp")
add_library(foo_py "... foo_py3.py"
protobuf_generate(TARGET foo)
protobuf_generate(TARGET foo_py)
```
An alternative (or extended) function could examine the source files for a given target looking for known suffixes, and add the appropriate rules to generate them or, in cmake 3.3+, insert the generated source files directly into the target sources.

For reference, I'm using these 2 resources (as well as my own experience) as style guides.
```
http://www.slideshare.net/DanielPfeifer1/cmake-48475415
https://rix0r.nl/blog/2015/08/13/cmake-guide/
```

**Comment by yeswalrus** [comment]
@podsvirov More detailed feedback of your in progress pr can be found here: https://github.com/yeswalrus/protobuf/pull/1

**Comment by yeswalrus** [comment]
To be very clear: Removing this file in no way breaks backwards compatibility with versions prior to 3.0.0 (though it could potentially cause *minor* inconvienience to people presently using 3.0.0-beta versions). Users that want to use the FindProtobuf.cmake module can still do so with `find_package(Protobuf MODULE), as it is separately maintained as part of the CMake project.

This file was *added* in the 3.0.0 beta line, and is essentially a duplicate of the FindProtobuf.cmake module provided by CMake natively. If it is included in the final release it will have to be supported until Protobuf 4.0.0, assuming the protobuf project only allows breaking changes at major version increments). At the very least, it's inclusion should be disabled by default.

If there are concerns about forcing users to call add_custom_command directly (which is the recommended practice in the modern cmake style guides which are available), they can be addressed in a separate PR with a function superior to the existing ones provided by the FindProtobuf.cmake module.

**Comment by podsvirov** [comment]
@yeswalrus in general I agree with you, but still want to keep this feature (disabled by default).
Some users do not want to study the arguments allowed the individual instruments and are satisfied with the default behavior.
We can realize protobuf_generate within our exported configuration?
I propose to implement the examples/CMakeLists.txt file (already in my operating time) and show his example of the use of old and new approaches.

**Comment by yeswalrus** [comment]
Fair enough, I'll close this one for now. I still don't think it's a great plan, but perhaps we can revisit this down the line. What specific legacy features do you want to support? Are you saying that you'd be ok with a protobuf_generate function? We can totally build that in the exported configuration file. I agree, the examples should be added as a top priority. I may grab your work and submit a pr, I'll be sure to ping you when I do.

**Comment by podsvirov** [comment]
Hello @yeswalrus, thank you for coming to meet me.

I create PR #1642.

**Pull request closed without merging**
