### PR TITLE
PHP: fix ZTS tsrm_ls errors

### LINKED ISSUE #2186: [pecl] TS build is broken
```
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c: In function 'appendbool_handler':
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:210:115: error: 'tsrm_ls' undeclared (first use in this function)
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:210:115: note: each undeclared identifier is reported only once for each function it appears in
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c: In function 'appendint32_handler':
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:211:174: error: 'tsrm_ls' undeclared (first use in this function)
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c: In function 'appenduint32_handler':
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:212:176: error: 'tsrm_ls' undeclared (first use in this function)
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c: In function 'appendfloat_handler':
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:213:172: error: 'tsrm_ls' undeclared (first use in this function)
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c: In function 'appendint64_handler':
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:214:174: error: 'tsrm_ls' undeclared (first use in this function)
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c: In function 'appenduint64_handler':
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:215:176: error: 'tsrm_ls' undeclared (first use in this function)
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c: In function 'appenddouble_handler':
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:216:174: error: 'tsrm_ls' undeclared (first use in this function)
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c: In function 'appendstr_handler':
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:224:60: error: 'tsrm_ls' undeclared (first use in this function)
       (RepeatedField*)zend_object_store_get_object(array TSRMLS_CC);
                                                            ^
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:230:3: error: too many arguments to function 'repeated_field_push_native'
   repeated_field_push_native(intern, &str TSRMLS_CC);
   ^
In file included from /builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:31:0:
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/protobuf.h:383:6: note: declared here
 void repeated_field_push_native(RepeatedField *intern, void *value);
      ^
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c: In function 'appendbytes_handler':
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:240:60: error: 'tsrm_ls' undeclared (first use in this function)
       (RepeatedField*)zend_object_store_get_object(array TSRMLS_CC);
                                                            ^
/builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:246:3: error: too many arguments to function 'repeated_field_push_native'
   repeated_field_push_native(intern, &str TSRMLS_CC);
   ^
In file included from /builddir/build/BUILD/php-pecl-protobuf-3.1.0/ZTS/encode_decode.c:31:0:

   <snip>
```

### PR DESCRIPTION
**Pull request by stanley-cheung**
Fixes #2186 

To reproduce:
 - compile PHP from source with `./configure --enable-maintainer-zts`
 - then compile the protobuf extension

### CODE REVIEW

**Comment by TeBoring** [comment]
Do I need to recompile PHP or just protobuf's extension with enable-maintainer-zts?

**Comment by TeBoring** [comment]
Is there any command line to install php with zts?

**Comment by stanley-cheung** [comment]
As far as I know, you need to re-compile PHP with `./configure --enable-maintainer-zts` manually to enable ZTS

**Comment by TeBoring** [comment]
ok to test

**Comment by TeBoring** [comment]
php/ext/google/protobuf/array.c:163:8: error: too few arguments to function 'native_slot_set'

**Comment by TeBoring** [comment]
jenkins is able to test zts build now.

**Comment by TeBoring** [comment]
LGTM

**Pull request merged**
