### PR TITLE
Fixed C++ size_t warning on x64

### PR DESCRIPTION
**Pull request by yangga**
Fixed some C++ compile warnings on x64 platform.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by yangga** [comment]
I signed it!

**Comment by yangga** [comment]
I signed it!

**Comment by yangga** [comment]
okay, check it again

**Comment by yangga** [comment]
I signed it!

**Comment by yangga** [comment]
okay, i changed email

**Comment by yangga** [comment]
I signed it!

**Comment by yangga** [comment]
I signed it!

**Comment by yangga** [comment]
I signed it!

**Comment by yangga** [comment]
Okay, I changed my profile. I didn't set my public email and name.

**Comment by yangga** [comment]
I signed it!

**Comment by yangga** [comment]
I signed it!

**Comment by yangga** [comment]
recheck my CLA

**Comment by yangga** [comment]
I signed it!

**Comment by xfxyjwf** [comment]
@yangga I think the problem is: the email address of one of the commits is not associated with your github account. Can you redo the commits with the correct email address?

**Comment by xfxyjwf** [comment]
The email address at question is:
Author: yangga <swyang@smilegate.com>

**Comment by pherl** [comment]
Unfortunately those are part of public APIs that we cannot change. Users are taking pointers on the functions or use templates which will be broken by a function signature change.

One example is ByteSize(). It returns int, and we would have to introduce another API ByteSizeLong() to make it return size_t, even though it's implicitly convertible.

**Comment by yangga** [comment]
Gotcha~

**Pull request closed without merging**
